### ISSUE TITLE
[Programming Model] Entry Point

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-powershell-worker#1]
## Script File 

PowerShell support for Functions will support a run file of **.ps1** format. We'll use the workflow below to determine which file to run:

_If_ the **"scriptFile"** attribute is set in **function.json**
_Else if_ the project contains a single **.ps1** file
_Else if_ **run.ps1** is present
_Else_ throw an error

## Entry Point 
Instead of running a plain script, we'll define a  method for the runtime to invoke during an execution.  We'll use the workflow below to determine which function to run:

_If_ the **"entryPoint"** attribute is set in **function.json**
_Else if_ **Run()** is present
_Else_ throw an error

**Comment by asavaritayal** [comment]
@pragnagopa do you have an update on this? 

> `Else if the project contains a single .ps1 file` - this is relatively straight forward for us to implement, but I'd need to see what the host sends us if there is no `run.ps1`.

**Comment by tylerl0706** [comment]
I tested this out and the host gives the path of the single ps1 in the directory. So that works as expected.

So we really have all scenarios except for:

`Else if Run() is present` which would be tedious to implement and I don't think makes a lot of sense for powershell since you can very easily declare parameters of a script by putting a param block at the top.

**Comment by tylerl0706** [comment]
I'd like to close this issue if we all agree that that last scenario doesn't really make sense for PowerShell.

**Comment by pragnagopa** [comment]
Yes. Either use the default run.ps1 or let users specify an entry point.

**Comment by asavaritayal** [comment]
> Else if Run() is present which would be tedious to implement and I don't think makes a lot of sense for powershell since you can very easily declare parameters of a script by putting a param block at the top.

Agreed that it may not make sense in the case of PowerShell since we can run the script directly. I'm good to go ahead and close this issue.
