### ISSUE TITLE
Container story

### ISSUE THREAD

**Issue by tylerl0706** [Azure/azure-functions-powershell-worker#10]
Can we use the CloudShell image and work off of that or do we need to use some Azure Functions base image?

I'm thinking about authentication with Azure. How can a user's script manage azure resources without doing heavy authentication lifting in their function?

cc @asavaritayal @pragnagopa

**Comment by tylerl0706** [comment]
This is being addressed here:
https://github.com/Azure/azure-functions-docker/pull/27

**Comment by asavaritayal** [comment]
Sorry, just catching up on this. We'll need to extend the azure-functions-base image to add PS and the PS language worker. Noticed the PR - I've added @ahmelsayed to review.

**Comment by tylerl0706** [comment]
We can close this since that PR is merged 😄
