### ISSUE TITLE
Close on script/module entry point

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-powershell-worker#101]
According to #1, we're definitely starting with `run.ps1` as the default entry point.

Two open questions then:

* have we already implemented `entryPoint` in `function.json` for scripts (e.g. foo.ps1)
* per the question posed in #17, does it make sense to implement `entryPoint` for .psm1? 

This is something we should decide we are or are not doing for the Preview milestone.

**Comment by joeyaiello** [comment]
We've decided that, for the time being, we're going to support `entryPoint` when you `scriptFile` is a .psm1, but not when it is a .ps1. We can revisit this in the future, but we currently think a shareable set of functions to be package as a module.

**Comment by daxian-dbw** [comment]
Closed via #116
