### ISSUE TITLE
Investigate/understand the WindowsCompatibility scenario

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-powershell-worker#102]
Today, there are limitations in the Windows consumption sandbox that prevent us from using the [WindowsCompatibility](https://github.com/powershell/windowscompatibility) module, namely that we don't have the ability to establish a WinRM connection to do implicit remoting over localhost.

I've heard a couple threads of investigation floated that we should pursue:
* Move WindowsCompatbility to use named pipes
* shelling out to `powershell.exe` appears to work, so we could streamline, wrap, or just doc that scenario as a helper

We should close on an approach/plan by the time we reach Preview.

**Comment by anirudhgarg** [comment]
Current workaround is to use powershell.exe, if we get customer feedback we will re-look at it.
