### ISSUE TITLE
[Linux Consumption] [Portal] Portal shows Linux Consumption as an option for Powershell 7.4 it is not supported

### ISSUE THREAD

**Issue by CooperLink** [Azure/azure-functions-powershell-worker#1039]
Bug bash - Portal is showing Linux Consumption as an option for Powershell 7.4 but the Consumption placeholder matching will not work as there are no placeholder pools with matching labels.

**Comment by CooperLink** [comment]
![image](https://github.com/Azure/azure-functions-powershell-worker/assets/46761504/4eb7cad6-7927-4160-a66c-cd00ae09dd3d)

**Comment by andystaples** [comment]
In Public Preview, only Windows SKUs will be available in the Portal. 
We will only add support for Linux in the portal once all SKUs are supported

**Comment by andystaples** [comment]
Dup of #1041
