### ISSUE TITLE
Enumerate additional documentation requirements for Preview

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-powershell-worker#104]
We've already got a bunch of `documentation` issues. We should figure out what other docs need to be written for Preview.

**Comment by joeyaiello** [comment]
Should include migration docs from the 1.0 runtime.

**Comment by joeyaiello** [comment]
* troubleshooting
* debugging with/without VS Code
* managed dependencies

**Comment by joeyaiello** [comment]
* (at least a nod) to enabling MSI support

**Comment by joeyaiello** [comment]
* Move debugging all up into the reference doc
* Not blocking preview on non-Code debugging
* troubleshooting: case-sensitivity, variable table cleared

**Comment by anirudhgarg** [comment]
Closing this issue.
