### ISSUE TITLE
[Linux Elastic Premium] Kudu SSH appears to fail for powershell7.4

### ISSUE THREAD

**Issue by CooperLink** [Azure/azure-functions-powershell-worker#1040]
Unable to connect to my Powershell 7.4 application using Kudu.  This could be for a variety of reasons. I have validated that the Powershell AppService image has the requisite tools. Investigating. It may be a dotnet 8 base image issue.

**Comment by andystaples** [comment]
I will test with 7.2 - if it works there, it becomes P1 and needs to be done before Linux support for 7.4
If it is not working in 7.2, we can wait

**Comment by andystaples** [comment]
Dup of #1041

**Comment by andystaples** [comment]
Works on PowerShell 7.2. Also tested on Java 21, as that is the only other runtime based on linux-bookworm instead of linux-bullseye, and it works there.

**Comment by andystaples** [comment]
Addressed by https://github.com/Azure/azure-functions-docker/pull/1054/files
