### ISSUE TITLE
Linux (Consumption) not supported in PowerShell 7.4 yet

### ISSUE THREAD

**Issue by andystaples** [Azure/azure-functions-powershell-worker#1041]

**Comment by andystaples** [comment]
Discussion for this can continue internally mid-May

**Comment by JBalhatchet** [comment]
Is support for this going to come out before 7.2 EOL?

**Comment by smoonlee** [comment]
Would love to know when this becomes GA

**Comment by joelfmrodrigues** [comment]
> Is support for this going to come out before 7.2 EOL?

Any official info published regarding this?

**Comment by smoonlee** [comment]
Can confirm you can now deploy PowerShell 7.4 

![image](https://github.com/user-attachments/assets/1b09505f-8b2c-4f54-9d5b-f97ca0e9d396)

![image](https://github.com/user-attachments/assets/a527a83f-d1ce-4034-b1d1-1ab3ecb8f199)


I've got a work in progress bicep configuration for this 
https://github.com/builtwithcaffeine/bwc-hugo-post-scheduler-source-files/blob/func/asp-lnx/bicep/hugoScheduler.bicep

**Comment by joelfmrodrigues** [comment]
I assume this would mean that it is now officially supported? Any official update published that can confirm this?

**Comment by smoonlee** [comment]
I see this: https://azure.microsoft.com/en-us/updates/v2/azure-functions-support-for-powershell-7-4

**Comment by joelfmrodrigues** [comment]
Thanks @smoonlee 
 I guess this makes things clear as upgrade instructions are already provided: https://github.com/Azure/azure-functions-powershell-worker/wiki/Upgrading-your-Azure-Function-Apps-to-run-on-PowerShell-7.4

**Comment by andystaples** [comment]
Resolved as of PS 7.4 GA
