### ISSUE TITLE
Better dependency / module management

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-powershell-worker#105]
Some older context in #69.

Our current experience (include `./Modules` as part of the `PSModulePath`) will remain until Azure Functions offers functionality to manage dependencies in a more programmatic way. 

Things we'd like to see from that implementation:

* the ability to query a function app for it's module dependencies
* the ability to provide a manifest of some kind (e.g. PSDepends' `requirements.psd1`) that specifies module name, version, and source instead of module files themselves
* the ability to deploy a module directly from the PowerShell Gallery to an Azure Functions App (similar to how Azure Automation works today)

Anything else?

**Comment by AnatoliB** [comment]
I'm not very clear on the first item. How would this be used?
> - the ability to query a function app for it's module dependencies

The rest seems to be covered by the Managed Dependencies feature, so I'm closing this for now.
