### ISSUE TITLE
a collision for Host ID "finctionsv4placeholdertempletesi" was detected in the configured storage account

### ISSUE THREAD

**Issue by juloora** [Azure/azure-functions-powershell-worker#1085]
I got a collision for host ID  error in my function app overview page why it is came how to over come this issue? please help me

**Comment by andystaples** [comment]
Hi @juloora 
Please refer to our documentation here on the Host ID Collision error: https://learn.microsoft.com/en-us/azure/azure-functions/errors-diagnostics/diagnostic-events/azfd0004
If you are not able to resolve this issue following the guidance from the doc, please reach out to Azure Support who can help using this link: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
Thanks
