### ISSUE TITLE
Powershell module ExchangeOnlineManagement  version 3.5.1 issue with azure functions

### ISSUE THREAD

**Issue by Sagarthore11** [Azure/azure-functions-powershell-worker#1088]
Hello All,

After the ExchangeOnlineManagement PowerShell module was released, we noticed that the latest version, 3.5.1, was released on July 11, 2024. Since then, the Azure Function app PowerShell has been failing with the following error. However, when we reverted back to version 3.5.0, it started working fine.

ERROR: Unable to find type [Microsoft.Exchange.Management.RestApiClient.ExchangeEnvironment].

https://www.powershellgallery.com/packages/ExchangeOnlineManagement/3.5.1

Could you please help us determine if there is a problem with this specific latest version?

https://learn.microsoft.com/en-us/answers/questions/1840897/connect-exchangeonline-in-azure-automation-account

**Comment by Sagarthore11** [comment]
Hello Experts,

Could you pls help us on it?

Thanks

**Comment by Sagarthore11** [comment]
Hello Team,

Any help would be greatly appreciated.

**Comment by Sagarthore11** [comment]
Hello Team, Any help on it pls ?

**Comment by Sagarthore11** [comment]
Hello Everyone,

Could you pls help us on it

**Comment by andystaples** [comment]
Hi @Sagarthore11 
A few questions
Is ExchangeOnlineManagement the only external module dependency for your function app or are there others? 
Does the issue reproduce with only ExchangeOnlineManagement installed? 
Can you provide some repro app (your own or a minimal) that demonstrates this behavior?

**Comment by Sagarthore11** [comment]
Thank you so much @andystaples for your response 

![image](https://github.com/user-attachments/assets/90cf8e63-197e-4182-820d-017c259e3cdf)

**Comment by Sagarthore11** [comment]
Thank you so much for your help, @andystaples. I was unable to reproduce the issue again after switching to PowerShell 7.4
