### ISSUE TITLE
Az.Storage 7.2.0+ not compatible with existing extension bundles

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-powershell-worker#1089]
The current extension bundles have storage assemblies that are no longer compatible with Az.Storage 7.2.0. Utilizing Az.Storage 7.2.0 results in several MethodNotFound exceptions like:
```
Method not found: 'Azure.Response`1<Azure.Storage.Blobs.Models.BlobContainerProperties> Azure.Storage.Blobs.BlobContainerClient.GetProperties(Azure.Storage.Blobs.Models.BlobRequestConditions, System.Threading.CancellationToken)'
```

## Workaround
Pin to Az.Storage 6.x modules

**Comment by andystaples** [comment]
I was not able to reproduce the issue today with bundles set to
```
    "version": "[4.*, 5.0.0)"
```
Likely subsequent Bundles updates have updated their dependencies and resolved the conflict. If you are still experiencing the issue, please provide the contents of host.json, requirements.psd1, and run.ps1 from the app for repro
