### ISSUE TITLE
Adding 'Convert-OutputBindingValue' broke the blob out binding scenario

### ISSUE THREAD

**Issue by daxian-dbw** [Azure/azure-functions-powershell-worker#136]
PR #113 added `Convert-OutputBindingValue` to make necessary transformation to the output value (e.g. `Hashtable` to `HttpResponseContext` implicit conversion). However, this broke the output binding for `blob` type.

Before making this change, `Push-OutputBinding` directly saves `$Value` to the `Hashtable` and thus preserves the true type of `$Value`.
After this change, `$Value` will be passed through `Convert-OutputBindingValue` before being saved. The value returned by `Convert-OutputBindingValue` will be unrolled by the pipeline, and thus the original type of `$Value` is lost. For example, if `$Value` is a byte array `byte[]`, after calling `Convert-OutputBindingValue`, an object array will be returned instead, which will cause incorrect data being sent out for the blob output.

`Write-Output -NoEnumerate` also unroll the value, even though `-NoEnumerate` is specified 🤕 It returns a `PSObject` array for a given byte array value.
Given this unpleasant behavior of `Pipeline`, we have to move the data transformation back to C# code in worker.

**Comment by TylerLeonhardt** [comment]
I feel like there might actually be an issue opened somewhere...

**Comment by TylerLeonhardt** [comment]
Aha! https://github.com/PowerShell/PowerShell/issues/5122
