### ISSUE TITLE
Using Format-* on an object that's sent to Push-OutputBinding sends the FormatRecord instead of the formatted object

### ISSUE THREAD

**Issue by SteveL-MSFT** [Azure/azure-functions-powershell-worker#144]
Repro:

1. Create HTTP trigger function
2. In run.ps1, have: `$body = Get-Process | Select-Object -First 1 | Format-List *`

Currently, without adding formatting to the pipeline, `$body` contains the default formatting which is likely a subset of the properties (like for Get-AzVM).  Expectation is that there should be some way to get all the properties to return.  The example above serializes the FormatRecords instead of the formatted object.

**Comment by TylerLeonhardt** [comment]
Simpler repro:

```
Get-Process | Select-Object -First 1 | Format-Table | ConvertTo-Json
```

We take `$body` and throw it through `ConvertTo-Json` if it's a type we don't recognize... which gives this same result. We probably want to handle these types correctly in the worker:

The types in `Format-*`:
```
02-01 20:30:16 ~→ (Get-Process | Select-Object -First 1 | Format-List) | % {$_.GetType()}

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
False    False    FormatStartData                          Microsoft.PowerShell.Commands.Internal.Format.StartData
False    False    GroupStartData                           Microsoft.PowerShell.Commands.Internal.Format.StartData
False    False    FormatEntryData                          Microsoft.PowerShell.Commands.Internal.Format.PacketInfoData
False    False    GroupEndData                             Microsoft.PowerShell.Commands.Internal.Format.ControlInfoData
False    False    FormatEndData                            Microsoft.PowerShell.Commands.Internal.Format.ControlInfoData

02-01 20:30:25 ~→ (Get-Process | Select-Object -First 1 | Format-Table) | % {$_.GetType()}

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
False    False    FormatStartData                          Microsoft.PowerShell.Commands.Internal.Format.StartData
False    False    GroupStartData                           Microsoft.PowerShell.Commands.Internal.Format.StartData
False    False    FormatEntryData                          Microsoft.PowerShell.Commands.Internal.Format.PacketInfoData
False    False    GroupEndData                             Microsoft.PowerShell.Commands.Internal.Format.ControlInfoData
False    False    FormatEndData                            Microsoft.PowerShell.Commands.Internal.Format.ControlInfoData

```

**Comment by daxian-dbw** [comment]
Users can simply append `Out-String` to the pipeline: `$body = Get-Process | Select-Object -First 1 | Format-List * | Out-String`.
I don't think the worker should do anything special here, given that all those formatting types are internal.

**Comment by TylerLeonhardt** [comment]
Yeah that's fair. Maybe wait for feedback to see if users fall into this situation often?

**Comment by daxian-dbw** [comment]
Sure. I personal think that it would be extremely rare for users to capture the format data objects as the output binding value.
If they want to inspect the properties, remember that they can leave the results from `Format-List` to the output stream, which will then be rendered through `Out-String` automatically and show up in the information log.

**Comment by anirudhgarg** [comment]
Closing this.
