### ISSUE TITLE
Clean up Jobs after Function invocation

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-functions-powershell-worker#146]
We should stop all PowerShell Jobs after invocation for cleanup purposes.

**Comment by daxian-dbw** [comment]
This is the best we can do. But if a new process is spun up via .NET API, then we won't be able to clean it when cleaning up the Runspace, because it could be spun up from a different Runspace by another running function, and there is no way to know for sure.

**Comment by daxian-dbw** [comment]
Close via #171
