### ISSUE TITLE
Attaching storage through Portal fails

### ISSUE THREAD

**Issue by benjaminhowarth1** [Azure/azure-functions-powershell-worker#151]
Chrome gives this error when trying to attach file storage to a function app:

[WebsitesExtension]  20:02:15 Websites.BaseFrameBlade Websites.BaseFrameBlade: EventMessage message type not supported: RECEIVED_BYOS_SELECTIONS

My use case is trying to load some standalone binaries into the function to execute (think command-line utilities). Has anybody got good documentation/experience of this?

**Comment by TylerLeonhardt** [comment]
Hmm this seems like an issue with the Functions portal experience than the PowerShell worker...

@pragnagopa and pointers here?

**Comment by pragnagopa** [comment]
@benjaminhowarth1 - Can you give us exact repro steps?

**Comment by anirudhgarg** [comment]
Closing this issue as we havent heard back from the customer.
