### ISSUE TITLE
LogStream not working after re publishing

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-functions-powershell-worker#159]
Observation:

I'm working on a function which I publish using `func azure functionapp publish <name>`.

I'm sending in small changes as I'm trying to debug some things and every time I publish my function again, the logstream does not work anymore (just, No new trace in the past x min(s)). I connect to the logstream using `func azure functionapp logstream <name>`

When I call the function it still responds and gives me a resultcode of 200. I need to stop the azure app and start it again to connect with logstream again to see any output.

Ask, is this a known issue? I couldn't find any issues related to this. Is there a simpler way to have the worker restart without stopping the entire app? (can I signal the worker after publication to reinitialize or something?)

Using consumption plan

**Comment by TylerLeonhardt** [comment]
Thanks for this @bgelens! This would be a greater Azure Functions issue.

@SteveL-MSFT has already opened an issue on them for this. Please give your feedback here:
https://github.com/Azure/Azure-Functions/issues/1143

**Comment by bgelens** [comment]
Thanks for the info @TylerLeonhardt!
