### ISSUE TITLE
`profile.ps1` not generated when creating from the Portal

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-powershell-worker#175]
When creating a 2.0 PowerShell function app using `func`, a `profile.ps1` gets created that's pre-populated with MSI authentication and some comments about using `Enable-AzureRmAlias`.

When creating a 2.0 PowerShell function app in the Portal using the feature flag, this `profile.ps1` does not get created. This creates issues where a user would incorrectly assume after enabling MSI support that they would be authenticated using MSI.

**Comment by eamonoreilly** [comment]
This is now created by the host in the service if the language worker is PowerShell.
