### ISSUE TITLE
Az modules not there when starting with core-tools

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-functions-powershell-worker#177]
I had to ```Save-Module -Path ~\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\powershell\Modules\ -Name Az``` before I could start with local development where interaction with Azure was needed. Maybe add to the docs or have additional install routine?

**Comment by TylerLeonhardt** [comment]
This is currently being addressed by @Francisco-Gamino.

Francisco, would you like to explain the plan? 😊

**Comment by daxian-dbw** [comment]
@bgelens Just in case you don't know, you can also create a `Modules` folder in the root directory of your Function App, and save the `Az` module there. PS worker automatically adds that folder to the module path.
But I understand have `Az` module in a common location makes sense if you have multiple Function Apps that all depend on that module.

@Francisco-Gamino is working on a feature called `dependency management` that will help this scenario.

**Comment by bgelens** [comment]
@daxian-dbw I know (using this for my own custom modules), but don't want to publish Az module when running ``` func azure functionapp publish```  as they are already installed (on Azure worker) by default. This is also the reason I added this issue as I expect local development to behave the same as it would using editor in portal.

**Comment by daxian-dbw** [comment]
Ah, I see what you mean. But I'm afraid that will change with the newest deployment of the PS worker due to #166, you can see the change that affects this behavior [here](https://github.com/Azure/azure-functions-powershell-worker/pull/166/files#diff-343a7bfdf47ea4e8011e6b0c8f7d0167L21). Basically, there is a design change in the `dependency management` feature, and the `Az` module will be deployed automatically only if you enable the `dependency management` feature. The PR description in #166 explains it more, and @Francisco-Gamino can chime in to provide more details.

**Comment by Francisco-Gamino** [comment]
Hello @bgelens, we just introduced a feature called Managed Dependencies in which the user specifies that you function app has a dependency in the Azure Az modules.

Here is how it works, at function app creation, using the func CLI, the user has the option to opt into Managed Dependencies for PowerShell function apps using the --managed-dependencies switch. Managed dependencies enables modules to be automatically managed by the Functions service. Currently, only the Azure Az module is supported.

If the user opts in, we add an entry to host.json and create a requirements.psd1.

User opts into managed dependencies for PowerShell
```
init --worker-runtime powershell --managed-dependencies
Writing profile.ps1
Writing requirements.psd1
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing E:\MyFunctions\MyFuncApp\.vscode\extensions.json
```
Running this command adds a managedDependency entry in host.json and generates a requirements.psd1 file.

```
# Contents of host.json
{
  "version": "2.0",
  "managedDependency": {
    "enabled": true
  }
}


# Contents of requirements.psd1

# This file enables modules to be automatically managed by the Functions service.
# Only the Azure Az module is supported in preview.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    'Az' = '1.*'
}
```
Once you start the function app is started, the latest version of the Az module is installed from the PSGallary under the ManagedDependencies folder. In you are running the app locally, this folder gets created at the function app root. If you are running in Azure, the path will be home/data/MangedDependencies.

Lastly, when the function app is published, we ignore this folder as the dependencies will be installed once your function app is started in the cloud. 

This feature is already available in the PowerShell worker. The core tools PR is should be merged this week. Please see https://github.com/Azure/azure-functions-core-tools/pull/1159 for more info.

In the meantime, if you'd like to try it, please do the following:
Please add the following entry to 
host.json
```
 "managedDependency": {
    "enabled": true
```

Create a requirements.psd1 and place at the function app root.
```
# This file enables modules to be automatically managed by the Functions service.
# Only the Azure Az module is supported in preview.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    'Az' = '1.*'
}
```

Please let me know if you have any other questions.

Thanks,
Francisco

**Comment by bgelens** [comment]
Thanks @Francisco-Gamino! I noticed the Az modules where gone today and tried to puzzle this together from your PR but your explanation here makes it all so much easier :)

**Comment by Francisco-Gamino** [comment]
Great, thanks bgelens! Feel free to reach out to me if you have issues setting this up for your function app.

**Comment by bgelens** [comment]
Hey @Francisco-Gamino! Right now you can only say, I need 1.* version of Az module. I need to fix it to 1.6.* so I'm assured nothing breaks when 1.7.0 comes out. 

Example, `Az.Storage` changed to make use of `Microsoft.Azure.Cosmos` (1.6) instead of `Microsoft.Azure.Storage` (1.x-1.5) library which I was dependent on. 

Would it be possible to have the minor fixed as well?

**Comment by TylerLeonhardt** [comment]
At the start, Managed Dependencies only allows you to lock to a Major version (1.*) but just as you suggested, locking to a Minor version is also important... that will come later, but it will addressed.

cc @anirudhgarg @eamonoreilly

**Comment by eamonoreilly** [comment]
If you need to lock to a specific version, I would recommend saving that specific module to the modules folder and not opting in to managed dependencies for the moment until we look to add these capabilities.
Thanks,
Eamon

**Comment by bgelens** [comment]
@Francisco-Gamino I've noticed that dependency management in azure core tools version 2.5.553 is trying to download the modules, placing them in a DependencyManagement folder in the Azure Function app root but this path is not appended to PSModulePath causing an indefinite loop. Not sure this is due to work in progress so I thought I would address my findings

**Comment by Francisco-Gamino** [comment]
@bgelens: Let me look into this. I will report back.

**Comment by Francisco-Gamino** [comment]
@bgelens: Thanks for reporting this issue. I have an repo. I need to do a bit more debugging as there are multiple moving pieces (CLI, PowerShell worker and Host). I will update this issue once I have more information. Thanks.

**Comment by Francisco-Gamino** [comment]
@bgelens: This issue will be resolved in the next release of the CLI. The problem was that for the local development scenario, we were downloading the function app dependencies to the functionAppRoot\ManagedDependencies. However, whenever there are file changes under the function app root folder, the Process Host gets restarted. To fix this, we will be placing the function app dependencies for the local dev scenario at LocalApplicationData\AzureFunctions\FunctionAppName\ManagedDependencies. Please see https://github.com/Azure/azure-functions-powershell-worker/pull/190 for more info.

We have updated the PowerShell package in the CLI with this fix. Please see for more info https://github.com/Azure/azure-functions-core-tools/pull/1190.

Closing this issue.

Thanks,
Francisco

**Comment by TylerLeonhardt** [comment]
@Francisco-Gamino where does this go on non-Windows?

**Comment by daxian-dbw** [comment]
It's using `Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData, Environment.SpecialFolderOption.DoNotVerify)`, which will be `~/.local/share` on Linux (or Ubuntu, more specifically).

**Comment by bgelens** [comment]
Thanks!
