### ISSUE TITLE
table input binding example

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-functions-powershell-worker#178]
I'm trying to use table storage as an intermediate data store between functions and have queue triggers in place to tell the next function which table row it should read l (and actually update using output again) like [in this example](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table#input---c-script-example---one-entity). Are there any examples / templates on how to deal with tables input binding with PowerShell? I can't seem to find any

**Comment by TylerLeonhardt** [comment]
@bgelens Can you open this in the https://github.com/Azure/azure-functions-templates/ repo and cc me and @joeyaiello?

Looks like they don't have templates for Table in _any_ language:
https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates

**Comment by bgelens** [comment]
Done! I'll close this one here. Thanks @TylerLeonhardt
