### ISSUE TITLE
Imperative binding patterns

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-functions-powershell-worker#184]
I don't know if it is possible but I would like to have a named parameter in my outputbinding like this:

```
{
  "type": "queue",
  "name": "queueoutput",
  "queueName": "{queuename}",
  "connection": "AzureWebJobsStorage",
  "direction": "out"
}
```

And have the code decide what queuename to use. Scenario is, rest call in -> route to correct queue which will trigger corresponding function.

Right now I have to add all queue's declaratively, as you can imagine, it can grow exponentially so having the ability to define the desired queue code would help a lot!

**Comment by TylerLeonhardt** [comment]
@bgelens This to me seems like a feature request that isn't specific to PowerShell but could be applied to _all_ languages. Correct me if I'm wrong!

If so, can you open this over on the [azure-functions-host repo](https://github.com/Azure/azure-functions-host)?

**Comment by TylerLeonhardt** [comment]
cc @pragnagopa @asavaritayal

**Comment by pragnagopa** [comment]
We already have support for binding expressions. Please see here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns

**Comment by bgelens** [comment]
I tried the pattern where the queuname is set as an appsetting, then overwrite using ```$env:queuename = 'someothername'```. Unfortunately, the queue name doesn't seem to be overwritable like this.

An interesting bit is that in C#, binding info can be created at [runtime](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#binding-at-runtime) which are called, imperative bindings. Could we have a similar implementation for PowerShell?

cc @TylerLeonhardt @daxian-dbw

**Comment by TylerLeonhardt** [comment]
@pragnagopa do language workers that are out of process have a mechanism for imperative bindings?

**Comment by pragnagopa** [comment]
@bgelens - As long as function.json follows the binding pattern like ` "queueName": "%input-queue-name%",` it should work. Can you please share function code and the function.json?

@TylerLeonhardt  - Language worker layer design requires function.json. As of now we do not have an equivalent of imperative bindings for out-of-proc languages

**Comment by bgelens** [comment]
@pragnagopa I have this in the function.json

```json
{
    "type": "queue",
    "name": "queueoutput",
    "queueName": "%queuename%",
    "connection": "AzureWebJobsStorage",
    "direction": "out"
}
```

I have a queueName defined in the application settings.

{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "powershell",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "queuename": "queue1"
  }
}

This works fine but now I want to have the code at the PowerShell worker to define another queuename. As the application settings are exposed as environmental variables, I figured it could be done as following:

```powershell
$env:queuename = 'queue2'
```

But the message will still end up in queue1 so this doesn't seem to have effect.

**Comment by TylerLeonhardt** [comment]
@bgelens that's because the Azure Functions Host and the Azure Functions PowerShell worker are 2 separate processes.

The [Azure Functions Host](https://github.com/Azure/azure-functions-host) is responsible for sending the data from the worker to the queue. If you mutate the `queuename` environment variable in the worker, this doesn't get applied to the Functions Host process since changing environment variables only affects the process you're in.

That's why it doesn't work, but I think we should have some mechanism for these imperative/dynamic out bindings.

**Comment by bgelens** [comment]
Yeah I figured as much. Just responding to the inquiry of @pragnagopa. 

Would definitely be great if something would happen to make this possible!

**Comment by pragnagopa** [comment]
You will not be able to set queuename for an output binding from within the function code. But Binding expressions allow you to use result from an input binding. Following sample shows how specify queuename from an output binding from queueTrigger data

```json
{
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "queue1",
      "connection": "AzureWebJobsStorage"
    },
    {
      "type": "queue",
      "name": "outputQueueItem",
      "queueName": "{name}",
      "connection": "AzureWebJobsStorage",
      "direction": "out"
    }
  ]
}
```
Sample queue trigger data from queue with name `queue1` 
```json
{
  "name": "queue2",
  "Id": "5"
}
```
Now, you can set value for `outputQueueItem` outputbinding which will be pushed to queue with name `queue2`

Hope this helps!

**Comment by bgelens** [comment]
Thanks! I will definitively give this a try. Would it be possible if the queue would contain a json body, to refer to a key / nested key?

**Comment by TylerLeonhardt** [comment]
I'm curious about this as well @pragnagopa but from the perspective of [this comment](https://github.com/Azure/azure-functions-host/issues/4207#issuecomment-479722629). If the host does deserialize the queue data if it's json so it can compute Binding expressions, then the worker should probably receive the json as `TypedData.Json` instead of `TypedData.string`?

**Comment by pragnagopa** [comment]
@TylerLeonhardt  - I have reopened https://github.com/Azure/azure-functions-host/issues/4207. yes, host should set typedData.json if the input data is infact json.

@bgelens -

> Would it be possible if the queue would contain a json body, to refer to a key / nested key?

yes, you can. Please see https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#dot-notation

Here is an extension to the above example:
Sample input data in `queue1`

```
{
  "input": {
    "name":"queue2",
    "Id":"3"
  }
}
```
Corresponding function.json to bind queuename to `input.name` for the outputbinding

```
{
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "queue1",
      "connection": "AzureWebJobsStorage"
    },
    {
      "type": "queue",
      "name": "outputQueueItem",
      "queueName": "{input.name}",
      "connection": "AzureWebJobsStorage",
      "direction": "out"
    }
  ]
}
```

**Comment by TylerLeonhardt** [comment]
That's awesome 😃

**Comment by bgelens** [comment]
Thanks @pragnagopa! This works perfectly!

**Comment by TylerLeonhardt** [comment]
Awesome!

We should maybe close this in favor of opening a new issue on the host to support imperative bindings for out-of-proc languages?

**Comment by bgelens** [comment]
@TylerLeonhardt Done!
