### ISSUE TITLE
Add OGFs for powershell functions

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-powershell-worker#198]
Tracking item to update OGFs for powershell functions.

cc: @anirudhgarg

**Comment by TylerLeonhardt** [comment]
What is an OGF?

**Comment by pragnagopa** [comment]
Overall Goodness Factor (OGF) - Manual E2E tests that are part of release testing. They include portal, CLI and VS. We will start tracking VSCode from now on.

**Comment by joeyaiello** [comment]
@Francisco-Gamino if this is done, please close this

**Comment by anirudhgarg** [comment]
Francisco has done it.
