### ISSUE TITLE
requirements.psd1 - Needs a note that it is only for Azure modules

### ISSUE THREAD

**Issue by dfinke** [Azure/azure-functions-powershell-worker#199]
I tried to add a module that is published on the PowerShell Gallery. That did not work.

**Comment by TylerLeonhardt** [comment]
cc @anirudhgarg, @Francisco-Gamino, @SatishRanjan

**Comment by eamonoreilly** [comment]
@TylerLeonhardt  @anirudhgarg, @Francisco-Gamino, @SatishRanjan
Thanks. This is called out on https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#manageddependency but I'll update https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#dependency-management with a note also. We might want to add a comment to the requirements.psd1 also for now.

**Comment by anirudhgarg** [comment]
Assigned to Francisco to add a comment in the requirements.psd1 in too

**Comment by AnatoliB** [comment]
This will be outdated after completing https://github.com/Azure/azure-functions-powershell-worker/issues/246.

**Comment by TylerLeonhardt** [comment]
Yes but do you see #246 addressed soon?

Given the performance concerns with #246 (wiping and downloading all the modules every time there's a new version) I would think that it's a bit far out and addressing #199 (this issue) is needed for the time being.

**Comment by AnatoliB** [comment]
We want to do https://github.com/Azure/azure-functions-powershell-worker/issues/246 for GA. No committed date at this point, but soon. I'm not against changing the doc in the meantime, just mentioning this because this change will have to be reverted.

**Comment by AnatoliB** [comment]
This PR enables non-Az modules: https://github.com/Azure/azure-functions-powershell-worker/pull/287. As soon as this is committed/deployed, the doc update will not be required.

**Comment by dfinke** [comment]
This mean that `Save-Module` does not have to be used if the module is in the PowerShell Gallery?

**Comment by AnatoliB** [comment]
@dfinke This is correct: if the Managed Dependencies feature suits your needs, you will not need to invoke `Save-Module` anymore (after this PR is committed/deployed). Just specify the module in `requirements.psd1`, and it will be installed and upgraded for you automatically by the PowerShell worker.

**Comment by Francisco-Gamino** [comment]
Managed Dependencies now supports downloading any module available on the PSGallery, so this work item is no longer needed, closing issue.
