### ISSUE TITLE
[Programming Model] Function Format

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-powershell-worker#2]
## Summary 
**TBD**  (general information about the function format)

### Input bindings

1. Trigger input 
**TBD**

2. Additional input
**TBD**

### Output bindings

1. $return type
**TBD**

2. Generic type
**TBD**

3. Multiple output values for a single binding
**TBD**

## Referencing external modules
**TBD**

## Logging
**TBD**

## Async
**TBD**

**Comment by asavaritayal** [comment]
Noticed the label. Is there a question here? :)

**Comment by asavaritayal** [comment]
Ah, got it!

By `generic type`, I meant a standard output type. You already answered that question.

For `multiple output values for a single binding`, I mean the scenario where we need to write multiple values to the same output binding. For e.g. if our function were to write 10 messages to the same queue, we shouldn't need to declare it 10 times in the `function.json` file. In C# we use a collector object for the same purpose and for python, we end up returning a tuple instead of a single value.

**Comment by tylerl0706** [comment]
> we end up returning a tuple instead of a single value

So this is a bit confusing to me because tuple or array aren't valid grpc types (AFAIK). So does the worker look for this tuple and iterates over it and sends messages with the valid grpc types (int, string, bytes, json, etc) that are contained in the tuple?

**Comment by asavaritayal** [comment]
I'm not certain about the implementation. @elprans can you please help out our PowerShell friends?
