### ISSUE TITLE
Discussion: VSCode Debug Experience Improvement

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-powershell-worker#204]
The "wait-debugger" method seems fraught with issues and slows down the write/test loop, for instance if I place one and forget to take it out, suddenly my code will "freeze" in production (assuming it misses a code review or I'm just testing).

Due to BreakAll, I understand the need for it, but perhaps when the function host is running in "vscode debug mode", an environment variable can be set to show this, so that the wait-debugger can be conditional? E.G.:

```powershell
if ($AZFUNC_IS_POSHDEBUG) {wait-debugger}
```

### Method 1: Launch Configuration modify local.settings.json
Unfortunately launch configurations still don't support postLaunchTask, otherwise my workaround for this would be:

- prelaunch task to backup local.settings.json and then modify it to add the environment variable
- postlaunch task to restore the original local.settings.json

This is not a great method because something going wrong can potentially leave the debug local.settings.json in place, but there aren't any other obvious "hooks" into the azure function host that can be defined at runtime that safely remove the item. However since local.settings.json doesn't get published or saved in git by default with the azure functions templates, it's a "safe" item to work with that won't affect a production deployment.

### Method 2: Language Worker Parameter
Could maybe a language worker parameter be added that would add the environment variable natively and add that to the task? For instance the launch task would be:
```
func host start --language-worker "-poshdebug"
```
and the powershell language worker if that parameter is specified sets the AZFUNC_IS_POSHDEBUG environment variable (or whatever). Then in my code I can add:

```powershell
if ($AZFUNC_IS_POSHDEBUG) {wait-debugger}
```

And that way my code is the same in both debug and production. I personally would place this at the top of pretty much every function so when debugging it stops at the top of the script, and since VSCode breakpoints work from then on, I'd just click continue once and get to where I really wanted to be, without having to constantly "add debugger line, save, debug,remove debugger line,save,continue"

Just some thoughts unless there's already a plan for GA. Thanks!

EDIT: The environment variable should be AZURE_FUNCTIONS_ENVIRONMENT since it already exists for this "purpose"

**Comment by bgelens** [comment]
I use this for my Http Triggered functions

```powershell
if ($Request.Query.ContainsKey('Debug') -and $env:AZURE_FUNCTIONS_ENVIRONMENT -eq 'Development') {
  if ($Request.Query['debug'] -eq 'true') {
    Write-Verbose -Message "Debug Query found, Please attach debugger to $(Get-PSHostProcessInfo -Id $pid | Out-String)" -Verbose
    Wait-Debugger
  }
}
```

By checking the environment I cannot accidentally trigger Wait-Debugger on a published function. 

This of course does not work for non http triggered functions. 

E.g. calling a timer triggered function locally:

```powershell
Invoke-RestMethod -Method Post -Uri 'http://localhost:7071/admin/functions/TimerFunc' -UseBasicParsing -ContentType 'application/json' -Body '{}'
``` 

Would be nice if I could control through query params or headers to signal I want to hit `Wait-Debugger`

**Comment by JustinGrote** [comment]
Good idea on the query parameter.

BTW it appears my functions environment starts in PRODUCTION by default with core tools, although this code change from 2018 says it should start as DEVELOPMENT
https://github.com/Azure/azure-functions-core-tools/commit/6e190f9f2a6c11e8d2d959968f41f1af5930c1c6

```
[5/2/2019 7:54:24 PM] Job host started
Hosting environment: Production
Content root path: C:\Users\JGrote\Documents\AzureDevOps\adslFunctionSandbox
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Http Functions:

        HttpTrigger: [GET,POST] http://localhost:7071/api/HttpTrigger
```

@bgelens did you do anything special or is yours development out-of-the-box?

**Comment by bgelens** [comment]
Is shows Production  when I start the host as well, but the environment variable AZURE_FUNCTIONS_ENVIRONMENT has Development.

**Comment by JustinGrote** [comment]
@bgelens OK so I'm not crazy then :).

There's another environment variable for detecting specifically the Core Tools environment, and I've started using that to detect for safety. I think I'll put in a separate issue to have the documentation updated to recommend doing this by default instead of Wait-Debugger by itself.

Should we settle on the workaround or is there plans for a more robust approach?

**Comment by daxian-dbw** [comment]
Good discussion here!
There can be a more robust approach -- allow breaking points to be set in the script before hitting `F5`, and set those break points when the debugger attaches to the target Runspace.
@TylerLeonhardt has already done some work in PowerShell to help make this approach possible, see https://github.com/PowerShell/PowerShell/pull/8923

**Comment by JustinGrote** [comment]
This actually works as of today in terms of the breakpoints, you just have
to add the wait-debugger to get there (sometimes, because of BreakAll it
often breaks earlier)

**Comment by daxian-dbw** [comment]
As of today, breakpoints set before `BreakAll` won't be hit. Only the breakpoints set after `BreakAll` can be hit.

The desired UX would be similar to the local debugging:
1. Breakpoints can be set beforehand, before pressing `F5` to start the debugger.
2. Avoid `BreakAll` and `Wait-Debugger`. The breakpoints set beforehand can be hit as long as the execution flow in the target Runspace hasn't passed the line where a breakpoint is set.

**Comment by JustinGrote** [comment]
@daxian-dbw can this PR: https://github.com/PowerShell/PowerShell/pull/8923 be used for this? Instead of using BreakAll, capture the PSBreakpoints from VSCode and pass them to Debug-Runspace when it is called by the Attach task.

**Comment by daxian-dbw** [comment]
@JustinGrote Of course, as I mentioned in https://github.com/Azure/azure-functions-powershell-worker/issues/204#issuecomment-489368383, that PR is the first step toward the desired experience.

**Comment by JustinGrote** [comment]
I would mention that once PS7 is available on the function host, this can probably be closed because $ErrorActionPreference = 'Break' will be available, assuming it works as expected, which would be an acceptable workaround.

**Comment by eamonoreilly** [comment]
Thanks Justin - @TylerLeonhardt  said he would have a look at this now that PS7 supports it better.
Eamon

**Comment by TylerLeonhardt** [comment]
Yep. A change was merged in to have a much better debugging experience in PS7. When Azure Functions moves to that this experience will be improved greatly.

**Comment by JustinGrote** [comment]
Breakpoints now work in 2022.4.1-preview FINALLY! Thanks to @seeminglyscience for the work on this. Closing this issue unless I come across a significant enough regression.

https://github.com/PowerShell/vscode-powershell/releases/tag/untagged-0b17b3c1ec11c7dda14a
