### ISSUE TITLE
Request.RawBody is not a string anymore

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-functions-powershell-worker#205]
Locally $Request.RawBody is still a json string. Since today, in my published function this has changed to a hashtable. I have no clue why.

**Comment by daxian-dbw** [comment]
Thanks for reporting this.
This is a regression caused by #186, which was supposed to be a temporary workaround for https://github.com/Azure/azure-functions-host/issues/4207.
Now that the issue has been reopened and we agreed the fix should be in the host, I will revert #186.
