### ISSUE TITLE
[HttpResponseContext] Content-Type should be set to 'application/json' when an object is provided to Body

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-powershell-worker#207]
When the HttpResponseContext autodetects the type and does a type conversion, if it converts to JSON then it should automatically mark the content as application/json and not text/plain

```powershell
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{Body=(get-childitem)})
```
![image](https://user-images.githubusercontent.com/15258962/57169757-8b9bc980-6dbd-11e9-9623-6b7a513ea511.png)

### Workaround
Explicitly specify the content type.
```powershell
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{Body=(get-childitem);ContentType='application/json'})
```
![image](https://user-images.githubusercontent.com/15258962/57169833-08c73e80-6dbe-11e9-9594-02267017b990.png)

**Comment by anirudhgarg** [comment]
Thanks for reporting. We will fix this.

**Comment by AnatoliB** [comment]
Fixed.
