### ISSUE TITLE
$TriggerMetadata should include Client IP

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-powershell-worker#213]
In 1.x I got this from the $REQ_HEADER_CLIENT_IP variable. In 2.x that's not visible as a variable nor is TriggerMetadata available (I checked all properties including headers):

![image](https://user-images.githubusercontent.com/15258962/57394099-9629da80-7192-11e9-8675-772f1b79765a.png)

As an aside, why do $request and Request properties both exist in TriggerMetadata? Is $triggermetadata.'$request' a bug? Seems unnecessarily redundant.

**Comment by joeyaiello** [comment]
This object is coming from the Functions host, so we'll work with them to see if we can get this info. 

We'll look into the `$request` vs. `Request` problem as well.

**Comment by anirudhgarg** [comment]
@SatishRanjan follow up with @fabiocav

**Comment by JustinGrote** [comment]
FYI I found that the "client-ip" is available within the Request object itself when running in production as the 'x-forwarded-for' attribute (doesn't seem to show up on the core tools for some reason at least on my machine). Client-IP is a 10 address that is either the function host itself or an intermediate load balancer, so it's not useful.

```powershell
param (
    $Request,
    $TriggerMetadata
)
"Req CIP: " + $request.headers.'client-ip'
"Req FW: " + $request.headers.'x-forwarded-for'
"TM CIP: " + $triggermetadata.request.headers.'client-ip'
"TM FW: " + $triggermetadata.request.headers.'x-forwarded-for'
"`$req TM CIP: " + $triggermetadata.'$request'.headers.'client-ip'
"`$req TM FW: " + $triggermetadata.'$request'.headers.'x-forwarded-for'
```

Result:
```
2019-06-13T15:09:32.554 [Information] OUTPUT: Req CIP: 10.0.128.34:41582
2019-06-13T15:09:32.555 [Information] OUTPUT: Req FW: <my ip address>:5031
2019-06-13T15:09:32.555 [Information] OUTPUT: TM CIP: 10.0.128.34:41582
2019-06-13T15:09:32.561 [Information] OUTPUT: TM FW: <my ip address>:5031
2019-06-13T15:09:32.561 [Information] OUTPUT: $req TM CIP: 10.0.128.34:41582
2019-06-13T15:09:32.561 [Information] OUTPUT: $req TM FW: <my ip address>:5031
```

So I think this can be closed if some clarification is added to the documentation.

**Comment by anirudhgarg** [comment]
Closing this as this is present in the Request Object
