### ISSUE TITLE
Default, out-of-the-box functions don't seem to work in the azure portal.

### ISSUE THREAD

**Issue by mgeorgebrown89** [Azure/azure-functions-powershell-worker#217]
A brand new function app, a new function, returns a 404 error? This seems very odd. I don't have anything else to include, that's pretty much it. The logs don't always return information either.

**Comment by JustinGrote** [comment]
Michael,

Can you step through your process for creating it? Did you use the web
portal, vscode, az cli, etc? And then how did you get the URL for it to
make sure you were accessing the right thing?

**Comment by mgeorgebrown89** [comment]
In this particular case, I did everything in the portal. New Function App. New Function with just the default everything. HttpTrigger. I click run and get a 404 error.

**Comment by JustinGrote** [comment]
Can't reproduce. Created a new one with these settings:
![image](https://user-images.githubusercontent.com/15258962/57479702-e10b2700-7252-11e9-9995-e10616d2f283.png)

Made a new function:
![image](https://user-images.githubusercontent.com/15258962/57479873-4d862600-7253-11e9-88ca-c1b35cdfef80.png)

Copied the function URL:
![image](https://user-images.githubusercontent.com/15258962/57479983-727a9900-7253-11e9-92fb-36da59f6e2e0.png)

worked fine in browser:
![image](https://user-images.githubusercontent.com/15258962/57480289-254af700-7254-11e9-9882-f22af2f6fb0e.png)

Added &name=testrun to the end of the URL
![image](https://user-images.githubusercontent.com/15258962/57480321-3b58b780-7254-11e9-989f-03bea241545f.png)

Try again maybe? :)

**Comment by mgeorgebrown89** [comment]
Yeah, I'm not sure what was happening yesterday, but this doesn't seem to be a problem anymore.
