### ISSUE TITLE
FunctionApp root Modules folder doesn't work when the FunctionApp is running as package

### ISSUE THREAD

**Issue by mgeorgebrown89** [Azure/azure-functions-powershell-worker#219]
I can't seem to track down a pattern, but sometimes this works, and sometimes it doesn't. 

As far as I understand, you're supposed to be able to put modules into a root-level folder called Modules and have it be accessible at runtime. I have both explicitly called this with using module ModuleName and without it, and it seems that sometimes it works, and other times it does not. Do I need to explicitly add this to PSModulePath?

**Comment by mgeorgebrown89** [comment]
And now I just switch it from read only to read/write, and my function started working correctly and was able to find the modules... am I just not waiting long enough?

**Comment by mgeorgebrown89** [comment]
aha. I figured it out (maybe). It seems that you can't run from package if you want to use the modules. You have to run from zip.

**Comment by daxian-dbw** [comment]
@mgeorgebrown89 I'm glad you figured it out (maybe 😄) But can you please share what didn't work and what worked (repro steps)?

**Comment by mgeorgebrown89** [comment]
I had an Azure Pipeline from my Azure Repo which contained my Function App. The pipeline builds the code and deploys it to a Function App (created originally via the portal). I had selected "auto-detect" for the Deployment Method section under Additional Deployment Options part of the Pipeline. This set it up to run from Package, which I've heard is better, but then when I tried to execute my function, the error messages indicated that it couldn't find the module functions that I was using. I edited the App's configuration to change the App Setting 'WEBSITE_RUN_FROM_PACKAGE' from 1 to 0, which I believe means it runs as a ZIP. 
After I did that my Function worked as expected.
I verified and redeployed the Function via my pipeline specifying ZIP deploy and my Function still functions.

**Comment by TylerLeonhardt** [comment]
Interesting... @pragnagopa do you have any context here? How are running as Package vs running as Zip different?

**Comment by daxian-dbw** [comment]
It looks to me running as package means the zip file is not extracted, and thus the module folder under the function app root doesn't exist.
It basically means PowerShell function cannot work as "running as package". @pragnagopa Can you please explain how things work when the zip file is not extracted?

**Comment by pragnagopa** [comment]
Here are details on how run from package works: https://github.com/Azure/app-service-announcements/issues/84

When using run from package, all the files needed should be deployed as part of the zip file eigher under `d:\home\data\SitePackages` or should be part of the blob storage. 

@SatishRanjan / @Francisco-Gamino  - This is a valid scenario. Can you please investigate what needs to be done to use dependeny modules feature with run from package enabled?

**Comment by daxian-dbw** [comment]
Quoted from Azure/app-service-announcements#84
> with Run From Package, things are very different. There is no longer a deployment step which copies the individual files to wwwroot. Instead, you just point it to a zip file, and *the zip gets mounted on wwwroot as a read-only file system.*

If it's mounted to `wwwroot`, the FunctionApp root module folder should continue to work ... Need to investigate why it doesn't.

**Comment by mgeorgebrown89** [comment]
One thing to note:

My module is in the root level Module folder, with a psm1 and psd1 inside another folder all with the same name, with Public and Private folders that contain the actual module functions as individual ps1 script files (which I believe is the current best-practice). Could the psm1 file grabbing the files from the folders be the issue? I suppose I could test just having everything in the psm1 file itself, rather than grabbing the functions from subfolders, and see if it runs from package...

**Comment by daxian-dbw** [comment]
> Could the psm1 file grabbing the files from the folders be the issue?

I don't think so. If your FunctionApp works locally (with `func start`), then it should work in Azure regardless of the deployment method.

**Comment by mgeorgebrown89** [comment]
Well, it works locally, but that’s because I’m explicitly importing those
modules. From what I understand and my experience , the Modules folder is
available at runtime from within Azure and doesn’t require importing, but
locally it doesn’t work the same way.

**Comment by Francisco-Gamino** [comment]
@mgeorgebrown89 :  I took a look, and run from zip work as expected for a PowerShell function app. First, I created a PowerShell function app locally using the Core Tools.

Here is my function and folder structure:
```
E:\MyFunctions\RunFromPackageFunction\.vscode
E:\MyFunctions\RunFromPackageFunction\.vscode\extensions.json
E:\MyFunctions\RunFromPackageFunction\Modules\MyProcess\MyProcess.psd1
E:\MyFunctions\RunFromPackageFunction\Modules\MyProcess\MyProcess.psm1
E:\MyFunctions\RunFromPackageFunction\MyHttpTrigger\function.json
E:\MyFunctions\RunFromPackageFunction\MyHttpTrigger\run.ps1
E:\MyFunctions\RunFromPackageFunction\.gitignore
E:\MyFunctions\RunFromPackageFunction\host.json
E:\MyFunctions\RunFromPackageFunction\local.settings.json
E:\MyFunctions\RunFromPackageFunction\profile.ps1
E:\MyFunctions\RunFromPackageFunction\requirements.psd1
```
As you can see, I have a custom module name MyProcess which contains two files MyProcess.psm1 and MyProcess.psd1. 

In MyProcess.psm1, I have a function named Get-MyProcess, which is just a wrapper for Get-Process
```
 function Get-MyProcess
{
    param
    (
        [ValidateNotNullOrEmpty()]
        [String]
        $Name
    )
    
    Get-Process $Name
}

```

Now, here is my function code where the custom module is imported.
```
using namespace System.Net

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

# Write to the Azure Functions log stream.
Write-Host "PowerShell HTTP trigger function processed a request."

# Interact with query parameters or the body of the request.
$name = $Request.Query.Name
if (-not $name) {
    $name = $Request.Body.Name
}

write-host "Process name: $name"

# Import helper module 
Import-Module MyProcess -Force -ea stop

if ($name)
{
    $processes = @(Get-Process -Name $name | Select-Object -Property Name, Id)
    $status = [HttpStatusCode]::OK

    $body = "Total process with name $name running $($processes.count)"

    $result = ""
    foreach ($p in $processes)
    {
        $result += "`r`nName: $($p.name) Id: $($p.Id)" 
    }
    $body += $result
}
else {
    $status = [HttpStatusCode]::BadRequest
    $availableModules = Get-Module -list | % {$_.Name + "`r`n"}
    $body = "Module not loaded. Exception: $exception. `r`nAvailable modules:" + $availableModules
}

# Associate values to output bindings by calling 'Push-OutputBinding'.
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = $status
    Body = $body
})
```

Next, I verified that my function worked locally.

```
PS E:\MyFunctions\RunFromPackageFunction> irm http://localhost:7071/api/MyHttpTrigger?name=pwsh
Total process with name pwsh running 3
Name: pwsh Id: 278812
Name: pwsh Id: 706784
Name: pwsh Id: 838844
```

After that, I created a PowerShell function app in the Portal. Here are the steps to set your app to run from package:
* From Kudu, create a d:\home\data\SitePackages folder, and drop your zip file in there (e.g. RunFromPackageFunction.zip)
* In the same folder, create a file named packagename.txt, containing the name of your zip file. e.g. it should contain RunFromPackageFunction.zip and nothing else (important: make sure you have no trailing spaces or newlines after the file name!)
* In your Azure App Settings, set WEBSITE_RUN_FROM_PACKAGE to 1 

Here is an issue that I ran into:
* When zipping the folder, make sure that all the function app files are at the root. Otherwise, the function will not work. Here is what your zip folder should look like:
```
E:\(ZipFolderName)\.vscode
E:\(ZipFolderName)\.vscode\extensions.json
E:\(ZipFolderName)\Modules\MyProcess\MyProcess.psd1
E:\(ZipFolderName)\Modules\MyProcess\MyProcess.psm1
E:\(ZipFolderName)\MyHttpTrigger\function.json
E:\(ZipFolderName)\MyHttpTrigger\run.ps1
E:\(ZipFolderName)\.gitignore
E:\(ZipFolderName)\host.json
E:\(ZipFolderName)\local.settings.json
E:\(ZipFolderName)\profile.ps1
E:\(ZipFolderName)\requirements.psd1
```

After that, start/restart your function app. It should look like this:
![image](https://user-images.githubusercontent.com/12720858/58657022-47bfb580-82d2-11e9-9e99-0f63b4e423f6.png)

Lastly, get the URL link to invoke your function

![image](https://user-images.githubusercontent.com/12720858/58656864-e992d280-82d1-11e9-8a75-30f90568ca2c.png)

Please let me know if you run into any issues.

Thanks,
Francisco

**Comment by Francisco-Gamino** [comment]
@mgeorgebrown89 : Closing issue. Please reopen if you have any further questions.

CC: @pragnagopa @daxian-dbw @tylercmsft @anirudhgarg
