### ISSUE TITLE
How to test a PS cosmosDB Trigger on my local box?

### ISSUE THREAD

**Issue by dfinke** [Azure/azure-functions-powershell-worker#223]
Is it done through the `host.json` file? Don't know the syntax.

# cosomsDB Trigger fails
![image](https://user-images.githubusercontent.com/67258/57796237-de5a7700-7715-11e9-92fb-4fed6e671d59.png)

# Took a Guess

`func extensions install -p Microsoft.Azure.WebJobs.Extensions.CosmosDB`
`func extensions install --package Microsoft.Azure.WebJobs.Extensions.CosmosDB --version 3.0.0-beta6`

![image](https://user-images.githubusercontent.com/67258/57796254-efa38380-7715-11e9-8b96-cff92413e227.png)

**Comment by dfinke** [comment]
# Removed 

```json
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
```
`func extensions install --package Microsoft.Azure.WebJobs.Extensions.CosmosDB --version 3.0.0`

```json
{
  "bindings": [
    {
      "type": "cosmosDBTrigger",
      "name": "Documents",
      "direction": "in",
      "leaseCollectionName": "leases",
      "connectionStringSetting": "dcfaccountname_DOCUMENTDB",
      "databaseName": "myDB",
      "collectionName": "myCollection",
      "createLeaseCollectionIfNotExists": "true"
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/67258/57797213-eca99280-7717-11e9-99d4-daa7c7db6ec8.png)

**Comment by daxian-dbw** [comment]
I doubt if it’s possible to run CosmosDB trigger locally for any languages. @pragnagopa any ideas?

**Comment by pragnagopa** [comment]
There is  a CosmosDB emulator: https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator. I haven't tried this myself but here is some useful info:
http://www.tobiaswright.com/2017/10/19/Getting-Locally-run-Azure-Functions-going-with-Azure-
CosmosDB-Emulator/
