### ISSUE TITLE
Testing locally, Invoke-RestMethod - ERROR: Response status code does not indicate success: 401 (Unauthorized).

### ISSUE THREAD

**Issue by dfinke** [Azure/azure-functions-powershell-worker#226]
```powershell
$result = Invoke-RestMethod -Headers (Get-PATHeader) $targetGithubRepo
```

This works in a PS console. If I publish the Az Function, it works. If I try to test it locally, it fails.

![image](https://user-images.githubusercontent.com/67258/57972570-810b3380-796a-11e9-91ef-31b80dd65a87.png)

**Comment by TylerLeonhardt** [comment]
@dfinke we're going to need a bit more information.

Are you interacting with GitHub's API?

My guess is that there might be an environment variable you're using in Azure but not locally. Did you mess with your Application Settings at all?

Does the function use Azure PowerShell at all?

**Comment by dfinke** [comment]
I set `GithubPAT` in both the `local.settings.json` and the app settings on Azure.
Only using `Invoke-RestMethod` for the git api.
Not using Azure PS, and the managedDependency is not enabled.

Are there other logs I can look at?

**Comment by TylerLeonhardt** [comment]
@dfinke can you paste the full `func start` console log? 

You could also verify that the environment variable is being set by Write-Host'ing it in your Function to make sure it's set correctly.

@pragnagopa it sounds like his environment variables are not being set even though they're added to the `local.settings.json`. Any log locations he could upload here?

**Comment by dfinke** [comment]
The downside of being consistent. I was doing a `Write-Host` on that env var, assumed the value being outputted was correct. I have a `$env:GithubPAT` in my `$PROFILE`, that took precedence.

**Comment by TylerLeonhardt** [comment]
Ahh. That's because any environment variables defined in the `local.settings.json` will only be applied if the environment variable is not already set.
