### ISSUE TITLE
PowerShell worker: Honor console output messages from profile.ps1

### ISSUE THREAD

**Issue by aws-scripting-guy** [Azure/azure-functions-powershell-worker#227]
**Issue description**
When running ```func host start``` _INFORMATION_ messages are being emitted only for run.ps1.

Example from the run.ps1 script:
Write-Host "PowerShell HTTP trigger function processed a request."

Worker log:
_[5/19/2019 1:41:53 PM] INFORMATION: PowerShell HTTP trigger function processed a request._

**Expected behavior:**
Console-output messages would be honored also from profile.ps1 and they would be visible in worker log.

**Current behavior:**
Console-output messages from profile.ps1 are ignored by worker.

**Comment by aws-scripting-guy** [comment]
Did find the solution here.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json

In **host.json** I would add section
 ```
 "logging": {
    "logLevel": {
        "default": "Debug"
    }
}
```
This way I can see ```write-debug```, ```write-host``` messages from my **profile.ps1** in the log of the powershell worker.

**Comment by TylerLeonhardt** [comment]
@aws-scripting-guy this is also mentioned here:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#logging

See the "important" call out.

**Comment by TylerLeonhardt** [comment]
@aws-scripting-guy trying Azure Functions 🤔 hope the experience helps change your name to azure-scripting-guy 😊

**Comment by aws-scripting-guy** [comment]
:) Thank you. Once Azure is on par with AWS - portal/quality of SDKs/reliable execution - I will consider!
