### ISSUE TITLE
Updated Azure SDKs?

### ISSUE THREAD

**Issue by burkasaurusrex** [Azure/azure-functions-powershell-worker#229]
In v1 functions, I had no problem calling into the `Microsoft.ServiceBus.Messaging` namespace without loading any DLLs. I just tried to call into the `Microsoft.Azure.ServiceBus` namespace in a Powershell script and received the following error:

```
[Error] ERROR: Unable to find type [Microsoft.Azure.ServiceBus.Message].
Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: ERROR: Unable to find type [Microsoft.Azure.ServiceBus.Message].
Exception: Unable to find type [Microsoft.Azure.ServiceBus.Message].
Stack:    at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
   at System.Management.Automation.Interpreter.FuncCallInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

So I went looking for the update Azure SDK on the environment drive and couldn't find the newer SDKs. It seems like the older SDKs are there though:

```
D:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Services\Microsoft.ServiceBus.dll
```

Just wanted to make sure I wasn't missing something here? I can download the NuGet package and load the the assembly manually if it's not supported.

**Comment by anirudhgarg** [comment]
Yes you have to get the Nuget package and load the assembly yourself. In V1 they were available out of the box. Please make sure to use the .Net Core version.
