### ISSUE TITLE
Test needed for function app dependencies installation logic

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-powershell-worker#231]
We need to add tests mocking Save-Module and file system operations.

**Comment by Francisco-Gamino** [comment]
For file system operations take a look at https://github.com/System-IO-Abstractions/System.IO.Abstractions

**Comment by Francisco-Gamino** [comment]
Unit test has been added for Managed Dependencies for the Save-Module code path.

**Comment by AnatoliB** [comment]
Addressed by https://github.com/Azure/azure-functions-powershell-worker/pull/267
