### ISSUE TITLE
Grpc.Core.RpcException

### ISSUE THREAD

**Issue by dfinke** [Azure/azure-functions-powershell-worker#234]
Works with smaller files, is there a way to up the message size on gRPC?

```powershell
irm -Method Post http://localhost:7071/api/FileUploadHttpTrigger -InFile .\largeFile.html  -ContentType  'multipart/form-data'
```

```
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=ResourceExhausted, Detail="Received message larger than max (2
0077534 vs. 4194304)")
```

**Comment by TylerLeonhardt** [comment]
@pragnagopa any ideas?

**Comment by dfinke** [comment]
Going to pivot to using a blob trigger. Much faster and looks like the way to architect these approaches.

Lots more to implement, more moving pieces, and might need to provide the user a SAS token with a TTL so they can upload files.

**Comment by jrudley** [comment]
Interesting enough, you can reproduce this using a blobtrigger as well.
