### ISSUE TITLE
Local debugging with VSCode does not work reliably when PSWorkerInProcConcurrencyUpperBound is greater than 1

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#240]
This is a known issue, we understand the root cause. Fixing this will require some effort, but the use case is also not very common, so consider just documenting this limitation for now.

**Comment by TylerLeonhardt** [comment]
Yeah this would be very tough to debug... But I think the root cause here is that PowerShell doesn't offer an ability to debug multiple runspaces at the same time. If that were a thing, the PowerShell extension for VSCode could take advantage of it.

**Comment by eamonoreilly** [comment]
Added note to https://docs.microsoft.com/en-us/azure/azure-functions/functions-debug-powershell-local#debug-in-visual-studio-code about setting this value to 1 when debugging locally in VSCode.
