### ISSUE TITLE
For blob input binding, blob content is assumed to be in the UTF8 encoding

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#243]
For blob input binding, blob content is assumed to be strictly in UTF8. No other encoding is allowed:
https://github.com/Azure/azure-functions-powershell-worker/blob/46bacf7b7203f0ce6a768126d61102ac5578a144/src/Utility/Utils.cs#L161
See also: https://github.com/Azure/azure-functions-powershell-worker/issues/132

Consider either giving the user an opportunity to specify a different encoding (binding settings?), or at least documenting this limitation.

**Comment by Francisco-Gamino** [comment]
We will look into this if there is any customer reported issues. Closing for now.
