### ISSUE TITLE
Enable specifying non-Az modules from PowerShell Gallery in requirements.psd1

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#246]

**Comment by TylerLeonhardt** [comment]
Keep in mind the performance concerns here with the current ManagedDependencies implementation.

- querying the Gallery
- wiping if there are any updates
- Save-Module on all the dependencies

This takes a long time... Even just the querying part adds seconds to any cold start.

What scares me is that with ManagedDependencies in-proc with the worker in its current model, that the performance of the feature (partially Gallery/PSGet's fault) will negatively impact the amount of time the user's function will be allowed to run.

**Comment by TylerLeonhardt** [comment]
One of the things I've been suggesting is considering a scenario where the ManagedDependencies lived as a separate service outside of the worker. This would keep the worker fast, and also deal with "multiple works upgrading deps at the same time" like #252

**Comment by AnatoliB** [comment]
Thank you, @TylerLeonhardt.

I expect the auto-upgrade performance to be significantly improved by https://github.com/Azure/azure-functions-powershell-worker/issues/247 and https://github.com/Azure/azure-functions-powershell-worker/issues/248. Specifically:

- We will not be wiping all local modules just because there is a newer version on the Gallery. Instead, we will install the new versions side-by-side and purge old modules later, not blocking function invocation.
- We will perform the auto-upgrade (including querying the Gallery) in the background, not blocking the current function invocation.
- We will not guarantee that modules are upgraded _immediately_ after a newer version appears on the Gallery. So, we don't have to even query the Gallery on every start - we can do it once a day or so (configurable).

I understand the potential benefits of performing this from a separate service, though. But implementing, deploying, and maintaining this service adds complexity. We will have to take this into account when considering the benefits. Our short-term plan is easy to implement, and it will mitigate the issue significantly (hopefully, enough for GA v1). Let's keep the separate service idea in mind and return to it later if still required.
