### ISSUE TITLE
Function start is blocked during auto-upgrading managed dependencies

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#248]
If a function execution request comes while managed dependencies are being auto-upgraded (for example, because a new module version has been published on the PowerShell gallery), the function will not start until the upgrade is complete. However, the upgrade can take long time. Since the upgrade has not been explicitly initiated by the user, so the delay looks unnecessary and unexpected to the user.

Instead of making the function wait, let it run with the currently installed module versions. Completing https://github.com/Azure/azure-functions-powershell-worker/issues/247 will help.

**Comment by TylerLeonhardt** [comment]
> Instead of making the function wait, let it run with the currently installed module versions.

Small addition that might be obvious but wanted to call out... 

This assumes there is at least _some_ version already installed. We'd probably need additional logic to verify the modules are available before actually invoking a function?

**Comment by AnatoliB** [comment]
> This assumes there is at least _some_ version already installed. We'd probably need additional logic to verify the modules are available before actually invoking a function?

Yes, we'll need to make sure the initial module installation is complete, otherwise we still need to block the function start. We will also need to make sure this logic is very efficient on the positive case, as it will run on every function invocation.

**Comment by AnatoliB** [comment]
Addressed by https://github.com/Azure/azure-functions-powershell-worker/pull/267
