### ISSUE TITLE
Clarify managed dependencies auto-upgrade expectations from the user perspective

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#249]
Document the auto-upgrade behavior and guarantees from the user perspective, specifically:
- If a new module version appears on the PowerShell Gallery, when will function executions _start_ using the _new_ version?
- When exactly will function executions _stop_ using the _previous_ module version?
- When will the _old_ module version be automatically _removed_ from the storage?
- How can the user control this (e.g. app configuration, restarting the app, etc.)?

See also: https://github.com/Azure/azure-functions-powershell-worker/issues/247, https://github.com/Azure/azure-functions-powershell-worker/issues/248.

**Comment by eamonoreilly** [comment]
This is now documented on https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#dependency-management so closing issue.
