### ISSUE TITLE
[Question] Can you Invoke-RestMethod to another PS azure function in the same function app?

### ISSUE THREAD

**Issue by dfinke** [Azure/azure-functions-powershell-worker#251]
I pulled the `$TriggerMetadata.Url` and munged it to point to another ps az fn in the same function app, it hangs. Wanted to confirm it is doing an irm` into the same runspace?

**Comment by AnatoliB** [comment]
@dfinke The execution request may be routed to the same worker, and it will not be able to start until the processing of the previous request finishes (in your case, this means "never"). Increasing [PSWorkerInProcConcurrencyUpperBound](https://github.com/Azure/azure-functions-powershell-worker/blob/dev/docs/designs/PowerShell-AzF-Overall-Design.md#concurrent-invocation-of-functions) may help.

**Comment by asifma** [comment]
THAN YOU SO MUCH. THIS SOLVED THE ISSUE I HAD :)
