### ISSUE TITLE
ERROR: Access Token missing or malformed. - using Get-AzAdServicePrincipal in Function

### ISSUE THREAD

**Issue by divgo** [Azure/azure-functions-powershell-worker#254]
**Language**: Powershell
**Binding**: EventHubs
**Function Identity**: Enabled - subscription-events is the name of the FunctionApp and the associated Service Principal

I am getting an **ERROR: Access Token missing or malformed.** Error when using **Get-AzAdServicePrincipal** in a Function App. 

The pertinent code is as follows;
```
    if ($_.data.claims.appid -ne $null ) {
        Write-Host "EventCreator was a Service Principal"
        try {
            $EventCreator = (Get-AzADServicePrincipal -ApplicationId $_.data.claims.appid).DisplayName
        } catch {
            $EventCreator = $_.data.claims.appid
        }
        
        Write-Host "EventCreator: " $EventCreator
    } else {
        $EventCreator = $_.data.claims.name;
    }
```

Not sure if this is the correct place to post this issue. I suspect the issue might have to do with the default password that the Service Principal is assigned during creation.

**Comment by eamonoreilly** [comment]
I believe you are hitting this issue https://github.com/Azure/azure-powershell/issues/9502

**Comment by eamonoreilly** [comment]
This issue is resolved with the latest Az accounts module (1.5.3). Please make sure the requirements.psd1 is now using 2.* as this will get the latest module that has the fix.
Thanks,
Eamon

**Comment by divgo** [comment]
Thank you for the update @eamonoreilly 

I just updated my Requirements.psd1 file as follows;

```
@{
	Az = '2.*'
}
```

And I am testing the Azure Function now. Just need to wait 5-10 minutes for some events to flow in and show up in the monitor tab.

**Comment by divgo** [comment]
this is the error I am getting now after updating my Requirements.psd1 file;

```
Result: Failure
Exception: Fail to install function app dependencies. Restarting the app may resolve the error. Error: 'Failed to clean up module destination path 'D:\home\data\ManagedDependencies''
Stack: 
```

This was after performing a Stop\Start on the Function App. I had to CD into the directory mentioned above and run a `RMDIR /Q /S Az`, then `RMDIR /Q /S Az.Account` - then Stop\Start again. 

Now, it looks like it is working as expected;


INFORMATION: EventCreator was a Service Principal | Information
-- | --
2019-06-28 14:55:47.274 | INFORMATION: EventCreator: subscriptions-events

**Comment by eamonoreilly** [comment]
Thanks for validating. I'll have look at what might have caused the module upgrade error and see if we can address also.
Thanks,
Eamon
