### ISSUE TITLE
Http output binding FileContentResult

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-functions-powershell-worker#270]
I need to respond to a request with a application/octet-stream content type (sending a byte array of a file. I’ve found this [stackoverflow](https://stackoverflow.com/a/52706799) answer suggesting I need to use FileContentResult. AFAICT, this is not available for PowerShell.

Can this be made available?

**Comment by Francisco-Gamino** [comment]
Hi @bgelens, have you tried setting the content-type to application/octet-stream in the ```Push-OutputBinding```? If this does not work, we will look into it.

**Comment by bgelens** [comment]
Yes I tried. It doesn't work unfortunately

**Comment by AnatoliB** [comment]
@bgelens This code seems to be achieving what you want:

``` PowerShell
$csv = 'a,b,c'

Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = [HttpStatusCode]::OK
    ContentType = 'application/octet-stream'
    Headers = @{
        'Content-Disposition' = 'attachment; filename="myfile.csv"'
    }
    Body = [System.Text.Encoding]::UTF8.GetBytes($csv)
  })
```

We may want to provide a more convenient wrapper that takes care of all these details automatically. In the meantime, please validate that this actually achieves your goal.

**Comment by bgelens** [comment]
Thanks! I got this working with a simple function! I’m going to try with a more complex one later. If I find any more issues I’ll report them here. For now I’m closing.
