### ISSUE TITLE
Error while connecting D365 CRM from Azure function Powershell

### ISSUE THREAD

**Issue by Atul-2509** [Azure/azure-functions-powershell-worker#280]
Error : Exception calling ".ctor" with "1" argument(s): "Could not load type 'System.Web.HttpRuntime' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'."

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0): 2.0
- Function App name: DSSFrameworkIntegration
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

1.	Created function app as below, with Runtime Stack as ‘PowerShell(Preview)’. This is something new preview feature introduced specially to create PowerShell Azure function.
2.	Created a function naming ‘GetFramework’ within it.
3.	Within function I have created folder ‘module’ and ‘bin’ using Kudu and uploaded all required files/dll in each respective folder.Module is imported via script.
4.	I am using module ‘Microsoft.Xrm.Data.PowerShell’ to connect CRM. It is failing while CRM connection in below line and giving above error.

$global:Connection = Connect-CrmOnline -ServerUrl $CRMPackagingUrl -Credential $CredPackaging -ForceDiscovery $true

5.	Check attached script, I am using

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by Francisco-Gamino** [comment]
Hello @Atul-2509,

The PowerShell worker uses PowerShell Core 6.2.1 (https://github.com/PowerShell/PowerShell/releases). The best way to figure out if a module is supported by PowerShell in Functions, please download the module using PowerShell 6, and try to import and run some command.

At the present time, it looks like this module is not supported in PowerShell 6. 

```
PS C:\Modules> mkdir Modules
PS C:\Modules> cd .\Modules\
PS C:\Modules> Save-Module -Name Microsoft.Xrm.Data.Powershell -Path . -Verbose
PS C:\Modules> Import-Module .\Microsoft.Xrm.Data.Powershell\
Import-Module : Could not load type 'System.Windows.DependencyObject' from assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
At line:1 char:1
+ Import-Module .\Microsoft.Xrm.Data.Powershell\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
+ FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```
In https://www.powershellgallery.com/packages/Microsoft.Xrm.Data.Powershell/2.8.0, there is a section for ```Project Site```. You can reach out to the team to see if they plan to support PowerShell 6.

![image](https://user-images.githubusercontent.com/12720858/61253808-2f3b1b80-a717-11e9-97da-40d5d292b1a3.png)

Cheers,
Francisco

**Comment by TylerLeonhardt** [comment]
Just for testing purposes, can you also download PowerShell 7 preview (same url that Francisco posted) and run through the same steps?

This will help us understand if your scenario will be fixed when Functions moves to PowerShell 7 (won't happen till after PowerShell 7 is GA but it's good data)

**Comment by Francisco-Gamino** [comment]
Hi @TylerLeonhardt,

I've downloaded PowerShell 7 preview and I was not able to import the module either. I am, however, getting a different error. 

```
PS C:\Program Files\PowerShell\7-preview> ipmo E:\Modules\Microsoft.Xrm.Data.Powershell\ -Verbose
VERBOSE: Loading module from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Data.Powershell.psd1'.
VERBOSE: Loading 'Assembly' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Crm.Sdk.Proxy.dll'.
VERBOSE: Loading 'Executable' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Crm.Sdk.Proxy.dll'.
VERBOSE: Loading 'Assembly' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'.
VERBOSE: Loading 'Executable' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'.
VERBOSE: Loading 'Assembly' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll'.
VERBOSE: Loading 'Executable' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll'.
VERBOSE: Loading 'Assembly' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Sdk.dll'.
VERBOSE: Loading 'Executable' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Sdk.dll'.
VERBOSE: Loading 'Assembly' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Tooling.Connector.dll'.
VERBOSE: Loading 'Executable' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Tooling.Connector.dll'.
VERBOSE: Loading 'Assembly' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Tooling.CrmConnectControl.dll'.
VERBOSE: Loading 'Executable' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Tooling.CrmConnectControl.dll'.
VERBOSE: Loading 'Assembly' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Tooling.CrmConnector.Powershell.dll'.
VERBOSE: Loading 'Executable' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Tooling.CrmConnector.Powershell.dll'.
VERBOSE: Loading 'Assembly' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Tooling.Ui.Styles.dll'.
VERBOSE: Loading 'Executable' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Tooling.Ui.Styles.dll'.
VERBOSE: Loading 'Assembly' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Rest.ClientRuntime.dll'.
VERBOSE: Loading 'Executable' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Rest.ClientRuntime.dll'.
VERBOSE: Loading 'Assembly' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Newtonsoft.Json.dll'.
VERBOSE: Loading 'Executable' from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Newtonsoft.Json.dll'.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Xrm.Data.Powershell.
VERBOSE: Loading module from path 'E:\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Tooling.CrmConnector.Powershell.dll'.
ipmo : Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
At line:1 char:1
+ ipmo E:\Modules\Microsoft.Xrm.Data.Powershell\ -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
+ FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```
I am not sure if this is a known issue. If it is not, I will file an new one.

**Comment by TylerLeonhardt** [comment]
> System.Management.Automation.PSSnapIn

SnapIn's predate modules. The module author should not rely on this type at all. Then, it might work in PowerShell 7

cc @SteveL-MSFT

**Comment by Francisco-Gamino** [comment]
Hello @Atul-2509,

The problem with Microsoft.Xrm.Data.PowerShell is that this module has a dependency on a PS Snap-In, which are not supported in .NetCore. Unless the module author removes this dependency, this module will never be able to run on PowerShell Core 7. 

I've opened https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/issues/372 to track this. Closing this issue.
