### ISSUE TITLE
$Host

### ISSUE THREAD

**Issue by 1ccb** [Azure/azure-functions-powershell-worker#285]
$Host.Name is currently "Default Host".  How about something more meaningful like "Azure Functions Host"?  Or perhaps allow this to be configurable from host.json.

**Comment by eamonoreilly** [comment]
Thanks for the feedback on this. Is there a specific scenario you have in mind where you would depend on this value?
Thanks,
Eamon

**Comment by 1ccb** [comment]
Yes, I have a library of PowerShell functions in a script that I include in both my Azure Functions and my regular PowerShell scripts that run on a VM.  As I migrate to Azure Functions I can exclude certain functions from this library that don't work or are obsolete in the Azure Functions environment based on the $Host that is running.

**Comment by JustinGrote** [comment]
There are a number of environment variables you can test for to determine
if you are in Azure functions or not.
https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version
https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings

FUNCTIONS_EXTENSION_VERSION
FUNCTIONS_WORKER_RUNTIME
AZURE_FUNCTIONS_ENVIRONMENT

I personally test functions_worker_runtime for powershell, and then fetch
Azure_Functions_Environment which is either Development, Staging, or
Production, so my scripts can adjust their behavior accordingly (I do way
more verbose logs in development than production, for example)


So while $host would be nice, I would think it's a lower priority to the
other more pressing issues right now IMHO.

**Comment by eamonoreilly** [comment]
Thanks guys. You can also use WEBSITE_INSTANCE_ID as described on [stackoverflow](https://stackoverflow.com/questions/45026215/how-to-check-azure-function-is-running-on-local-environment-roleenvironment-i)

I'm going to close this issue given we have a way to determine this. Thanks for opening.
Eamon
