### ISSUE TITLE
Inconsistent folder behavior in Powershell

### ISSUE THREAD

**Issue by canoas** [Azure/azure-functions-powershell-worker#301]
One of my colleagues is getting different path when using 
```
Set-Location (split-path -parent $MyInvocation.MyCommand.Definition)
```
In my case I get the folder where my function is located (run.ps1) but a newer machine is getting the Functions folder

Did some search and found these variables in the wiki https://github.com/Azure/azure-functions-host/wiki/Retrieving-information-about-the-currently-running-function

but running with the vars got me null values on local development
```
Set-Location (join-path $EXECUTION_CONTEXT_FUNCTIONDIRECTORY $EXECUTION_CONTEXT_FUNCTIONNAME)
```

Shouldn't these env var behave the same way both in Azure as in local windows laptop?

#### Investigative information
- Function App version (1.0 or 2.0): 2.0

**Comment by Francisco-Gamino** [comment]
Hello @canoas, here are a couple of ways to get the folder location of your executing function: 

If you take a look at https://github.com/Azure/azure-functions-host/wiki/Retrieving-information-about-the-currently-running-function, you can use ```FunctionDirectory```, e.g.,
```write-output "Directory: $($TriggerMetadata.FunctionDirectory)"```. Alternatively, you can the PowerShell built-in variable ```$PSScriptRoot```. Both of them should point you to the same location. 

Sample code:
```
using namespace System.Net

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

# Write to the Azure Functions log stream.
Write-Host "PowerShell HTTP trigger function processed a request."

write-output "PSScriptRoot: $PSScriptRoot"
write-output "Directory: $($TriggerMetadata.FunctionDirectory)"

# more code ...
```

Output:
![image](https://user-images.githubusercontent.com/12720858/63393354-7dbf8380-c36f-11e9-9403-bd44433cbc75.png)

**Comment by mattsmall1972** [comment]
Will you please update the previous documentation at  https://github.com/Azure/azure-functions-host/wiki/Retrieving-information-about-the-currently-running-function?  It does not work, at least for the function app that I am executing.

**Comment by Francisco-Gamino** [comment]
Hello @mattsmall1972, thank you for reporting this. I have opened an issue to track this: https://github.com/Azure/azure-functions-host/issues/4969
