### ISSUE TITLE
Powershell Az commands stopped working after latest runtime update

### ISSUE THREAD

**Issue by rphoon** [Azure/azure-functions-powershell-worker#304]
Getting the following error now calling "Get-AzResource" since the runtime was updated 2 days ago. It was running fine before then.

ERROR: The term 'Get-AzResource' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by brettsam** [comment]
@Francisco-Gamino -- FYI just moved this over to the powershell worker repo.

**Comment by AnatoliB** [comment]
@rphoon Do you have `managedDependency` enabled in `host.json`? What do you have in `requirements.psd1`? Do you do anything else to have Az modules installed?

**Comment by rphoon** [comment]
Yes, managedDependency is enabled by default.

requirements.psd1 has Az = '2.*' by default as well.

**Comment by AnatoliB** [comment]
@rphoon Thank you, the configuration looks correct. I'll have to ask you a few more questions. Are you running this app locally or on Azure? Do you see this error intermittently or every time? Any other errors or warnings in the logs?

**Comment by rphoon** [comment]
On Azure. Error happens every time. No other errors.

It seems that it stopped working after the Az module was updated to 2.5.0. I could try changing the requirements.psd1 to set Az = '2.4.0' to see if it fixes the problem.

**Comment by AnatoliB** [comment]
@rphoon No need to try `Az = '2.4.0'`: specifying exact versions is not allowed yet, you can specify only `Az = '<MajorVersion>.*'`

This problem does not seem to be related to Az 2.5.0. I'm able to run an app with Az 2.5.0 without issues. However, we know that the current implementation of managed dependencies is prone to intermittent problems on module version updates. We are going to release a more robust version soon, but it may take 2-3 weeks. In the meantime, please try these steps as temporary workarounds:

- Restart the app.
- If restarting the app does not help, please stop the app, remove the entire `/data/ManagedDependencies` directory on the storage account associated with this app, and start the app again.

Please also watch for any unusual errors and warnings in the logs.

**Comment by rphoon** [comment]
Hi Anatoli,

Stopping the app and removing the /data/ManagedDependencies directory fixed the problem.

Thanks very much.

Regards,
Raymond

**Comment by Francisco-Gamino** [comment]
Closing issue as new reliability enhancements will be release in the next update.

**Comment by premaarya** [comment]
I am facing the same issue and deleting the ManagedDependencies directory is not helping.
Anyone found a solution.

**Comment by anirudhgarg** [comment]
@premaarya what are you seeing ? Can you be more specific.

**Comment by premaarya** [comment]
My function works perfectly in the local VS Code. After deployment the function is getting invoked getting follwing error: 
```

2019-10-23T17:45:40.321 [Information] INFORMATION: PowerShell queue trigger function processed a request.
2019-10-23T17:45:41.207 [Error] ERROR: az : The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program.Check the spelling of the name, or if a path was included, verify that the path is correct and try again.At D:\home\site\wwwroot\Deployment\run.ps1:133
```

**Comment by AnatoliB** [comment]
@premaarya You are probably trying to use **az CLI** in your code (not the same as the **Az module**). Please note that **az CLI** is currently not installed on the functions sandbox on Azure. Is there a way to achieve what you want by using Az modules?

**Comment by premaarya** [comment]
@AnatoliB  looks like this is the exact issue I took the Az Module same as az CLI ... looks like they are different. Thank for pointing that out. 
I am learning ..will see if same commends avaiable in Az Module.

**Comment by AnatoliB** [comment]
Here are the instruction on how to use **az CLI** if this is what you need: https://github.com/Azure/azure-functions-powershell-worker/issues/221#issuecomment-546039332
