### ISSUE TITLE
Consistent timeouts working with Queues

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-functions-powershell-worker#310]
Hello,

My jobs consistently timeout without even starting job processing when pulling messages from the queue. Failure process rate is above 50%.
The very first step of processing is `Write-Host "PowerShell queue trigger function processed work item: $($TriggerMetadata["VMName"])"` which never makes it to output stream as you can see below since it times out before it even hits it.
It appears that function does not respect concurrency settings and creates more threads then required since I see queue count of 732 to completly dequeue when it's runs even though no more then 24 shall be running simultaneously on single worker.

![image](https://user-images.githubusercontent.com/13176884/63212710-39618880-c0ce-11e9-81b7-b54e5eb8d482.png)

![image](https://user-images.githubusercontent.com/13176884/63212717-42525a00-c0ce-11e9-9263-5d7366bae41d.png)

**Run.ps1**
```
# Input bindings are passed in via param block.
param([string] $QueueItem, $TriggerMetadata)
# Write out the queue message and insertion time to the information log.
Write-Host "PowerShell queue trigger function processed work item: $($TriggerMetadata["VMName"])"
Write-Host "Queue item insertion time: $($TriggerMetadata.InsertionTime)"
Write-Host "Starting executing Invoke-AzureRMCommand with parameters $($TriggerMetadata["VMName"]), $($TriggerMetadata["ResourceGroup"]), $($TriggerMetadata["State"]))"
$return = Invoke-AzureCommand -vmName $TriggerMetadata["VMName"] -resourceGroup $TriggerMetadata["ResourceGroup"] -PowerState $TriggerMetadata["State"]
Write-Host "Finished executing Invoke-AzureRMCommand with parameters $($TriggerMetadata["VMName"]), $($TriggerMetadata["ResourceGroup"]), $($TriggerMetadata["State"]) )"

$json = @"
[
    {
        "Return" : $($return | convertto-json),
        "VMName" : "$($TriggerMetadata["VMName"])",
        "ResourceGroup" : "$($TriggerMetadata["ResourceGroup"])"
    }
]
"@
Write-Host "Outputing following to Log Analytics $json"
Post-LogAnalyticsData -customerId $env:CustomerID -sharedKey $env:SharedKey -body ([System.Text.Encoding]::UTF8.GetBytes($json)) -logType "MetaDataLog"
```

**Host.json**
```
{
  "version": "2.0",
  "functionTimeout": "00:04:00",
  "managedDependency": {
    "enabled": true
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "extensions": {
    "queues": {
      "maxPollingInterval": "00:00:02",
      "visibilityTimeout": "00:00:30",
      "batchSize": 16,
      "maxDequeueCount": 5,
      "newBatchThreshold": 8
    }
  }
}
```
**Function.json**

```
{
  "bindings": [
    {
      "name": "QueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "metadataservicequeue",
      "connection": "useastbootdiag_STORAGE"
    }
  ]
}

```

**Function Console log**

https://gist.github.com/artisticcheese/77cc1a7926b246d1de1c52539c806e72

**Comment by JustinGrote** [comment]
Out of curiosity, why are you using a boot diagnostics storage account? Why not just use the default queue (leave it blank).

I haven't seen this behavior in my queue usage, as troubleshooting steps I would remove your custom queue settings and remove the connection line to use the default function storage account for your queues.

**Comment by artisticcheese** [comment]
Bootdiag is just used because it was in the same location as my Function. It has nothing to do with an issue though. The only way to make it work was  to increase `FUNCTIONS_WORKER_PROCESS_COUNT` and `PSWorkerInProcConcurrencyUpperBound` and stop using consumption app service plan. Looks like on consumption plan it actual spins up so many worker nodes that queue show empty but none are being processed due to concurrency issues.
I have 700 messages in queue and powershell using information from the queue to do remote work which makes a lot of outgoing REST calls to Azure infrastructure.
As I said issue is not with queue location but default setup of Powershell worker preventing such high concurrency setup on consumption plan and on app service plan without modifying those values.


(https://stackoverflow.com/questions/57514459/powershell-azure-function-times-out-on-processing-queue?noredirect=1#comment101497654_57514459)

**Comment by eamonoreilly** [comment]
Closing this out given the usage of the app settings to control concurrency.
