### ISSUE TITLE
Managed dependencies are continiously being downloaded untill all space is used

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-functions-powershell-worker#316]
Looks like each time function either being executed or deployed a new set of dependencies being downloaded. I have single function and there is 476 folders created under ManagedDependencies folder each 126 MB in size

![image](https://user-images.githubusercontent.com/13176884/63816835-4026a180-c8ff-11e9-8827-aee0b8d6c3f1.png)

**Comment by AnatoliB** [comment]
This is fixed by https://github.com/Azure/azure-functions-powershell-worker/pull/311, the fix is being deployed now. In the meantime, here is the workaround:

1. Stop the app.
2. Remove the entire ManagedDependencies folder.
3. Start the app.

**Comment by artisticcheese** [comment]
Impossible to delete those due to a volume and big number of small files. Took 3 hours and still was not done. Had to move to new AppServicePlan but good that it's fixed

**Comment by AnatoliB** [comment]
I recommended removing the entire ManagedDependencies folder for simplicity. In fact, removing the entire content is not required. The following command would remove just a few folders with names that interfere with the new dependency management logic, and this should be enough to solve the problem:

``` PowerShell
Get-ChildItem *r | ?{ $_.Name -notmatch '[.\d]r\Z' } | Remove-Item -Recurse -Force
```

This command should be invoked **from the ManagedDependencies folder**.

**Comment by linlidialpad** [comment]
This issue is still happening to me as of today, can you help? Let me know any information you need from me. 
![Screen Shot 2021-03-11 at 9 17 40 PM](https://user-images.githubusercontent.com/57730092/110896535-a9d38a00-82b0-11eb-903b-23c70c68eb43.png)

**Comment by AnatoliB** [comment]
@linlidialpad If you are using any pre-release module versions, you are probably affected by https://github.com/Azure/azure-functions-powershell-worker/issues/602. If you are _not_ using any pre-release module versions, please let us know. In this case, please also share your `requirements.psd1`, if possible.

**Comment by linlidialpad** [comment]
@AnatoliB Thanks for the quick response! It is indeed caused by some preview module version and switching to release version has resolved the problem :)

**Comment by OlafD** [comment]
I'm still seeing this issue in my Function App running with PowerShell. MDMinBackgroundUpgradePeriod is set to "7.00:00:00", MDMaxBackgroundUpgradePeriod is set to "14.00:00:00". FUNCTIONS_WORKER_PROCESS_COUNT is set to 5.
I see new folders for the managed dependencies hourly in data/ManagedDependencies, 74 new folders since yesterday evening. 
Yesterday, I stopped the function app, removed all folders from data/ManagedDependencies and started the function app again. The function app is running in a premium app service plan.
How can/should we prepare a reliable solution with this behavior?
requirements.psd1:
@{
    'Az' = '6.*'
    'AzTable' = '2.0.3'
    'PnP.PowerShell' = '1.7'
}

**Comment by AnatoliB** [comment]
@OlafD You seem to be hitting issue #647. Please note there is no version `1.7` for the `PnP.PowerShell` module on the PowerShell Gallery. You probably want to use version `1.7.0`, please specify it.
