### ISSUE TITLE
contents of ConvertTo-CSV not being written to Blob properly 

### ISSUE THREAD

**Issue by rscottwatson** [Azure/azure-functions-powershell-worker#343]
When I convert my object to a csv using the convertto-csv cmdlet the blob that gets written using the output binding has all the double quotes escaped and all the newlines have been removed and replaced with a comma.   Is this because convertto-csv creates a collection of strings?  I don't see the same behaviour with convertto-json.

eg.
```
$csvstring = $alldbs | where {$_.SubscriptionName -like '*SOMENAME*'} | select SubscriptionName, ServerName, DatabaseName | ConvertTo-CSV 

# This is not formatting the output properly
Push-OutputBinding -name outputBlob -value $csvstring
```

**Comment by AnatoliB** [comment]
@rscottwatson If you invoke the first line from a regular PowerShell console, what do you get in `$csvtring`? I'm trying to understand if your question is about anything specific to Azure Functions, or this is about the `ConvertTo-CSV` cmdlet behavior (and perhaps PowerShell as a language in general).

**Comment by rscottwatson** [comment]
When I run in a regular PS console I get the output as a typical csv file.  My question is about writing a csv file to blob storage using an azure function with an output binding. 
```
PS /Users/i840040> $alldbs | where {$_.SubscriptionName -like '*MT*'} | select SubscriptionName, ServerName, DatabaseName | select -First 3 | ConvertTo-Csv 
"SubscriptionName","Servername","DatabaseName"
"[MT ***] cust 1234","c6ns8l-aaa-p1-server","c6ns8l-aaa-p1-db"
"[MT ***] cust 1234","c6ns8l-aaa-p2-server","c6ns8l-aaa-p2-db"
"[MT ***] cust **** ","c4biqd-aaa-p1-server","c4biqd-aaa-p1-db"
```

**Comment by AnatoliB** [comment]
@rscottwatson The `$csvstring` variable in your first example contains an array of strings (**not** a single string with newline characters). When `Push-OutputBinding` receives an array, it serializes it into JSON and writes the result into the blob. When `Push-OutputBinding` receives a single string, this JSON serialization does not happen.

The decision to serialize arrays to JSON is somewhat questionable, we will need to think about it. In the meantime, as a workaround for your specific case, please try this:

``` PowerShell
Push-OutputBinding -name outputBlob -value ($csvstring -join "`n")
```

**Comment by rscottwatson** [comment]
@AnatoliB That did it!  Thank you for that.  Now I have a file that looks like a csv file.

Much appreciated.
