### ISSUE TITLE
Document Firewall dependencies for ILB ASE implementations

### ISSUE THREAD

**Issue by jsandersrocks** [Azure/azure-functions-powershell-worker#348]
We need to add Firewall dependencies for ILB ASE implementations.  For example, I found a dependency here:  https://github.com/Azure/azure-functions-powershell-worker/blob/5d39f798a41ba29bf47c89ca39977c4aa7330177/src/DependencyManagement/PowerShellGalleryModuleProvider.cs

This seems to be the only HttpClient call currently:
https://www.powershellgallery.com/*

**Comment by eamonoreilly** [comment]
Added note to https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#dependency-management to discuss adding powershellgallery.com to any firewall requirements.
