### ISSUE TITLE
Validate Functions v3 Preview

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-powershell-worker#349]
Details will be coming soon. Opening issues right now to track. 

Functions v3 preview (on .NET Core 3) is coming soon and we'd like the language worker owners to take it for a spin first and let us know if there are any issues.

Initial plan:
- Build details coming early Mon Oct 7, with a CLI build and a private site extension links.
- Would like some kind of signoff by EOD Wed Oct 9
    - That signoff is up to the language worker owner. Can be a test suite run, or even some manual validation with the CLI and/or production.

**Comment by brettsam** [comment]
Some directions and links have been added to https://github.com/Azure/azure-functions-host/issues/5041.

**Comment by AnatoliB** [comment]
I performed a basic validation: tried HTTP triggers, blob triggers, managed dependencies, using Az module from functions, using both the private site extension and the CLI. Everything worked as expected, no obvious problems.
