### ISSUE TITLE
Support for Azure App Configuration

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-functions-powershell-worker#360]
Is Azure App Configuration supported when using the PowerShell worker?

The [Quickstart: Create an Azure function with Azure App Configuration](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-azure-function-csharp) refers to using Visual Studio to add references to Microsoft.Extensions.Configuration.AzureAppConfiguration.

Is it as simple as adding a using statement referring to this in run.ps1? Or is more work required?

**Comment by Francisco-Gamino** [comment]
Hi @eamonoreilly, do we plan to support this in PowerShell? If we do, we should added to the backlog. Here is the link to the C# quick start: https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-azure-functions-csharp.

**Comment by eamonoreilly** [comment]
This appears to be supported https://github.com/Azure/AppConfiguration/issues/232 but I'm not sure if it is complete for all scenarios. If there are specific capabilities missing in the module, I would update the above issue with the ask or perhaps open up a new issue on the repo.
Closing this issue as it is better tracked in the AppConfiguration repo unless a specific Azure Functions issue comes up.
Thanks,
Eamon

**Comment by eosfor** [comment]
I did some quick and dirty implementation of some of our immediate needs: https://github.com/eosfor/psapcfg

However, implementing this as a binary module for Powershell did not go well: https://github.com/PowerShell/PowerShell/issues/11560
