### ISSUE TITLE
Change wording and severity of the "Downloading managed dependencies message".

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-powershell-worker#362]
Change wording and severity of the "Downloading managed dependencies message".

**Comment by Francisco-Gamino** [comment]
Current message: "Managed dependency download is in progress, function execution will continue when it's done."

New message: " The first managed dependency download is in progress, function execution will continue when it's done. Subsequent updates will be performed in the background."

Change severity to warning from informational.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed and merged.

**Comment by IanKemp** [comment]
What happened to the `Add a link to managed dependencies. "See for more information."` bit?
