### ISSUE TITLE
Azure Powershell 2.0 Class support 

### ISSUE THREAD

**Issue by Boriszn** [Azure/azure-functions-powershell-worker#363]
Hi Team,

First of all, Thank you so much for the **great job**.
 
I have 2 questions:

- Does PowerShell  Azure Function worker 2.* support Power Shell Classes ? 
- If yes, will class based function be supported in the future ? 
I didn't found this in the documentation.

Thank you a lot for the answers, in advance, and best regards,
Boris

**Comment by JustinGrote** [comment]
@Boriszn it supports everything powershell core supports. That said, PowerShell Classes were primarily designed to make DSC easier, there's been no further development on them in years and they are quite limited, so ask yourself if you really need a class or if it can be accomplished either by an existing dotnet type or a series of functions.

**Comment by Boriszn** [comment]
Thank you a lot, now this is clear for me.
