### ISSUE TITLE
PowerShell: can't load Microsoft.PowerShell.Utility.

### ISSUE THREAD

**Issue by Ba4bes** [Azure/azure-functions-powershell-worker#377]
I have the same error as mentioned in [this issue](https://github.com/Azure/azure-functions-core-tools/issues/1288). 

`[Process:4688]: PS C:> The module 'Microsoft.PowerShell.Utility' could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Utility'.
At line:0 char:0`

`[Process:4688]: PS C:> Debug-Runspace : The term 'Debug-Runspace' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

It started somewhere when I installed the latest Core Tools.
I use version 2.7.1948 through Chocolatey
I have .net Core SDK version 2.1, 2.2 and 3.1

I have two different VSCode environments (regular and insiders), PowerShell preview and regular, PowerShell extension preview and regular, it really doesn't seem to matter what combination I pick.  
(all of these are on the latest versions)  
 
Also tried reinstalling .net Core SDKs and Azure Core Function tools. No luck so far.

**Comment by Francisco-Gamino** [comment]
This issue is not caused by the Core Tools, so moving to the PowerShell Worker for tracking.

**Comment by Ba4bes** [comment]
After extensive troubleshooting we have found no way to fix this issue, but also no way to reproduce.
I have reinstalled my laptop (while keeping files) and removed all my profile-folders that start with a dot. 
This has fixed the issue. Thank you everyone for your time and effort. I will close this issue.

**Comment by Francisco-Gamino** [comment]
You are welcome @Ba4bes. I am glad the debugging issue was issue was resolved. Please do not hesitate to reach out if you ever need help for PowerShell in Functions. 

Thanks,
Francisco
