### ISSUE TITLE
HttpResponseContext included in tests, missing peter test examples

### ISSUE THREAD

**Issue by asears** [Azure/azure-functions-powershell-worker#389]
The tests currently include the HttpResponseContext type in the binding.  Can someone provide sample Powershell Pester Test for verifying and for mocking the function below with HttpResponseContext included?

```
Push-HttpBinding -Body $body -Name 'Response' -StatusCode Accepted -ContentType 'text/plain' -Headers $headers
```

What happened to the code changes merged by this pull request to remove the dependency on HttpResponseContext / get rid of the import statement?

https://github.com/Azure/azure-functions-powershell-worker/pull/113/commits/d72f34266838ffe2ee9dcecb02857e810a836440

**Comment by JustinGrote** [comment]
I see you're using Push-HTTPBinding, I don't think that's part of the Azure Functions code natively, it's a convenience function I wrote (assuming you're using the same thing) and showed in #208

Have you tried push-outputbinding natively?

**Comment by eamonoreilly** [comment]
Push-HTTPBinding is not supported in the platform. We will keep #208 open to track improvements there.

**Comment by asears** [comment]
Are there any pester test examples with the default Push-OutputBinding and HttpResponseContext? 
I'm just trying to create a test and I think the HttpResponseContext is part of Microsoft.Azure.Functions.PowerShellWorker.Utility.  Probably I need to import the associated namespace, working on that.  I have not seen any example tests for https://github.com/Azure/azure-functions-powershell-worker/blob/dev/examples/PSCoreApp/MyHttpTrigger/run.ps1

Would make sense to create a Function App Pester Test project / Test files as part of the examples to ensure code coverage, and perhaps even add as part of func init scaffolding.  Or add run.Tests.ps1 and some help for developers writing tests against the worker.

**Comment by JustinGrote** [comment]
@asears Not sure how deep you're looking to go with the pester testing, but you generally can't go much beyond your Push-OutputBinding.

What I do is I mock Push-OutputBinding and then do Should tests against the parameters that are on Push-OutputBinding for my unit tests, but that doesn't test that Push-OutputBinding actually is returning what you're expecting.

If you wanted to get fancy, you could have an integration pester test that would spin up Azure Function Core Tools, load your function, do an Invoke-Restmethod, and then ensure the output is as you are expecting. That would be the best way to get an end-to-end test of your code.

**Comment by asears** [comment]
Thanks!  I'm getting a Type not found error on [HttpResponseContext] when importing run.ps1.  Doesn't seem to matter whether the function is mocked or not.  It sounds like I would need to move this into it's own separate module to ignore it.

**Comment by JustinGrote** [comment]
You can mock the type:
https://github.com/pester/Pester/wiki/New%E2%80%90MockObject
