### ISSUE TITLE
Concurrency story

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-functions-powershell-worker#4]
Right now, I'm managing 1 runspace which isn't enough considering we want to handle multiple requests.

**Comment by joeyaiello** [comment]
Can we get an enumeration of our current status on this one? I know this was some discussion around:

* 24 simultaneous incoming connections (sounds like this isn't a hard requirement, but we should do some validation around the "graceful upscaling" of Windows consumption)
* "parallel foreach" from within a function (if we think this is important, we should open another issue around it)

**Comment by joeyaiello** [comment]
Wrt the first one, let's get a design started for runspace pooling with possible implementation to come later.

Wrt the second one, let's put `ThreadJob` back in the worker.

**Comment by daxian-dbw** [comment]
Closed via #123
