### ISSUE TITLE
Increase gRpc channel message size to int.MaxValue

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-powershell-worker#423]
Related issue https://github.com/Azure/azure-functions-host/issues/5650

Channel Message Size is set here: https://github.com/Azure/azure-functions-powershell-worker/blob/8cab08b1440afb775a2375ebf1c54785387d5387/src/Messaging/MessagingStream.cs#L22-L26

Need to set these values to int.MaxValue and ignore host settings.

**Comment by pragnagopa** [comment]
@AnatoliB  - can you help with this?

**Comment by AnatoliB** [comment]
Please see this comment: https://github.com/Azure/azure-functions-host/issues/5650#issuecomment-596663178
