### ISSUE TITLE
[DurableFunctions] Example should use Extension Bundle instead of extensions.csproj

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-powershell-worker#433]
https://github.com/Azure/azure-functions-powershell-worker/blob/dev/docs/durable-experimental-instructions.md#3-install-the-required-extensions

Is this step really necessary? The current extension bundles have the matching durable functions package, so this step adds a lot of compile time and complexity vs. just including the precompiled into host.json.

I did this in my host json:
```json
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "1.1.1"
  }
```

And all the examples work just fine.

More Info:
https://github.com/Azure/azure-functions-extension-bundles
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register

**Comment by AnatoliB** [comment]
@JustinGrote This is a good idea in general, and would work right now. Unfortunately, it will stop working when we migrate to Durable Functions v2 (soon), as the required DurableTask version is not in the bundle yet. On top of that, the latest DurableTask 2.* contains a bug preventing us from using it, so I want to specify an exact version for now, to make these examples self-sufficient. We can return to this idea when the extension bundles include a good DurableTask 2.* version, but I will close this issue until then.
