### ISSUE TITLE
PowerShell worker .Net version will not longer match the Host (runtime) version

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-powershell-worker#434]
Note: The next release after .Net 3 is .Net 5. For more info on .Net 5, please see https://devblogs.microsoft.com/dotnet/introducing-net-5

PowerShell 7.1-preview1 will be compiled against .Net 5, for more info, please  see https://github.com/PowerShell/PowerShell/pull/12140

As a result of this, the PowerShell worker .Net version will not longer match the Host (runtime) version

**Comment by anirudhgarg** [comment]
This is just a tracking thing. Closing this.
