### ISSUE TITLE
Unnecessary Get-Module call in profile.ps1

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#443]
The auto-generated `profile.ps1` contains the following code:

``` PowerShell
if ($env:MSI_SECRET -and (Get-Module -ListAvailable Az.Accounts)) {
    Connect-AzAccount -Identity
}
```

The `Get-Module` call creates two problems:

- The call takes ~2 seconds (on Consumption) when only Az modules are installed, and may take longer when there are more modules. This time becomes a part of the cold start time (at least in user perception).
- If the user enabled MSI but does not have Az modules installed, this code will mask the problem.

The only _potentially_ useful purpose I can think of would be to actually enable the scenario where MSI is configured but Az modules are not used. This is a corner case that does not deserve sacrificing 2 or more seconds for everybody else.

The proposal is to remove the `Get-Module` call from the templates:

``` PowerShell
if ($env:MSI_SECRET) {
    Connect-AzAccount -Identity
}
```

**Comment by Francisco-Gamino** [comment]
The `profile.ps1` template will be updated in the Core Tools, Host, and VSCode Extension. 

This work will be tracked by:
https://github.com/Azure/azure-functions-core-tools/issues/2000
https://github.com/Azure/azure-functions-host/issues/6071
https://github.com/microsoft/vscode-azurefunctions/issues/2123

**Comment by Francisco-Gamino** [comment]
This work has been completed.
