### ISSUE TITLE
Invoke Disable-AzContextAutosave from profile.ps1

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#452]
Invoking [Disable-AzContextAutosave](https://docs.microsoft.com/powershell/module/az.accounts/disable-azcontextautosave) before `Connect-AzAccount` saves 2-4 seconds. Also, from the functionality perspective, this seems to be the right thing to do in the Azure Functions context. Let's add it to the auto-generated `profile.ps1`:

``` PowerShell
if ($env:MSI_SECRET ...) {
    Disable-AzContextAutosave
    Connect-AzAccount -Identity
}
```

**Comment by Francisco-Gamino** [comment]
The `profile.ps1` template will be updated in the Core Tools, Host, and VSCode Extension. 

This work will be tracked by:
https://github.com/Azure/azure-functions-core-tools/issues/2000
https://github.com/Azure/azure-functions-host/issues/6071
https://github.com/microsoft/vscode-azurefunctions/issues/2123

**Comment by Francisco-Gamino** [comment]
This work has been completed.
