### ISSUE TITLE
Failing to load "MicrosoftTeams" PowerShell module in Azure Function App

### ISSUE THREAD

**Issue by shivashyavi** [Azure/azure-functions-powershell-worker#471]
After copying "MicrosoftTeams" modules files into Azure Kudu environment and and tried to run the "Connect-MicrosoftTeams" and getting below error,

Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' in Azure Function

![image](https://user-images.githubusercontent.com/66424568/83762251-f7bdc080-a694-11ea-9bf1-87cff2cd7caf.png)

**Comment by AnatoliB** [comment]
@shivashyavi The following workaround may help you:
- Switch your Azure Function app to PowerShell 7: https://github.com/Azure/azure-functions-powershell-worker/issues/371#issuecomment-641026259.
- Import the module in the [compatibility](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7) mode using the following command: `Import-Module MicrosoftTeams -UseWindowsPowersShell`

**Comment by anirudhgarg** [comment]
We have already tested -UseWindowsPowerShell as @AnatoliB  and that work with PowerShell 7.
