### ISSUE TITLE
EXCEPTION: Durable function is not yet supported for PowerShell

### ISSUE THREAD

**Issue by bosens** [Azure/azure-functions-powershell-worker#477]
Hi Guys,

Trying to use the PowerShell Durable Functions and its failing with "**EXCEPTION: Durable function is not yet supported for PowerShell**" when running it.

The following code was generated when creating the function via the Azure Portal and would expect it to work and throw the error.

Could someone please advise as to the real issue?

Thanks
Peter

run.ps1------------->>

using namespace System.Net

param($Request, $TriggerMetadata)

$FunctionName = $Request.Params.FunctionName
$InstanceId = Start-NewOrchestration -FunctionName $FunctionName
Write-Host "Started orchestration with ID = '$InstanceId'"

$Response = New-OrchestrationCheckStatusResponse -Request $Request -InstanceId $InstanceId
Push-OutputBinding -Name Response -Value $Response

<<------------run.ps1

**Comment by anirudhgarg** [comment]
Durable Functions PowerShell only works with PowerShell **_7_** Azure Functions which you cant create from the portal.
Still if you would still like to try it see here for how to convert your app to a PowerShell 7 app.

https://github.com/Azure/azure-functions-powershell-worker/issues/371#issuecomment-641026259

Here are the complete instructions: https://github.com/Azure/azure-functions-powershell-worker/blob/dev/docs/durable-experimental-instructions.md

**Comment by AnatoliB** [comment]
Please let us know if you hit this issue when following the instructions at https://github.com/Azure/azure-functions-powershell-worker/issues/371#issuecomment-641026259. In the meantime, I'm closing this for now.

**Comment by bosens** [comment]
Thanks guys. The information was what I needed.
