### ISSUE TITLE
Unable to ignore information stream output for Azure cmdlets generated with the last tooling

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-powershell-worker#479]
If you run the following commands to ignore the information stream, this works with no issues locally or if the user authenticates via service principal when running in Azure 

```powershell
Get-AzFunctionAppSetting -Name <functionAppName> -resourcegroupname <ResourceroupName> -InformationAction Ignore
```
However, when running in the Functions Service, this command throws an exception. Please see below:
![image](https://user-images.githubusercontent.com/12720858/85605766-55e02280-b607-11ea-84ba-535d43284823.png)

And without redirecting the Information stream, the user gets extra information logs:
![image](https://user-images.githubusercontent.com/12720858/85604666-5af0a200-b606-11ea-9078-045ce2ee5dae.png)

**Comment by anirudhgarg** [comment]
This is a problem but probably a low priotiy for now.

**Comment by yuu045-ran** [comment]
Hi @anirudhgarg , this is Yuna from CSS team.

I recently have a support ticket on this issue and these generated Information is consuming customer's AI cost and affecting the readability when customer is trying to log their personalized information.

May I know if there's going to be an ETA on this problem?
Or at least, could we have any other mitigations that will have the same impact on `| Out-Null` or any other methods to null these Information, for this `Get-AzFunctionAppSetting` command?

Thank you very much!

**Comment by anirudhgarg** [comment]
@yuu045- thanks for providing the data that this is actively affecting a customer. We will investigate if we can find any work around or fix in the upcoming week(s)

**Comment by yuu045-ran** [comment]
Hi @anirudhgarg, thank you very much for keeping an eye on this issue:)
We will be waiting for any possible mitigates.
Hopefully we could help our customer as soon as possible.

**Comment by Francisco-Gamino** [comment]
Hello @yuu045-ran -- the issue preventing the suppression of the Information stream no longer repros. This means that the customer can suppress the extra information logs using `-InformationAction Ignore`. Here is how the cmdlet call would look like:

`Get-AzFunctionAppSetting -Name <functionAppName> -resourcegroupname <ResourceroupName> -InformationAction Ignore`
