### ISSUE TITLE
Log Breaking API used by apps

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-powershell-worker#495]
Functions host logs any breaking api from 2.2 --> 3.1 . Here is the relevant code: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/BreakingChangeAnalysis/ChangeAnalysisService.cs

@AnatoliB - can you please investigate if powershell worker can do something similar and log?

**Comment by AnatoliB** [comment]
Discussed and decided that there is too much work for very little gain, so closing for now
