### ISSUE TITLE
What does Durable Functions mean for the PowerShell worker?

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-functions-powershell-worker#50]
We have a general idea behind what Durable Functions are... but how do we make one for PowerShell.

**Comment by pragnagopa** [comment]
cc: @kashimiz

**Comment by kashimiz** [comment]
As part of getting Durable Functions to work in languages run out-of-proc in Functions v2, we are developing an [execution schema](https://github.com/Azure/azure-functions-durable-extension/wiki/Out-of-Proc-Orchestrator-Execution-Schema-Reference) which is used to communicate between the process running the Functions runtime and Durable Functions extension, and the process running the [language worker](https://github.com/Azure/azure-functions-host/wiki/Language-Extensibility). 

To enable Durable Functions for PowerShell (or any other language that runs via a language worker), you'll need two things:

- [ ] support for the Durable Functions bindings in that language
- [ ] at least one shim library that can parse the input schema received from the Durable Functions extension and produce correct output schema that the extension can interpret. (Multiple shim libraries can be written for a single language, each enabling a different style/developer experience.)

You can see an example of this for JavaScript at the [Azure/azure-functions-durable-js](https://github.com/Azure/azure-functions-durable-js) repo, which is currently in public preview. The execution schema is being developed alongside this library, but is language-agnostic.

Please reach out with any questions or feedback about this - we'd love to help bring Durable Functions to PowerShell. :)

**Comment by joeyaiello** [comment]
Going to close this in favor of #77 where more discussion has occurred
