### ISSUE TITLE
Issue a warning on PowerShell 6 end-of-life for PowerShell 6 apps

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#502]
From https://docs.microsoft.com/powershell/scripting/powershell-support-lifecycle?view=powershell-7#powershell-releases-end-of-life:

Version | End-of-life
-- | --
6.2 | September 4, 2020

**Comment by fabiocav** [comment]
@AnatoliB should the milestone here be updated?

**Comment by AnatoliB** [comment]
> @AnatoliB should the milestone here be updated?

@fabiocav Thank you, done
