### ISSUE TITLE
Function Isolation

### ISSUE THREAD

**Issue by kilasuit** [Azure/azure-functions-powershell-worker#517]
Whilst locally testing a fairly complex series of PowerShell functions this threw up a need for invocation of functions locally (& also in Azure) to enforce a max concurrency of 1 PowerShell Function definition per running function runtime process. Locally this would require the need for the function runtime to shell out additional out of process runspaces, something that `Start-Job` would do, whereas `Start-ThreadJob` will not & makes this potentially not suitable for the task at hand.

To give further background these functions need to call into multiple Azure Tenants, which I was intending to use Connect-AzAccount which would have worked using Start-Job as it would have given full process isolation, whereas Start-ThreadJob doesn't

Is this something that we can achieve via a configuration setting, or something that you would be willing to add as suitable functionality that can be used both locally and in Azure too

**Comment by AnatoliB** [comment]
@kilasuit There is currently no setting that would force process isolation for function invocations within the same app. Implementing such a setting does not look trivial, so we want to understand the motivation first:
- You can invoke `Start-Job` from your function code. Does this work for you?
- Are you sure process-level isolation is really required in your case, though? If you pass a proper `DefaultProfile` to each Az command, it may give you enough isolation even within the same process. If it does not, perhaps there is an opportunity for Az modules to improve.

**Comment by AnatoliB** [comment]
@kilasuit Actually, increasing [FUNCTIONS_WORKER_PROCESS_COUNT](https://docs.microsoft.com/azure/azure-functions/functions-app-settings#functions_worker_process_count) while keeping [PSWorkerInProcConcurrencyUpperBound](https://docs.microsoft.com/azure/azure-functions/functions-reference-powershell#concurrency) at 1 (default) may satisfy your requirements right now. Please let us know if this does not work for you.

**Comment by kilasuit** [comment]
I think that may do what I wanted though I ended up going with pure rest API calls in the end as it was likely to be cleaner overall.

Useful for the next time 😊
