### ISSUE TITLE
Improve docs on PowerShell Functions concurrency and scaling

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#519]
We often receive questions on the meaning of the "requests are being queued due to no available runspaces" warning and the proper ways to scale out and control concurrency. Our existing doc at https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#concurrency answers this questions partially, but it is still not enough and we keep getting questions. I reply with the following, and this seems to be helpful:

---
> This condition will not become a reason for automatic autoscaling. You can watch for this event and build your own autoscaling logic, but I suggest considering the alternatives first. PowerShell workloads are typically I/O-bound, so increasing the number of instances will increase the cost while keeping these instances underutilized.

> Please note that this condition is not an error yet. This message is just telling you that the requests are being queued, and they will be handled when the previous requests are completed. However, if both the rate of incoming requests and the time required to handle one request are sufficiently high, eventually some requests may time out – and this is the actual problem.

> I would recommend trying out the following approaches:
>- Increase FUNCTIONS_WORKER_PROCESS_COUNT. This allows handling function invocations in multiple processes within the same instance, which introduces certain CPU and memory overhead. Depending on your workload, this may or may not become a problem. In general, I/O-bound functions will not suffer from this overhead. For CPU-bound functions, the impact may be significant.
> - Increase the PSWorkerInProcConcurrencyUpperBound app setting value. This allows creating multiple runspaces within the same process, which significantly reduces CPU and memory overhead. However, this requires all the PowerShell code (including modules) to be concurrency-safe. Many modules are, but there are exceptions.
> - Depending on your use case, Durable Functions may significantly improve scalability. PowerShell support for Durable is going to be in Public Preview in a few days. In the meantime, you can try https://github.com/Azure/azure-functions-powershell-worker/blob/dev/docs/durable-experimental-instructions.md
> - If nothing else helps and/or you are willing to just throw money at the problem, increase the number of instances.
---

Let's update the official doc accordingly.

**Comment by ggailey777** [comment]
Tracking in the docs repo as: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1760540

**Comment by stefanushinardi** [comment]
The doc has been updated: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#concurrency
