### ISSUE TITLE
doc update for PR #527 in https://docs.microsoft.com missing

### ISSUE THREAD

**Issue by mi-hol** [Azure/azure-functions-powershell-worker#542]
While 'Added support for external events and the ability to cancel an awaited durable timer #527' is a great achievement, without the related documentation few people will become aware if it :(

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=powershell#human still says 'Human interaction is currently not supported in PowerShell.'

**Comment by AnatoliB** [comment]
Thank you @mi-hol, you are absolutely correct. Please note that PowerShell Worker releases are _not_ official announcements of public feature availability. The feature is not available on the Azure Functions service yet, until the worker is deployed to Azure, which will take some time. This is when we will update the docs, too. Thank you for waiting!

**Comment by AnatoliB** [comment]
PowerShell examples are added
