### ISSUE TITLE
Unable to find type [HttpResponseContext].

### ISSUE THREAD

**Issue by nawijesi** [Azure/azure-functions-powershell-worker#545]
Hello,

I'm following this guide (https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code?pivots=programming-language-powershell) to create a Powershell function and push it to Azure locally. When I am testing this locally I get the following error in run.ps1 file: 

![image](https://user-images.githubusercontent.com/67364854/94912156-23b04d80-049f-11eb-8fa2-b992e7fc94b7.png)

However I did push the function App to azure and it runs there perfectly fine when I hit the endpoint. 
I have checked that I have **installed** all the pre requisities on my local dev environment as well: 

- An Azure account with an active subscription. Create an account for free.
- Node.js, required by Windows for npm. Only Active LTS and Maintenance LTS versions. Use the node --version command to check your version. Not required for local development on macOS and Linux.
- PowerShell 7
- Both .NET Core 3.1 and .NET Core 2.1
- Visual Studio Code on one of the supported platforms.
- The PowerShell extension for Visual Studio Code.
- The Azure Functions extension for Visual Studio Code.

Is anyone aware of this issue?

**Comment by AnatoliB** [comment]
@nawijesi Have you made any code changes? Do you still have the following line at the beginning of your run.ps1?

``` PowerShell
using namespace System.Net
```

**Comment by nawijesi** [comment]
@AnatoliB  I have not made any code changes.. yes i do have that line in ps1.. just running what was generated from the setup of functions on VS Code 

![image](https://user-images.githubusercontent.com/67364854/94975116-82f67800-0508-11eb-89fe-0bc099a6b8fe.png)

**Comment by hosulik** [comment]
I have same problem. When I coded powershell directly in the Azure portal, my function worked. Later, I downloaded app content as Visual Studio project. I did some changes in the code and after publishing from Visual Studio, my function does not work anymore.
I downloaded diagnostic dump from Kudu. I have there more errors related to ImportModuleCommand.

**Comment by linlidialpad** [comment]
I had the same issue running it from VS code the first time after all prerequisites installed. Restarting my mac solved the problem.

**Comment by AlexHimself** [comment]
I installed all of the prereq's and followed the steps and I have the same issue. No clue, it's pretty vanilla. Seems like there's an issue with the instructions.

**Comment by vonbartas** [comment]
Hi,
I have the same issue.

**Comment by Francisco-Gamino** [comment]
Hello all -- If you are still having this issue, we will need to look at the app configuration/content. For this, please open a support case via the Azure Portal and we will follow-up there.

**Comment by Thunder-Ray** [comment]
I got this error because I was trying to run PowerShell script using the run button on top right corner. This kicks off a local PowerShell session using PowerShell extension.  HttpResponseContext is not available in a local PowerShell session.

Instead, we should kick off the debug using the "Run" icon in "Run and Debug" panel after installing "Azure Function Core Tools". This will kick of a local hosted web service that simulates Azure Function. HttpResponseContext  is available in this session. 

Check "Details" of Azure Functions extension for more details.

**Comment by madrum** [comment]
Adding to Thunder-Ray's comment, the run/debug configuration must be "Attach to Node Functions", as opposed to "PowerShell Launch Current File" or "PowerShell: Interactive Session". It won't matter if you use F5 or click the Run button, so long as this configuration is selected.

My VSCode did not get automatically configured with an "Attach to Node Functions" configuration after installing the extension, so I had to manually add it to my .vscode/launch.json file. Here what the file looks like with just that debug configuration:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Node Functions",
            "type": "node",
            "request": "attach",
            "port": 9229,
            "preLaunchTask": "func: host start"
        }
    ]
}
```

**Comment by potatoqualitee** [comment]
Thank you @madrum -- that worked for me!
