### ISSUE TITLE
Durable Functions not displaying function name in showHistory on TaskScheduled

### ISSUE THREAD

**Issue by djradium** [Azure/azure-functions-powershell-worker#551]
Hi, we are taking our first dive into durable functions and it appears when querying the history of statusQueryGetUri with showHistory=true, then the scheduled activity functions do not display the FunctionName untill they set to TaskCompleted.

However, when digging into the function queues/tables it does show this information. Screeen shot added for reference

![image](https://user-images.githubusercontent.com/26868369/97572735-9fd77b80-19e0-11eb-9003-dab2a8890721.png)

**Comment by Francisco-Gamino** [comment]
Could you please use the `Set-DurableCustomStatus` to get the status of your orchestration as described here https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-custom-orchestration-status?tabs=powershell#visualize-progress?
