### ISSUE TITLE
User-assigned managed identity regression in Az.Accounts 2.1.0

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#552]
**_Resolved: see "Update 2020-11-02" below"_**

Before Az.Accounts **2.1.0**, user-assigned managed identities could be used in PowerShell Functions like this:

``` PowerShell
Connect-AzAccount -Identity -AccountId <guid>
```

Starting from Az.Accounts **2.1.0**, the same code reports the following error:

```
ManagedIdentityCredential authentication failed: Service request failed.
```

## Workaround

The workaround is to pin your Az.Accounts to the previous working version (**1.9.5**).

### Method 1: Editing requirements.psd1

- Remove the `Az` module entry from `requirements.psd1`.
- Add the following line to `requirements.psd1`:

``` PowerShell
@{
    ...
    'Az.Accounts' = '1.9.5'
    ...
}
```

- At the beginning of `profile.ps1`, invoke:

``` PowerShell
Import-Module Az.Accounts -RequiredVersion '1.9.5'
```
The last step is necessary because installing other Az.* modules may automatically install higher versions of `Az.Accounts`, and this is what PowerShell may load by default.

### Method 2: Include the desired module versions into the app

- Include `Az.Accounts` module (and other modules, if desired) content into the app directly (see [Function app-level Modules folder](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell?tabs=portal#function-app-level-modules-folder)). Make sure there is no version of `Az.Accounts` higher than 1.9.5.
- Remove the references to these modules from `requirements.psd1`.

Please note that modules included into the app directly are never auto-upgraded by Managed Dependencies automatically.

## Update 2020-11-02

The regression is fixed in Az.Accounts 2.1.2, which is published to the PowerShell Gallery now. The workaround described above is not required anymore.

The _newly deployed_ apps that depend on Az (without specifying exact Az.Accounts versions) will work as they used to work before.

The _existing_ apps that already happened to pick up Az.Accounts 2.1.0 will self-heal automatically in the next Managed Dependencies update cycle (by default, within 1-7 days - for more details, see [the relevant Function app settings documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell?tabs=portal#dependency-management)). If you want to ensure the fix is applied sooner, please add the following entry to requirements.psd1:

``` PowerShell
@{
    ...
    'Az.Accounts' = '2.1.2'
    ...
}
```

In the future, if you want to make sure Az.Accounts is pinned to any specific version, please be aware that the dependencies between Az.Accounts and other Az.* modules are configured like this (see Package Details on the PowerShell Gallery):
```
Az.Accounts (>= 1.7.5)
```
As a result of this, installing older versions of Az will always bring in the _latest_ version of Az.Accounts. For example, the following command:
``` PowerShell
InstallModule -Name Az -RequiredVersion 3.8.0
```
will install Az.Accounts 2.1.2 now. In the future, exactly the same command will install a _newer_ version of Az.Accounts. This is exactly what's happening in Azure Functions as well, and this is why pinning just the Az module version is not enough. If you must pin Az.Accounts to any specific version, the original workaround described above is still required.

**Comment by pragnagopa** [comment]
cc @pragnagopa @finbar - fyi in case we see more CRIs

**Comment by pragnagopa** [comment]
So far we have two CRIs. Opened tracking issue: https://github.com/Azure/azure-powershell/issues/13371

**Comment by muntaserq** [comment]
For some odd reason, in addition to the proposed workaround, I had to explicitly import the `1.9.5` version of the module in `profile.ps1` because the `Az.Accounts` version `2.1.0` stuck around in the function app.

`Import-Module -Name 'Az.Accounts' -RequiredVersion '1.9.5'`

**Comment by muntaserq** [comment]
@AnatoliB After rolling this out to the various azure function apps, I'm stilling getting an error across several deployments. Is there an issue with dependency management in Azure Functions for PowerShell?
This is my requirements.ps1 file:
```
@{
    'Az.Accounts' = '1.9.5'
    'Az.KeyVault' = '1.6.0'
    'Az.Storage' = '1.6.0'
    'SqlServer' = '21.1.18218'
}
```

```
2020-10-30T16:54:55.361 [Error] ERROR: The specified module 'Az.Accounts' with version '1.9.5' was not loaded because no valid module file was found in any module directory.

Exception             : 
    Type    : System.IO.FileNotFoundException
    Message : The specified module 'Az.Accounts' with version '1.9.5' was not loaded because no valid module file was found in any module directory.
    HResult : -2147024894
TargetObject          : Az.Accounts
CategoryInfo          : ResourceUnavailable: (Az.Accounts:String) [Import-Module], FileNotFoundException
FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
InvocationInfo        : 
    MyCommand        : Import-Module
    ScriptLineNumber : 16
    OffsetInLine     : 1
    HistoryId        : 1
    ScriptName       : D:\home\site\wwwroot\profile.ps1
    Line             : Import-Module -Name 'Az.Accounts' -RequiredVersion '1.9.5'

    PositionMessage  : At D:\home\site\wwwroot\profile.ps1:16 char:1
                       + Import-Module -Name 'Az.Accounts' -RequiredVersion '1.9.5'
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : D:\home\site\wwwroot
    PSCommandPath    : D:\home\site\wwwroot\profile.ps1
    InvocationName   : Import-Module
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, D:\home\site\wwwroot\profile.ps1: line 16
PipelineIterationInfo : 
```

**Comment by pragnagopa** [comment]
@anirudhgarg - Can you please follow up on the Azure/azure-powershell#13371 to get the right traction?

**Comment by anirudhgarg** [comment]
@pragnagopa  yes we have followed up with the Azure PowerShell team and I have updated https://github.com/Azure/azure-powershell/issues/13371

**Comment by muntaserq** [comment]
> @anirudhgarg - Can you please follow up on the [Azure/azure-powershell#13371](https://github.com/Azure/azure-powershell/issues/13371) to get the right traction?

It appears to be due to the PowerShell Gallery outage that started today:
The PowerShell Gallery is currently: Experiencing an outage as of 10/30 at 06:03AM UTC

https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md

**Comment by anirudhgarg** [comment]
yes unfortunately also hit at the same time

**Comment by AnatoliB** [comment]
Please note that the PowerShell Gallery outage is a separate issue, coincidentally happening now. When the Gallery is fixed, the Az.Accounts regression is still an issue.

**Comment by AnatoliB** [comment]
I've just realized that the `Import-Module Az.Accounts -RequiredVersion '1.9.5'` step is not optional, almost every app using user-assigned identities will need it now. I will update the guidance.

**Comment by ChendrayanV** [comment]
> I've just realized that the `Import-Module Az.Accounts -RequiredVersion '1.9.5'` step is not optional, almost every app using user-assigned identities will need it now. I will update the guidance.

At my workplace I have three environment - DEV use 2.1.0 (Az.Accounts) with MSI - No impact, Where in TST use 2.1.0 (Az.Accounts) and fails. So, I changed to 1.9.5 in test and worked as expected. 

Both the environment used same plan and same code. Agree it's an module issue. But, I need to know why compute engine has difference?

**Comment by ChendrayanV** [comment]
@anirudhgarg  and @AnatoliB - I have two apps in same plan. Only one got impacted due to 2.1.0 regression issue. But not other app.

**Comment by simonesavi** [comment]
I faced the same problem. There is a solved bug in Az.Accounts 2.1 ([here](https://github.com/Azure/azure-powershell/pull/13386))

To avoid the problem it can be used the requirements.psd1 with follow configuration:
```
@{
    'Az'           = '4.8.0'
}
```

This version contains Az.Accounts 1.9.5

I have also found that if you previously used the Az.Accounts module v2.1.0, the downgrade isn't automatic. I believe this happen because function download the decencies once at startup. For this it is required to specific which version of Az.Accounts module to use.
If it's possible, try a fresh deployment of function with Az version 4.8.0.

@ChendrayanV I suggest to you to remove the version 2.1.0 because it contains an authentication issues, and in the correct conditions it could potentially stop to work.

**Comment by TylerLeonhardt** [comment]
I just wanted to also add that I experienced issues with `Connect-AzAccount -Identity` using _System_ assigned MSI with the latest version of `Az.Accounts` (2.1.2)

**Comment by AnatoliB** [comment]
@TylerLeonhardt Thank you, could you please add more details on your issues? Have you seen them on the older Az.Accounts versions?

**Comment by AnatoliB** [comment]
I updated the guidance on how to properly pin Az.Accounts to a specific version, see the original post above.

Please note that the **Az** module does not in fact contain _any_ **Az.Accounts** version. Instead, it specifies dependency constraints in this form:
```
Az.Accounts (>= 1.7.5)
```
As a result, pulling almost _any_ version of Az from the PowerShell Gallery automatically pulls the _latest_ Az.Accounts. The workaround described in the original post is required to deal with that.

**Comment by jeffwmiles** [comment]
For what it's worth, even after pinning my modules at Az = 4.8 and Az.Accounts = 1.9.5, my function app would randomly be unable to load these modules and all my functions would error out:
```
2020-11-05T16:00:29.005 [Error] Executed 'Functions.Get-AppGw-Health' (Failed, Id=bc96fb86-70de-4b3c-b758-9d82c8a19332, Duration=222795ms)Result: FailureException: Failed to install function app dependencies. Error: 'Failed to install function app dependencies. Error: 'The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:Unable to save the module 'Az'.''Stack:    at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitOnDependencyInstallationTask()  in D:\a\1\s\src\DependencyManagement\DependencyManager.cs:line 238at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitForDependenciesAvailability(Func`1 getLogger) in D:\a\1\s\src\DependencyManagement\DependencyManager.cs:line 157at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequest(StreamingMessage request) in D:\a\1\s\src\RequestProcessor.cs:line 245
2020-11-05T16:00:29.871 [Error] ERROR: The specified module 'Az.Accounts' with version '1.9.5' was not loaded because no valid module file was found in any module directory.Exception             :Type    : System.IO.FileNotFoundExceptionMessage : The specified module 'Az.Accounts' with version '1.9.5' was not loaded because no valid module file was found in any module directory.HResult :
```

I had to manually load the modules myself and remove them from requirements.psd1 in order to get any stability.

**Comment by AnatoliB** [comment]
Thank you @jeffwmiles. The PowerShell Gallery seems to be experiencing intermittent performance issues now. Until this is fixed on the Gallery side, retries may help. Alternatively, use other methods of deploying modules, like you already do. Please also know that only the first invocation after deploying the app is affected: if you manage to get it running once, all the subsequent module upgrades will be performed on the background, unaffected by PowerShell Gallery issues.

This is not related to the Az.Accounts regression, though.

**Comment by ThePoShWolf** [comment]
I wish this issue was easier to find! I spent a couple hours troubleshooting this issue on package deployments and finally found this issue.

Az.Accounts v2.1.2 does not work for me. I had to forcibly use v1.9.5 in the requirements.psd1 and profile.ps1 as outlined above:

The error I got on v2.1.2 was a file not found error for 'C:\home\site\wwwroot\.IdentityService'

**Comment by AnatoliB** [comment]
@ThePoShWolf The problem you are referring to is actually tracked by a separate issue: https://github.com/Azure/azure-functions-powershell-worker/issues/554. The mitigation (reverting to 1.9.5) is the same.

**Comment by ThePoShWolf** [comment]
@AnatoliB  - My bad, I had several issues open combing through them. I'll copy that over there as well.

**Comment by AnatoliB** [comment]
I'm closing this because this specific regression has been fixed in Az.Accounts 2.1.2. Please note that #554 has not been fixed yet. The same [workaround (pinning Az.Accounts to 1.9.5)](https://github.com/Azure/azure-functions-powershell-worker/issues/552#issue-732797653) should still be applied if you are affected by #554.

**Comment by simonesavi** [comment]
Hi @AnatoliB, just created a new function with a user-assigned managed identity associate to it.

During the first execution the function downloads the dependencies and this means the Az.Accounts 2.2.1. 

With this configuration I'm receiving below error:

`2020-11-23T09:50:54.445 [Warning] The first managed dependency download is in progress, function execution will continue when it's done. Depending on the content of requirements.psd1, this can take a few minutes. Subsequent function executions will not block and updates will be performed in the background.
2020-11-23T09:52:32  No new trace in the past 1 min(s).
2020-11-23T09:52:37.747 [Warning] WARNING: Unable to acquire token for tenant 'organizations'
2020-11-23T09:52:39.908 [Error] ERROR: ManagedIdentityCredential authentication failed: Service request failed.Status: 400 (Bad Request)Headers:Date: Mon, 23 Nov 2020 09:52:37 GMTContent-Length: 138Exception             :Type           : Azure.Identity.AuthenticationFailedExceptionTargetSite     :Name          : FailWrapAndThrowDeclaringType : Azure.Identity.CredentialDiagnosticScope, Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8MemberType    : MethodModule        : Azure.Identity.dllStackTrace     :at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)at...`

It the code I didn't insert any `Connect-AzAccount` command. I receive this error only execution function
