### ISSUE TITLE
Using Invoke-AzResourceAction causes Trace-PipelineObject to throw an error

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-functions-powershell-worker#559]
We are using [Invoke-AzResourceAction](https://docs.microsoft.com/en-us/powershell/module/az.resources/invoke-azresourceaction?view=azps-5.0.0) in an Azure Function. The command succeeds, but always returns an error - even inside a try/catch. Works without any errors locally - hence I suppose the issue is related to the Azure Functions PowerShell Worker.

The error is:
> ERROR: Trace-PipelineObject : Cannot bind argument to parameter 'InputObject' because it is null. + CategoryInfo : InvalidData: (:) [Trace-PipelineObject], ParameterBindingValidationException + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Azure.Functions.PowerShellWorker.Commands.TracePipelineObjectCommand Script stack trace: at <ScriptBlock>, D:\home\site\wwwroot\BackupFileShare\run.ps1: line 62 System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'InputObject' because it is null. at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags) at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStateInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets) at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingState(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets) at System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject inputToOperateOn) at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject inputToOperateOn) at System.Management.Automation.CommandProcessor.Read()

**Comment by AnatoliB** [comment]
@janegilring Could you please share a code sample? Please try to either capture the output of Invoke-AzResourceAction into a variable, or pipe it to Out-Null, and let us know if this helps as a workaround.

**Comment by janegilring** [comment]
@AnatoliB Here is a code sample:

```powershell

$null = Set-AzContext $AzSubscriptionId

$AzContainerGroup = Get-AzContainerGroup -ResourceGroupName $AzContainerGroupResourceGroupName -Name $AzContainerGroupName

Write-Output "Starting Azure Container Instance $AzContainerGroupName"

try {

    Invoke-AzResourceAction -ResourceId $AzContainerGroup.Id -Action start -Force -ErrorAction Stop

}

catch {

    Write-Warning -Message $_.Exception.Message

}
```

**Comment by janegilring** [comment]
@AnatoliB Piping to Out-Null seems to be a workaround, thanks. Although the most optimal would of course to have this exception not occur in the first place, but at least in my scenario it mitigates the issue of false ops-alerts.

Another curiosity is that even though the command succeeded and the container instance started, the following was logged:
```
WARNING: ServiceUnavailable : The requested resource is not available in the location 'westeurope' at this moment. Please retry with a different resource request or in another location. Resource requested: '1' CPU '1.5' GB memory 'Linux' OS virtual network CorrelationId: ee24a33a-3847-4dc0-b5f0-b320f7169f60
```

This might not be relevant to this issue, but wanted to mention it anyway.

**Comment by AnatoliB** [comment]
@janegilring  This seems to be related to a more generic issue: #561. If Invoke-AzResourceAction returns $null sometimes, the rest is explained. Apart from the Trace-PipelineObject and the warning, do you see any other output from Invoke-AzResourceAction?

One could argue that returning $null from PowerShell cmdlets is not a good practice in general (and this is why we haven't encountered this bug until now). However, regardless of the cmdlet authors decisions, this technically works in regular PowerShell, so we should fix it in Functions.

**Comment by janegilring** [comment]
@AnatoliB Nothing returned except the warning I mentioned. I would also agree that it should work in Functions since it works in regular PowerShell, although the cmdlet design may have room for improvements.
