### ISSUE TITLE
FUNCTIONS_EXTENSION_VERSION ~2 does not work but ~2.0 works

### ISSUE THREAD

**Issue by jagdishrajan** [Azure/azure-functions-powershell-worker#587]
So far my FUNCTIONS_EXTENSION_VERSION has been set to ~2 and I've got the 2.x version of Azure Functions.  However, this morning that changed and I was switched to Azure Functions 3.x.  After some debugging I see that setting FUNCTIONS_EXTENSION_VERSION to ~2.0 keeps Azure Functions at 2.x but ~2 does not.

**Comment by anirudhgarg** [comment]
@jagdishrajan - have a look at this: https://github.com/Azure/app-service-announcements/issues/266
