### ISSUE TITLE
Add support for the local RPC endpoint

### ISSUE THREAD

**Issue by davidmrdavid** [Azure/azure-functions-powershell-worker#597]
The Durable Extension recently introduced a [local rpc endpoint](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.durabletaskoptions.localrpcendpointenabled?view=azure-dotnet) feature that enables Durable SDKs to communicate directly to the Durable Functions API, whereas before this communicate would occur via HTTP calls. Without this feature, we cannot integrate Durable Functions for PowerShell with EasyAuth, as framework-internal HTTP calls will fail due to authentication requirements.

**Implementation Requirements**
Thankfully, it appears that supporting this feature is relatively simple: it simply means that we call a different URI in places where we used to make HTTP requests. Also, it **appears** that this feature is only used for durable clients bindings, which potentially limits the scope of this refactor.

Judging by its usage in the JavaScript SDK, I expect the following APIs need to be revised:
* purgeInstanceHistory
* * JS example [here](https://github.com/Azure/azure-functions-durable-js/blob/297cc490e70b06eb7ebe418edefb4f5aa2b7fee1/src/durableorchestrationclient.ts#L290)
* raiseEvent
* * JS example [here](https://github.com/Azure/azure-functions-durable-js/blob/297cc490e70b06eb7ebe418edefb4f5aa2b7fee1/src/durableorchestrationclient.ts#L420)
* startNew
* * JS example [here](https://github.com/Azure/azure-functions-durable-js/blob/297cc490e70b06eb7ebe418edefb4f5aa2b7fee1/src/durableorchestrationclient.ts#L674)
* terminate
* * JS example [here](https://github.com/Azure/azure-functions-durable-js/blob/297cc490e70b06eb7ebe418edefb4f5aa2b7fee1/src/durableorchestrationclient.ts#L674)
* getStatusBy
* * JS example [here](https://github.com/Azure/azure-functions-durable-js/blob/297cc490e70b06eb7ebe418edefb4f5aa2b7fee1/src/durableorchestrationclient.ts#L875)

I've omitted the entity APIs that make use of this feature as I believe PowerShell doesn't support those yet. If needed, let me know and I can list those JS examples as well 😄

**Comment by AnatoliB** [comment]
These are not currently supported in PowerShell Functions:

- purgeInstanceHistory
- terminate
- getStatusBy

So, I will be closing this issue when #626 is merged. When we implement the three features above, we will use the local RPC endpoint from the beginning.
