### ISSUE TITLE
Az.Accounts v 2.2.6 get's loaded without being defined in requirements.psd1

### ISSUE THREAD

**Issue by Agazoth** [Azure/azure-functions-powershell-worker#610]
I have a function, that utilizes a module that is incompatible with Az.Accounts 2.*

I have a requirements.psd1 file defining the following modules:
```powershell
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'. 
    'Az.KeyVault' = '2.2.1'
    'Az.Accounts' = '1.9.5'
    'Az.Storage' = '2.7.0'
    'partnercenter' = '3.0.10'
}
```

When loading the functions for the first time, Az.Accounts 2.2.6 gets loaded along with the other modules even though it is not defined in the file, and my code breaks

I can delete the 2.2.6 folder from the share on the storage account (found in File Shares\func-name\data\ManagedDependencies\longnumber.r\Az.Accounts and my code will run without errors.

Unfortunately the 2.2.6 version somehow gets loaded again. There is no pattern in when. I just had my function run for 8 days without issues (runs every night), today the 2.2.6 version got loaded again and my code broke. I deleted the folder and the code runs again, but I can now see that the 2.2.6 folder has been loaded (but not locked), so the code will break again at next run, if I do not delete it again.

I do not find this behavior logical. Can anyone explain, why the 2.2.6 version gets loaded and how to avoid that (without deactivating module loading via requirements.psd1)?

I would be happy to provide further information on this issue.

**Comment by AnatoliB** [comment]
**Why this is happening**

The dependencies between Az.* modules are set up in such a way that installing almost any Az.* module leads to installing the latest Az.Accounts side-by-side with any other installed version. After the module is installed to the file system, any attempt to invoke a command from this module or any dependent module makes PowerShell load the latest Az.Accounts.

**What you can do about it**

Don't try to modify the content under the ManagedDependencies folder: it is managed automatically, and any changes can (and eventually will) be overwritten. The correct way to use an older version of Az.Accounts is:
1. Specify the version you need in `requirements.psd1` (you did this correctly).
2. **THIS STEP IS VERY IMPORTANT:** In your app code, _before invoking any Az.* command or importing any Az.* module_, invoke `Import-Module -RequiredVersion <desired_version>`. I recommend doing this at the very beginning of `profile.ps1`. As a result, PowerShell will not attempt to also import the latest version into this PowerShell session anymore, even though it is present on the file system.

@Agazoth, I hope this helps. I'm closing this issue, feel free to continue the discussion if needed.

**Comment by Agazoth** [comment]
Thanks @AnatoliB I'll give that a shot right away and check back in.
