### ISSUE TITLE
Document the way to use a specific module version when multiple versions get installed side-by-side

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#612]
Depending on the content of `equirements.psd1` and the module versions available on the PowerShell Gallery, multiple versions of the same module may be installed to the file system side-by-side. It is not immediately obvious to the user which version will be used as a result, and how to force the app to use a desired version. We need to document the guidance (specifically, the `Import-Module` step):

- https://github.com/Azure/azure-functions-powershell-worker/issues/610#issuecomment-800453798
- https://github.com/Azure/azure-functions-powershell-worker/issues/552#issuecomment-719572961

We want to update the doc at https://aka.ms/functions-powershell-managed-dependency, and perhaps even include this in the auto-generated requirements.psd1 comments.

**Comment by Francisco-Gamino** [comment]
Doc is available at https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell?tabs=portal#dependency-management.
