### ISSUE TITLE
Durable functions does not work in combination with App Service AD Authentication / Authorization

### ISSUE THREAD

**Issue by Willem-J-an** [Azure/azure-functions-powershell-worker#613]
Is this a bug or a missing feature?

The observed behavior:
- AD authenticated call returns OrchestrationCheckStatusResponse object
- The provided URLs  in the response object do not work with a bearer token included, or excluded. (404 and 403)
- The Orchestration function does not trigger after Start-NewOrchestration

It works fine locally, and works fine in the cloud when I disable AD authentication/Authorization.

**Comment by stefs987** [comment]
I've just been battling this same issue today until I came across this issue. Same result, PowerShell Durable Function app secured with AD, results in HTTP starter function running successfully, apparently returning an instance ID for the orchestration, but orchestrator never runs and never starts, no logs, nothing in storage account/queues etc. Eventually, I get a (slightly bizarre) 404 back in Logic Apps (I'm starting the function from there). If I disable Azure AD auth everything runs fine.

I want to be sure it was a PowerShell Durable Function issue, so tested a C# Durable Function app works just fine using same steps to secure with Azure AD auth, so seems to be an issue with PowerShell only (guess that's the risk of using preview!)
