### ISSUE TITLE
Testing on Consumption Plan or App Service?

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-powershell-worker#63]
Hello Team,

Very much looking forward to this worker and thanks for your hard work. Is there a process for adding this worker to the v2 runtime on the Azure consumption plan or a private app service, or is it only possible to run on a functions runtime develop host today?

Just curious if it was possible to test "in production" so to speak along with integrations to app insights, etc. so thanks!

**Comment by asavaritayal** [comment]
@JustinGrote unfortunately, we don't have an option to run on Azure today. The feature still has some ways to go before we can ask our customers to give it a try themselves. However, we'll make sure to keep the repo updated with the latest - please stay tuned!
