### ISSUE TITLE
Investigate why Stop-DurableOrchestration returns `404 Not Found` on an started orchestration

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-powershell-worker#640]
The repro is available at https://github.com/Azure/azure-functions-powershell-worker/blob/dev/test/E2E/TestFunctionApp/DurableClientTerminating/run.ps1#L14

**Comment by Francisco-Gamino** [comment]
Hello @davidmrdavid -- I am tagging you in this issue given you are our Durable Functions SMA. This test case was disabled because it was randomly failing. Next time you are working on this area, could you please take look? Thank you.

**Comment by davidmrdavid** [comment]
Thanks @Francisco-Gamino. Will do.
