### ISSUE TITLE
Push-OutputBinding not working in ActivityTrigger 

### ISSUE THREAD

**Issue by kwill-MSFT** [Azure/azure-functions-powershell-worker#646]
Using the standard VSCode function creation templates, I created an orchestrator with an activity function defined as:

function.json
```
{
    "bindings": [{
            "name": "name",
            "type": "activityTrigger",
            "direction": "in"
        },
        {
            "type": "queue",
            "direction": "out",
            "name": "outputQueueItem",
            "queueName": "outqueue",
            "connection": "AzureWebJobsStorage"
        }
    ]
}
```

run.ps1
```
param($name)

Write-Information "Pushing to outputQueueItem output binding"
Push-OutputBinding -Name outputQueueItem -Value "Queue item from Hello1"
Write-Information "Done"

"Hello $name!"
```

The Write-Information lines get logged, but no queue item is created.  The same Push-OutputBinding works fine from other triggers such as an httpTrigger.

Repro attached.
* Queue item gets generated correctly when running http://localhost:7071/api/HttpTrigger1
* Queue item is not generated when running http://localhost:7071/api/orchestrators/DurableFunctionsOrchestrator1

[FunctionsOutputBinding.zip](https://github.com/Azure/azure-functions-powershell-worker/files/6665913/FunctionsOutputBinding.zip)

**Comment by stefs987** [comment]
Just ran into the same issue. It also does not work with a queue as an output binding in an orchestrator and using Push-OutputBinding in the orchestrator. No errors, but queue message is not created. I could also replicate with an activity function as reported by the OP. Any news on this?

**Comment by NikoMix** [comment]
Also affected by this. There is no Error/Warning/Message showing up,  the Queue Item simply does not show up. Application Insights also tracks no calls towards the Storage Account. It's added to Sprint 105 which is showing 3 Months past due - is this still under investigation? Any further information needed?

**Comment by haripraghash** [comment]
Is this issue sorted? I seem to be having the same issue with the same repro attached above.
I am using an actual storage account as opposed to azurite. 

Azure Functions Core Tools
Core Tools Version:       4.0.3971 Commit hash: d0775d487c93ebd49e9c1166d5c3c01f3c76eaaf  (64-bit)
Function Runtime Version: 4.0.1.16815

**Comment by davidmrdavid** [comment]
Hi @haripraghash, @NikoMix, @stefs987, and @kwill-MSFT.

Sorry for the poor communication here, I didn't realize the issue auto-closed when I merged my PR, that was a mistake on my part. This issue was patched in PR  #702 and will be included as a part of the next PowerShell Azure Functions worker release. Unfortunately, I don't have much control over the speed of that process, but I understand it takes a few weeks.

For context about the future: I've taken ownership of the Durable Functions PowerShell experience, and I'm working to improve various other parts of it. In particular, with respect to the speed at which these patches can be released, I'm looking to make the Durable Functions component of the PowerShell worker be independently released, which would give me more control over the release cycle and speed; a similar model to what we have in the JS and Python experiences for Durable Functions. In any case, I wanted to give a heads up that further improvements are in the works, but it'll require a few months to get there.

**Comment by haripraghash** [comment]
@davidmrdavid Thank you for clarifying that.

**Comment by ghost** [comment]
@davidmrdavid are you able to provide the build number that will be pushed to Azure so I can know when it's been deployed? Thanks!

**Comment by ghost** [comment]
@davidmrdavid I can confirm this is now working for me with build 4.1.3.17473 in Azure. Thanks for fixing this one.

**Comment by thunderstorm654** [comment]
> @davidmrdavid I can confirm this is now working for me with build 4.1.3.17473 in Azure. Thanks for fixing this one.

Good news, thanks for confirming. How do you check which build is live in Azure?

**Comment by ghost** [comment]
@thunderstorm654 this is something I learnt from MS as it's not intuative at all.

Open your function app in the Azure portal and select the Overview tab.

After a slight delay (maybe 10 seconds) in the _Essentials_ section (at the top) you should see a _See more_ link under _tags_ (not the one next to properties. Click that and then _Runtime version_ should appear under properties on the right hand side.

**Comment by thunderstorm654** [comment]
> @thunderstorm654 this is something I learnt from MS as it's not intuative at all.
> 
> Open your function app in the Azure portal and select the Overview tab.
> 
> After a slight delay (maybe 10 seconds) in the _Essentials_ section (at the top) you should see a _See more_ link under _tags_ (not the one next to properties. Click that and then _Runtime version_ should appear under properties on the right hand side.

Brilliant thanks so much for replying - been wondering how to check this for a long time! Turns out it was hiding in *almost* plain sight all along :)

**Comment by davidmrdavid** [comment]
Thanks @oobegreg for helping with the discussion here! Glad to hear the patch is finally out. Thanks all
