### ISSUE TITLE
When the module version does not *precisely* match the version on the PS Gallery, the worker keeps downloading modules too often

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#647]
If `requirements.psd1` contains a module version that is similar but is not precisely equal to the version on the PS Gallery, the worker downloads modules on every worker start, consuming more and more storage. For example, this app will run into the issue:

**requirements.psd1**

``` PowerShell
@{ PnP.PowerShell = '1.5' }
```

The problem is that the PS Gallery has version **1.5.0** of this module, but not **1.5**. However, the `Save-Module` cmdlet is "smart" enough to accept that, and it installs version **1.5.0** instead of the specified **1.5**, and this is why the worker does not complain about the `requirements.psd1` content to begin with. However, the next time a worker starts, it checks whether the **1.5** version is present, and it uses a simple string comparison for this, so it does not find it and decides to download dependencies again.

We need to either adjust the module version comparison algorithm to match the `Save-Module` logic and tolerate the trailing ".0", or at least perform this check immediately after the download, so that this module is rejected right away and the user is informed about this.

**Comment by Francisco-Gamino** [comment]
Use Find-Module to try to find the version required by the app. If not match is found, write a warning with the available versions. 

For V4, the warning will be an error (breaking change).
