### ISSUE TITLE
Dependency story

### ISSUE THREAD

**Issue by tylerl0706** [Azure/azure-functions-powershell-worker#69]
How will the user package up module dependencies in their function app?

We will have the user package up their modules to a `Modules` folder either at the `function` level or at the `function app` level. We will also modify the PSModulePath so it looks like (in order):

`/path/to/function/Modules` - modules that apply to a specific function
`/path/to/functionapp/Modules` - modules that apply to all functions
`/path/to/powershellworker/Modules` - modules that ship with the worker

We can also have pack put the modules in the right module path but that will be covered in #68

**Comment by daxian-dbw** [comment]
The module folder in a specific function level might be a bit overkill. I suggest we go with FunApp level module folder and worker level module folder. This will make it easy to pack.

If we get a feedback requesting the specific function level module folder, we can revisit.

**Comment by tylerl0706** [comment]
fixed in #76
