### ISSUE TITLE
Unable to install large module as managed dependency

### ISSUE THREAD

**Issue by tristan-earl** [Azure/azure-functions-powershell-worker#698]
In my PowerShell Azure Function, I'm including the [MicrosoftTeams module](https://www.powershellgallery.com/packages/MicrosoftTeams/2.6.0) v2.6.0 as a required module (in requirements.psd1 file).

EXPECTED
MicrosoftTeams module is able to be successfully installed.

ACTUAL
After deploying, when I try to execute my Function, it fails with the following error:
```
Exception while executing function: Functions.ConfigDaxTeams Result: Failure
Exception: Failed to install function app dependencies. Error: 'Failed to install function app dependencies. Error: 'The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to save the module 'MicrosoftTeams'.''
Stack:    at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitOnDependencyInstallationTask() in /home/vsts/work/1/s/src/DependencyManagement/DependencyManager.cs:line 246
   at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitForDependenciesAvailability(Func`1 getLogger) in /home/vsts/work/1/s/src/DependencyManagement/DependencyManager.cs:line 164
   at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequest(StreamingMessage request) in /home/vsts/work/1/s/src/RequestProcessor.cs:line 245 
```

With some help from the Azure Functions team, further details were discovered:

```Package 'MicrosoftTeams' failed to be installed because: There is not enough space on the disk.```

The module is ~220 MB on disk.

REPRO
1) Create a PowerShell Azure Functions project.
2) Include the following in the requirements.psd1 file
```
@{
    MicrosoftTeams = '2.*'
}
```
3) Deploy to Azure Function and execute function.

**Comment by stefanushinardi** [comment]
Hello, 

Unfortunately we do not have much control over the size of the tmp directory that is used to download the module. 

The workaround could be found here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell?tabs=portal#function-app-level-modules-folder.

**Comment by tristan-earl** [comment]
Thanks, we're using that workaround for now.

**Comment by Francisco-Gamino** [comment]
Closing given that there is a workaround.
