### ISSUE TITLE
Context.InstanceId cannot be accessed

### ISSUE THREAD

**Issue by anushkakda** [Azure/azure-functions-powershell-worker#727]
With PowerShell Durable Functions we aren't able to use/pass the instance id in the Orchestrator Function. 
We do see that this is due to the instanceid having an internal access level as defined [here](https://github.com/Azure/azure-functions-powershell-worker/blob/2f47e2e421ba525e30cbdfde734f0a3d94932cc6/src/Durable/OrchestrationContext.cs#L23)

But the instanceId can be accessed with dotnet durable functions. 
![image](https://user-images.githubusercontent.com/40432645/147370549-d90f4f1b-002d-4b22-829f-4e6cb147360d.png)

We would like for the option to be available with PowerShell durable functions as well.

**Comment by bachuv** [comment]
cc @AnatoliB @davidmrdavid

**Comment by davidmrdavid** [comment]
Hi @anushkakda,

Thank you for reaching out. I'll add this to our list of ToDos for triaging in our upcoming meeting, this should easy to patch.
