### ISSUE TITLE
Custom module with 3. party dependencies assembly load error

### ISSUE THREAD

**Issue by Agazoth** [Azure/azure-functions-powershell-worker#733]
I am using a custom module for importing and exporting parquet data. The module can be found here: [PSParquet](https://www.powershellgallery.com/packages/PSParquet/0.0.67)

The module works on PowerShell 7.x on both Windows and Linux, but on WindowsPowerShell the module generates this error:
```powershell
Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or
one of its dependencies. The system cannot find the file specified.
```

I want to run the module in Azure Functions PowerShell Worker, but there I get the exact same error - both when debugging locally and on an actual Azure Function.

My function is setup with `powerShellVersion: '~7'`, `FUNCTIONS_EXTENSION_VERSION: '~3'` and `FUNCTIONS_WORKER_RUNTIME: 'powershell'`. Stack Settings show `Stack: PowerShell Core` and `PowerShell Core Version: PowerShell 7.0

I do not need to run the module in WindowsPowerShell and I was under the impression, that Azure Functions PowerShell Worker ran in an isolated environment. Unfortunately, that does not seem to be the case here.

I have been running Azure PowerShell functions whit custom modules for years, but this is my first go with a custom C# module with dll dependencies. I am actually able to run the module in a container and I have thought about deploying a container in stead of using Azure Functions,, but I would REALLY prefer to make the Azure Function work instead.

Can you point me in the right direction for getting this up and running in Azure Functions?

**Comment by AnatoliB** [comment]
@Agazoth This module seems to need PowerShell 7.2, which is not supported on Functions just yet (expected in a few weeks, perhaps in February).  If you are in control of the module, would you be able to rebuild it and target .NET Core 3.1 instead of .NET 6? This is probably the only reason why it does not work in PowerShell 7.0.

**Comment by Agazoth** [comment]
Hi @AnatoliB , Thanks for getting back to me. Really good news about the upcoming  7.2 support!

I tried re-building in .NET Core 3.1. That changed the error somewhat. The module still works in PS7, but in Windows PowerShell I now get:
```
Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or
one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ import-parquet C:\Temp\customers.parquet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException
```

4.2.2.0 seems to be .NET Core 3.1 related.

In the Azure Function this looks different. There I get:
```
Exception             : 
    Type       : System.IO.FileNotFoundException
    Message    : Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    FileName   : System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    TargetSite : 
        Name          : ProcessRecord
        DeclaringType : PSParquet.ImportParquetCommand
        MemberType    : Method
        Module        : PSParquet.dll
```

The Azure Function error looks like this:
```
Exception: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Stack:    at PSParquet.ImportParquetCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
2022-01-04T15:27:46.858 [Information] Executed 'Functions.GetCustomers' (Succeeded, Id=86f91165-e057-42d0-82ed-ccd2721cdf48, Duration=2220ms)
2022-01-04T15:27:46.858 [Information] Executed 'Functions.GetCustomers' (Succeeded, Id=86f91165-e057-42d0-82ed-ccd2721cdf48, Duration=2220ms)
2022-01-04T15:28:00.126 [Information] Host Status: {
  "id": "axtest667",
  "state": "Running",
  "version": "3.3.1.0",
  "versionDetails": "3.3.1 Commit hash: bd2b318013cee8d608c88203ec4ee3516d2a9961",
  "platformVersion": "96.0.10.637",
  "instanceId": "c12050d08c5c46b4185378460da05a1612da03d95949aea74b42b412a82ab1e5",
  "computerName": "10-30-2-229",
  "processUptime": 1650089,
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "2.8.3"
  }
}
```

**Comment by AnatoliB** [comment]
Hi @Agazoth,
The error you are getting on Functions looks like your assembly is still targeting a different .NET version. Do you think you can share your csproj file?
Please also note that we don't use _Windows_ PowerShell in Functions (except for the experimental support in v1 - not recommended).

**Comment by Agazoth** [comment]
Hi @AnatoliB - sure, here it is:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Parquet.Net" Version="3.9.1" />
    <PackageReference Include="IronSnappy" Version="1.3.0" />
    <PackageReference Include="PowerShellStandard.Library" Version="7.0.0-preview.1" />
  </ItemGroup>

</Project>
```

**Comment by Francisco-Gamino** [comment]
We are in the process of enabling PowerShell 7.2; However, this is several weeks away. We will update this issue as soon as 7.2 is available so you can try it. Thanks.

**Comment by AnatoliB** [comment]
@Agazoth You can also try out PowerShell 7.2 support locally right now:

- Make sure you have the latest Core Tools **v4.x** installed.
- In local.setting.json, set `FUNCTIONS_WORKER_RUNTIME_VERSION` to `7.2`

**Comment by Francisco-Gamino** [comment]
@Agazoth -- You can install the V4 Core Tools from here: https://github.com/Azure/azure-functions-core-tools#installing. In addition, you will also need to install .Net 6, which is available at: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by Agazoth** [comment]
Just tested locally. I get the same error with 7.2 and V4 Core Tools

**Comment by Francisco-Gamino** [comment]
Hello @Agazoth -- Could you please share what version of the Core Tools you are using? 

Here is my environment configuration: 

```powershell
PS C:\> func --version
4.0.3971
PS C:\> dotnet --version
6.0.101
PS C:\>
```

To figure out the PowerShell worker version, I've created a simple httptrigger function.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/12720858/151090463-8d1812a4-dac4-4604-84d2-e71897f82705.png">

To target the PowerShell 7.2 worker, I've set `FUNCTIONS_WORKER_RUNTIME_VERSION` to `7.2` in `local.settings.json`. 

Here is what my file looks like:

```
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "powershell",
    "FUNCTIONS_WORKER_RUNTIME_VERSION": "7.2",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true"
  }
}
```
This is the latest PowerShell worker 7.2 version available in the Core Tools V4:

```powershell
PS C:\> irm http://localhost:7071/api/HttpTrigger
Hello from PowerShell
Language worker version: 7.2.0-preview.9
PS C:\>

```
Could you please confirm that you are using the Core Tools version `4.0.3971`? Thanks.

**Comment by Agazoth** [comment]
@Francisco-Gamino I can confirm the following:
Language version: 7.2.0-preview.9
FUNCTIONS_WORKER_RUNTIME_VERSION: 7.2
func version:. 4.0.3971
dotner version: 6.0.101

AND: now it works! Guess a reboot fixed it ...

Thank you for your support. Any update on when will this be available in Azure?

**Comment by Francisco-Gamino** [comment]
@Agazoth -- A tentative ETA is between 4-6 weeks.

**Comment by Agazoth** [comment]
Thanks. I'm looking forward to it 😊
