### ISSUE TITLE
Switch to new gRPC package

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-powershell-worker#751]
Per [this readme](https://github.com/grpc/grpc/tree/master/src/csharp#grpc-c) and [this blogpost](https://grpc.io/blog/grpc-csharp-future/), the `Grpc.Net.Client` nuget package is now the recommended gRPC implementation for .NET/C# as opposed to the `Grpc.Core` package. The old package is currently in maintenance mode and will be deprecated in May 2022

**Comment by Francisco-Gamino** [comment]
Hello @michaelpeng36 -- I am assigning this to you since you are already working on it.
