### ISSUE TITLE
Support running on M1 Macs [PowerShell]

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-powershell-worker#752]
I'm testing an arm64 build of core tools and the PowerShell worker cannot run. Note, I'm testing with PowerShell 7.2 as that is the first version that supports arm64 (see [here](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2#installation-via-direct-download)).

This is the error I'm running into:
> Unhandled exception. System.IO.IOException: Error loading native library "/Users/erijiz/tools/func-arm/workers/powershell/7.2/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib".
> [2022-02-04T21:37:02.426Z]    at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)

I tried updating the Grpc.Core package, but it didn't help. The latest source code for the `Grpc.Core` package does not list osx-arm64 (see [here](https://github.com/grpc/grpc/blob/1979d43341f190e59fc44c99a4c79eb51372093f/src/csharp/Grpc.Core/Grpc.Core.csproj#L37)) and I don't expect them to add it considering the package is in maintenance mode. I believe the only fix will be to switch to the new grpc-dotnet package (see #751), which does not use any native dependencies.

The only workaround for users right now is to try x64 emulation. 

I recommend the PowerShell worker team addresses #751 and then I'd be happy to test the worker on my M1 Mac again.

**Comment by ejizba** [comment]
I tested `func start` with an http, timer, & queue function on v4.5.0 of the host (which includes the fix for https://github.com/Azure/azure-functions-powershell-worker/issues/751) and everything appears to be working now on an M1 Mac 🎉

As noted earlier, this only applies to PowerShell 7.2

**Comment by bshea5** [comment]
Is there an additional step I'm missing? I appears to error still for myself. I get the following output from `func start`

Azure Functions Core Tools
Core Tools Version:       4.0.4544 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.3.2.18186

And I get the following error
``` shell
[2022-05-31T18:09:19.777Z] Unhandled exception. System.IO.IOException: Error loading native library "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.4544/workers/powershell/7.2/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib". 
```

**Comment by ejizba** [comment]
No you're not missing anything. This will be included in v4.5.0 of the host which has not been released yet. The latest version of the host released is 4.3.2 as shown in your comment. I expect it to go out sometime in the next few weeks

See here for a list of core tools releases:
https://github.com/Azure/azure-functions-core-tools/releases

**Comment by ejizba** [comment]
FYI - The release of core tools with this fix finished a few days ago:

https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.4590

**Comment by invisibleaxm** [comment]
i know its an old issue but wanted to say thanks as this was a major blocker for me. Thumbs up!
