### ISSUE TITLE
Durable Functions Support for PowerShell

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-powershell-worker#77]
New Feature - Looking for votes and/or user input to gauge traction.

[Tweet-sized description and examples](https://twitter.com/TylerLeonhardt/status/1054710089544679424?s=19) by @tylerl0706

[AB#4652662](https://msazure.visualstudio.com/9912b5ff-89a4-4651-bae2-9452eb7992a8/_workitems/edit/4652662)

**Comment by ctmcisco** [comment]
Does really need a vote 😜. Definitely would love this to happen.

**Comment by obilogic** [comment]
Yes ...yes please!

**Comment by guidooliveira** [comment]
yes absolutely!

**Comment by johnmccrae** [comment]
OOh, yes please. Love that idea. Plus 1 to JustinGrote's comments.

**Comment by stefanstranger** [comment]
Yes please, we need this at a customer of mine. 👍

**Comment by omiossec** [comment]
Yes !!!

**Comment by johnnliu** [comment]
I think people are going to hate me, I want to discuss this in terms of priority.

First, we need to get PowerShell support onto AzureFunctions 2.0 and GA. 

Then, there are several much nicer to haves:

- Import from PS Gallery
- Object, streaming arguments (not serialized strings)
- Managed Service Identity support
- Azure KeyVault support, like Azure Automation - would this be a binding that's custom and generic across all 2.0 function languages?
- I even think if we have well defined PowerShell functions with arguments, the Swagger generation should be automatic.
- I also want better PowerShell logging support 

And of course Durable Functions, I want this too, but I suspect Durable Functions syntax in PowerShell might be a bit messy.  I don't know how async/await will look like, and traditionally PowerShell async is done with Jobs or Runspaces, so I'm curious what a prototype would look like.

So let me be the first in the thread to say we need PS+DF but may be lower in priority.  I don't know if we need this day 1 of PS on 2.0

**Comment by Agazoth** [comment]
Yes, please!

**Comment by SteveL-MSFT** [comment]
I would be interested in getting feedback from people who have tried durable functions supported in AzF today (C#, for example) and are familiar with the development experience.  Essentially, your orchestrator script maintains state while the activity functions are stateless.  However, there are other ways to maintain state across multiple functions to replace the need for a single monolithic script.

**Comment by vmsilvamolina** [comment]
Yes!! We need PowerShell support!

**Comment by JustinGrote** [comment]
For implementation, what seems most logical to me is to expose the orchestrator object in a variable, just like $req, initially. Later powershell functions as wrappers around the methods could make it more user friendly.

**Comment by rwaal** [comment]
I agree with @johnnliu. In my opinion, Powershell support for Azure Function V2 would come first and then other things like Durable Functions. 

Please make PS support for Azure Functions V2... please...

**Comment by bytemech** [comment]
Can we even just have the ability to have Activity functions in PowerShell?

I can see why the orchestrator function might have to stay out of PS due to the stuff it does with "await". However, I think that the biggest utility for PS would be in the Activity function especially when dealing with Azure automation.

**Comment by BrianTJackett** [comment]
> Can we even just have the ability to have Activity functions in PowerShell?
> 
> I can see why the orchestrator function might have to stay out of PS due to the stuff it does with "await". However, I think that the biggest utility for PS would be in the Activity function especially when dealing with Azure automation.

@bytemech I had the same idea for mixing a C# client + orchestrator but calling into a PowerShell ActivityTrigger.  Have you tried this yet with the preview release?

**Comment by JustinGrote** [comment]
I think following the javascript worker's example is a good first step: https://github.com/Azure/azure-functions-durable-js

**Comment by jnevins-gcm** [comment]
any update on this?

**Comment by AnatoliB** [comment]
We'll be working on this very soon. Not ready to commit to any specific date yet. Thank you for your votes!

**Comment by wstinkens** [comment]
Since PowerShell support for Azure functions is now GA, any updates on Durable Functions support for PowerShell?

**Comment by AnatoliB** [comment]
Currently work in progress.

**Comment by Abdul-Sen** [comment]
Any update on this guys? Is MS planning on adding support for this?

**Comment by anirudhgarg** [comment]
@Abdul-Sen please see Anatoli's comment above. https://github.com/Azure/azure-functions-powershell-worker/issues/77#issuecomment-556017475

 We can confirm that we have started to work on it. We have non-production supported early prototype implementation for the chaining pattern. If you would like to try it contact @AnatoliB

**Comment by AnatoliB** [comment]
If you want to try this out, see the [instructions](https://github.com/Azure/azure-functions-powershell-worker/blob/dev/docs/durable-experimental-instructions.md).

**Comment by DixonDalmeida** [comment]
Any Update?

**Comment by AnatoliB** [comment]
Please [try this out](https://github.com/Azure/azure-functions-powershell-worker/blob/dev/docs/durable-experimental-instructions.md), and thank you for your feedback!

**Comment by visualjeff** [comment]
How soon until this feature for PowerShell support goes GA?  Could you provide a ball park date?  Thank you!

**Comment by JustinGrote** [comment]
I made a quickstart to help get started with this:
https://gist.github.com/JustinGrote/63983c9a53b4085d4710befea17bc913

**Comment by AnatoliB** [comment]
Durable PowerShell support (preview scope: **Function Chaining**, **Fan-Out/Fan-In**, **Async HTTP APIs** patterns) is deployed to Azure.

In order to try it out, please switch your app to PowerShell 7 by following these instructions: https://github.com/Azure/azure-functions-powershell-worker/issues/371#issuecomment-641026259.

You can find the samples for Function Chaining and Fan-Out/Fan-In patterns here: https://github.com/Azure/azure-functions-powershell-worker/blob/dev/docs/durable-experimental-instructions.md#2-sample-app.

We will continue working on the rest. The GA timeline and the implementation completeness depend on your feedback very much! Thank you!

**Comment by AnatoliB** [comment]
I've updated the instructions at https://github.com/Azure/azure-functions-powershell-worker/blob/dev/docs/durable-experimental-instructions.md with all the steps required to try this out on Azure.

**Comment by Windos** [comment]
Has anyone got this working in Azure?

I have trouble running Functions locally in general (laptop needs a re-image... my problem) so I'm jumping straight to Azure. With both the Chaining and Fan-Out/Fan-In examples I end up with a 404.

**Comment by AnatoliB** [comment]
@Windos I've got this working in Azure :-) Please tell us more: how do you get a 404? Which function do you start and how? Are you using a correct URL (please keep in mind that the URLs in the instructions are for the local host only.

**Comment by Windos** [comment]
I'm trying both FanOutFanInStart and FunctionChainingStart. Getting the 404 in the Test/Run pane in the Portal:

![Test Pane Example](https://user-images.githubusercontent.com/6955786/85502615-c5700500-b63b-11ea-9385-4e5fa73e4270.png)

Also using the function url (both in Windows PowerShell and PowerShell 7):

![Shell Example](https://user-images.githubusercontent.com/6955786/85502809-3f07f300-b63c-11ea-84ec-1cebe224cb15.png)

Will try tearing it down and starting again later on tonight.

**Comment by Windos** [comment]
Welp, I don't know what I did differently on the third attempt, might have just required a break to avoid missing a step.

All working now (and working well!) Good job all that've worked on this.

**Comment by SimonWahlin** [comment]
I tried this on Azure and most things seemed to be working but the command Start-DurableTimer seems to not be available in Azure. I can see that it is exported from Microsoft.Azure.Functions.PowerShellWorker.psd1 in the git repository but not when I'm running in Azure. What can I do to make this available?

**Comment by AnatoliB** [comment]
@SimonWahlin `Start-DurableTimer` has been implemented just a couple of days ago. It normally takes 2-4 weeks for worker updates to be deployed to the Azure Functions service, so expect `Start-DurableTimer` to be available by the end of August.

**Comment by SimonWahlin** [comment]
I see. Thanks for the info. Great job on durable functions so far!

**Comment by AnatoliB** [comment]
Thank you everyone for your patience, feedback, and contributions! PowerShell support in Durable Functions is now [generally available](https://azure.microsoft.com/en-us/updates/powershell-support-in-durable-functions-is-now-generally-available). As always, your feedback is very welcome.

**Comment by JustinGrote** [comment]
@AnatoliB great achievement! Will the examples docs be updated?

**Comment by AnatoliB** [comment]
@JustinGrote We've recently added more samples, all the major patterns and features are supposed to be covered. There are still some minor gaps in both the docs and the implemented features. Please let us know if you find that something important is missing.

**Comment by JustinGrote** [comment]
@anatolliB none of the examples in this section have Powershell equivalents, am I looking in the wrong place?
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-sequence?tabs=csharp

**Comment by AnatoliB** [comment]
@JustinGrote You are right, the Tutorials section is not updated yet. These topic are supposed to be mostly covered by https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=powershell. But thank you for pointing this out, we'll take care of it.
