### ISSUE TITLE
Could not load module

### ISSUE THREAD

**Issue by KoenVerbeeck** [Azure/azure-functions-powershell-worker#804]
The issue is explained in the Q&A here:
https://docs.microsoft.com/en-us/answers/questions/838024/azure-function-with-powershell-could-not-load-modu.html

Basically an Azure Function with PowerShell sometimes fails with the error a module could not be loaded (dbatools in this case). But other parallel executions of the Function succeed just fine. I tried both managed dependencies and by uploading the module directly to the website, but both have the issue.

**Comment by Francisco-Gamino** [comment]
Hello @KoenVerbeeck -- Could you please add this to the top of your run.ps1 script: `Import-Module <ModuleName> -ErrorAction Stop`? This should tell us why the module could not be imported to the current session.

**Comment by KoenVerbeeck** [comment]
I added the import statement at the top inside a try catch block. Again, most calls succeed, some fail. I got a lot of these errors in the log stream:

![image](https://user-images.githubusercontent.com/7213731/168582966-53249c25-c2ef-41a7-bb8a-7ad595f4b0c3.png)

In ADF I get for a failed call the following error:

![image](https://user-images.githubusercontent.com/7213731/168583098-8e258de7-0756-4bd9-9202-e2b6f26546c0.png)

**Comment by Francisco-Gamino** [comment]
Hello @KoenVerbeeck -- Could you please share a short repro?
