### ISSUE TITLE
Azure Function with PowerShell - Bad Gateway error

### ISSUE THREAD

**Issue by KoenVerbeeck** [Azure/azure-functions-powershell-worker#805]
The issue is explained in this Q&A:
https://docs.microsoft.com/en-us/answers/questions/838007/azure-function-with-powershell-bad-gateway-error.html

Sometimes a Function called from Azure Data Factory fails with a bad gateway error, probably because ADF receives a response code it is not expecting. Other parallel executions succeed, or some fail as well. In the live log, it seems the Function App is restarting for some unknown reason.

![image](https://user-images.githubusercontent.com/7213731/167264846-632a1af4-06ff-4291-8447-97e3abb9a98f.png)

**Comment by Francisco-Gamino** [comment]
Hello @KoenVerbeeck -- Could you please open a support ticket so we can take a closer look? To do so, please follow this instructions: https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request. Thanks.

**Comment by KoenVerbeeck** [comment]
> Hello @KoenVerbeeck -- Could you please open a support ticket so we can take a closer look? To do so, please follow this instructions: https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request. Thanks.

I don't have permissions to open support tickets myself, but I asked our IT team to create one. Keep you posted.

**Comment by KoenVerbeeck** [comment]
The support ID number is 2205170050000474

**Comment by Francisco-Gamino** [comment]
Closing this issue because there is a support ticket. Please reopen if your issue is not resolved.
