### ISSUE TITLE
local.settings.json not being loaded into $env

### ISSUE THREAD

**Issue by knightian** [Azure/azure-functions-powershell-worker#819]
macos 12.4 (Intel)

Powershell 7.2.4 (Also tried with 7.1.7)

azure-functions-core-tools@4

When some environment variables are specified in the local.json.settings file to be used in local testing, they are not made available to the powershell functions when calling $env:variable_name it is just returning blank as if it is not set.

The settings file is definitely being parsed correctly as it is instructing func to use azurite and I confirmed when running func settings list that it shows the settings in the file. So something is not putting them into $env I guess?

**Comment by Francisco-Gamino** [comment]
Thanks you @knightian for reporting this issue. Would it be possible for you to share a simple repro? 

Hi @michaelpeng36 -- Could you please take a look? Also, should we move this issue to the Core Tools repro?

**Comment by knightian** [comment]
@Francisco-Gamino yep:

powershell 7.2.4 installed on macos via brew

Install dotnet 6 SDK (also dotnet 5 SDK and dotnet 3.1 core SDK however unsure if these two are needed)

Clone this repo: [https://github.com/KelvinTegelaar/CIPP-API](https://github.com/KelvinTegelaar/CIPP-API)

I install the azure function tools and azurite like so (Using Node LTS (16.5.1)):

`npm install --global azure-functions-core-tools@4 --unsafe-perms true`

`npm install --global azurite`

Then I create a local.settings.json file in the repo root directory with:

```
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "powershell",
    "FUNCTIONS_WORKER_RUNTIME_VERSION": "~7",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsSecretStorageType": "files",
    "applicationid": "59603b59-63b0-4b64-9b20-c48f0c3256dd",
    "applicationsecret": "thissecretisredacted",
    "refreshtoken": "redactedrtoken",
    "exchangerefreshtoken": "redactedertoken",
    "tenantid": "redactedtenant.onmicrosoft.com"
  }
}
```

If I run `func settings` I confirm it is parsing the JSON in the settings file and with -a shows me the correct values.

when I run `func start --verbose` all runs except it is not loading the values from local.settings.json into the $env environment variable set. When I do a `Write-Host $env:applicationid` for example, it is printing out empty as if it has not been set.

If it makes it easier the full instructions to tool the devenv are here [https://cipp.app/docs/dev/](https://cipp.app/docs/dev/)

**Comment by Francisco-Gamino** [comment]
Thank you @knightian for the repro.

@michaelpeng36 -- Could you please transfer this issue to the Core Tool repro and take a look? Thanks in advance.

**Comment by knightian** [comment]
@Francisco-Gamino I figured it out an appologies for the bumsteer. It seems that Windows does not care about case for the environment variables. So the team developing on Windows have `applicationid` in their local.settings.json file, and the code calls `$ENV:ApplicationId` and this works perfectly fine on windows, however on macOS it literally looks for `ApplicationId` which doesn't exists as it's `applicationid` and it is not as forgiving as Windows about the case insensitivity, this is why it appears blank.

So seems this isn't a bug in Azure Functions, more a nuance between OS.

Thanks for the quick response and will to assist I appreciate it! I'll close the issue.

**Comment by Francisco-Gamino** [comment]
Thank you @knightian for the update.
