### ISSUE TITLE
Function reloads all Az modules on every call

### ISSUE THREAD

**Issue by kaldurak** [Azure/azure-functions-powershell-worker#820]
I've had my FunctionApp running for awhile now - I went to add a new function and when testing the execution I noticed that it reloads all my Az modules everytime I call it.
I've tested with both the portal's test function and calling the function using the web end-point (http post)

Loading all the modules results in the call timing out which returns the nice little 'we are down - we are trying to find support to go fix the issue' message...   

This is running on a windows host and my app service plan is consumption.
I've tried restarting the FunctionApp but that doesn't fix it.

Not that it is super important but here is the invocation details:
2022-06-09 17:26:55.477
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:27:00.402
INFORMATION: Loaded Module 'Az.Aks'
Information
2022-06-09 17:27:04.112
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:27:09.045
INFORMATION: Loaded Module 'Az.AppConfiguration'
Information
2022-06-09 17:27:19.665
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:27:25.384
INFORMATION: Loaded Module 'Az.ContainerInstance'
Information
2022-06-09 17:27:30.459
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:27:35.035
INFORMATION: Loaded Module 'Az.Databricks'
Information
2022-06-09 17:27:42.849
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:27:48.044
INFORMATION: Loaded Module 'Az.DesktopVirtualization'
Information
2022-06-09 17:27:56.601
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:28:10.436
INFORMATION: Loaded Module 'Az.Functions'
Information
2022-06-09 17:28:20.710
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:28:25.511
INFORMATION: Loaded Module 'Az.Kusto'
Information
2022-06-09 17:28:38.238
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:28:45.231
INFORMATION: Loaded Module 'Az.Migrate'
Information
2022-06-09 17:29:06.948
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:29:12.420
INFORMATION: Loaded Module 'Az.RedisEnterpriseCache'
Information
2022-06-09 17:29:15.781
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:29:19.729
INFORMATION: Loaded Module 'Az.ResourceMover'
Information
2022-06-09 17:29:34.751
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:29:42.160
INFORMATION: Loaded Module 'Az.SignalR'
Information
2022-06-09 17:30:04.075
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:30:10.132
INFORMATION: Loaded Module 'Az.StreamAnalytics'
Information
2022-06-09 17:30:18.060
INFORMATION: Loaded Module 'Az.Accounts'
Information
2022-06-09 17:30:23.084
INFORMATION: Loaded Module 'Az.Websites'
Information

**Comment by Francisco-Gamino** [comment]
Hello @kaldurak -- The PowerShell worker can create multiple runspaces as needed, depending on the function execution duration and the incoming request rate. Every runspace will have to load its own set of modules. Do you think this is what is happening?

**Comment by kaldurak** [comment]
I've restarted the app, called the function,  and waited for it to timeout then tried again, each call loads the modules over again.   I get that the initial call might do this on a cold start, but every call?  Seems extreme.

**Comment by Francisco-Gamino** [comment]
Hello @kaldurak -- Could you please open a support ticket so we can take a closer look? To do so, please follow this instructions: https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request. Thanks.
