### ISSUE TITLE
Populate WorkerMetadata in WorkerInitResponse message

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-powershell-worker#821]
The protobuf has been updated to include a `WorkerMetadata` property within the `WorkerInitResponse` message. The worker should include `WorkerMetadata` when sending the `WorkerInitResponse` to the host.

[PR](https://github.com/Azure/azure-functions-language-worker-protobuf/pull/76) for reference on how to fill in the fields.

You will need to pull in the latest protobuf version first (this [doc](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/EngineeringProcesses/ReleaseProcesses/ProtobufReleaseProcess.md&version=GBmaster&_a=preview) may help).

```proto
message WorkerMetadata {
  // The runtime/stack name
  string runtime_name = 1;

  // The version of the runtime/stack
  string runtime_version = 2;

  // The version of the worker or worker SDK
  string worker_version = 3;

  // The worker bitness/architecture
  string worker_bitness = 4;

  // Optional additional custom properties
  map<string, string> custom_properties = 5;
}
```

**Comment by liliankasem** [comment]
Latest proto version is now [v1.5.8](https://github.com/Azure/azure-functions-language-worker-protobuf/releases/tag/v1.5.8-protofile)

Edit: I had to force push so please confirm the commit hash is `14b2ba5` when you pull the protobuf into your repo

**Comment by liliankasem** [comment]
@Francisco-Gamino can we prioritize this for the next sprint?

**Comment by liliankasem** [comment]
Documentation to help with implementation: https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/Design/OOPWorkers/WorkerMetadata.md&version=GBmaster&_a=preview

**Comment by Francisco-Gamino** [comment]
> @Francisco-Gamino can we prioritize this for the next sprint?

@liliankasem -- Yes, we will include this fix in the next sprint.

**Comment by liliankasem** [comment]
> > @Francisco-Gamino can we prioritize this for the next sprint?
> 
> @liliankasem -- Yes, we will include this fix in the next sprint.

Thank you!

**Comment by Francisco-Gamino** [comment]
Adding prerequisite for this work item: https://github.com/Azure/azure-functions-powershell-worker/issues/875.

**Comment by Francisco-Gamino** [comment]
> Adding prerequisite for this work item: #875.

prerequisite work item has been completed.

**Comment by Francisco-Gamino** [comment]
@liliankasem - In order to populate the language worker `RuntimeVersion`, we need to initialize the worker to use the PowerShell SDK (either `7.2` or `7.0`). Currently, this initialization takes place in the first `ProcessFunctionLoadRequest` once we know the `functionAppRoot` and whether the customer has enabled `Managed Dependencies`. However, to complete this work item, we need to move the initialization of the worker to `ProcessWorkerInitRequest`. After this change, we need to test in prod to make sure no regression are introduced. I will discuss with this with the team in our next sync up and provide a new ETA.

/cc @AnatoliB @michaelpeng36

**Comment by Francisco-Gamino** [comment]
@liliankasem -- The next deployment (which starts January 3rd) of the PowerShell worker 7.2 will have this fix.

**Comment by liliankasem** [comment]
> @liliankasem -- The next deployment (which starts January 3rd) of the PowerShell worker 7.2 will have this fix.

Great! thank you
