### ISSUE TITLE
Add docs for programming model

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-powershell-worker#86]
This should describe how our triggers, input/output bindings work, `$return`, capturing different streams, `Push-OutputBinding`, etc.

**Comment by tylerl0706** [comment]
I think this is where we should go over dependencies. Not in #88;
I'm calling this "Anatomy of a PowerShell function"

**Comment by tylerl0706** [comment]
Addressing this in https://github.com/MicrosoftDocs/azure-docs/pull/18273

**Comment by TylerLeonhardt** [comment]
Can we close this one too?

**Comment by joeyaiello** [comment]
Possibly refer to #2 for some of this info

**Comment by joeyaiello** [comment]
In a private doc repo as 57447

**Comment by anirudhgarg** [comment]
This is done. Closing this out.
