### ISSUE TITLE
Add docs for authing to Azure with service principal

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-powershell-worker#87]
We have a basic demo that authenticates into Azure using a service principal. We should doc this example and explain how/why it works.

**Comment by tylerl0706** [comment]
Eamon's doing this, yeah?

**Comment by tylerl0706** [comment]
@eamonoreilly :wave:

**Comment by joeyaiello** [comment]
Not sure that this is actually needed once we have MSI support, throwing it on the backlog.

**Comment by sspage** [comment]
This is in direct conflict with #112 where you say you are removing support for service principals.  Which is it?  Hope you are not removing it or will provide guidance on another method for AzureRM auth.

**Comment by TylerLeonhardt** [comment]
Please see my response in #112.

**Comment by anirudhgarg** [comment]
We have MSI support, closing this out.
