### ISSUE TITLE
Update Quickstart: Create a PowerShell function in Azure using Visual Studio Code to use PowerShell 7.2 and .Net Core 6 

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-powershell-worker#871]
Update Quickstart: Create a PowerShell function in Azure using Visual Studio Code to use PowerShell 7.2 and .Net Core 6.

This document is located at https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-powershell.

**Comment by ggailey777** [comment]
@Francisco-Gamino this should now be fixed in the docs. https://github.com/MicrosoftDocs/azure-docs-pr/pull/226954

**Comment by Francisco-Gamino** [comment]
Great, thank you @ggailey777.
