### ISSUE TITLE
Add docs: `func` CLI quickstart

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-powershell-worker#88]
We should have a quickstart doc outlining how to:
* create a function app
* create a function
  * timer trigger
  * HTTP trigger
* add a module dependency
* pack/publish to Azure
* show it working

**Comment by TylerLeonhardt** [comment]
I think this one can be closed now too, right @joeyaiello?

**Comment by anirudhgarg** [comment]
We do have one.
