### ISSUE TITLE
What does powerShellVersion "~7" actually mean?

### ISSUE THREAD

**Issue by Eonasdan** [Azure/azure-functions-powershell-worker#885]
Sorry if this is the right place to ask this.

I am working on making sure my FA are all on the latest LTS version of dotnet and PowerShell. I'm update my arm template to deploy a PowerShell FA. I set the value of `"powerShellVersion": "~7"` under the `Microsoft.Web/sites/properties/siteconfig`

After deploying, I checked the app in Azure and was greeted with this message:

![image](https://user-images.githubusercontent.com/1006516/199122013-dbbbcbe7-02a3-439b-aaf4-b77a732e7abe.png)

My expectation based on my experience with npm would be that the `~` means "at this version-ish". Do I need to set this specifically to 7.2? If I did, does that mean `~7.2.x`?

**Comment by Francisco-Gamino** [comment]
Hello @Eonasdan -- `"~7"` in this case refers to `"7.0.x"`. When we first added support for PowerShell 7.0, this was under the assumption that there would be no breaking changes between Powershell 7.0 and 7.2. Unfortunately, this was not the case, and as a result, we could not directly update customers with ~7 as their PowerShell version to 7.2. Going forward we will require our customers to include both the major and minor version.  

> Do I need to set this specifically to 7.2? If I did, does that mean ~7.2.x? 

Now, `7.2` means `7.2.x`.

**Comment by Eonasdan** [comment]
Thanks for the update.
