### ISSUE TITLE
Add docs: Portal quickstart

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-powershell-worker#89]
We should have a quickstart doc outlining how to do the following from the Azure portal:
* create a function app
* create a function
  * timer trigger
  * HTTP trigger
* add a module dependency
* pack/publish to Azure
* show it working

**Comment by tylerl0706** [comment]
Today, you can't create a function in the Portal. You only have the ability to publish a local function so for now, the docs for this are:

* create a function app in the portal
* push a local function app
* edit and run that function app in Azure

**Comment by TylerLeonhardt** [comment]
I think we can call this closed, right @joeyaiello?

**Comment by joeyaiello** [comment]
Let's leave this open as an updated version of this for our preview release. Might just be a validate pass, but this should be gone over before we ship publicly.

**Comment by anirudhgarg** [comment]
This is done.
