### ISSUE TITLE
How to import Azure Function Module in Local Powershell?

### ISSUE THREAD

**Issue by nrv-96** [Azure/azure-functions-powershell-worker#896]
I am trying to find out the module of durable function of Local Powershell but unable to find the module in internet.

I got the error as below:

```
Start-DurableOrchestration : The term 'Start-DurableOrchestration' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Is there any module or dependency to resolve this?

**Comment by Francisco-Gamino** [comment]
This cmdlet implementation is currently embedded into the PowerShell worker. There is no way to use it from a stand alone PowerShell session. What is your scenario? What are you trying to do?

**Comment by nrv-96** [comment]
@Francisco-Gamino 
What is your scenario? ,What are you trying to do?
I'm trying create azure durable function with activity and orchestrator with powershell, there is no any details documents to see all the azure function for powershell or no any module mention in anywhere else so, If I get in my local system then I can get better idea about all function with property.

**Comment by davidmrdavid** [comment]
Hi @NIRAVJ96,

It would help us to see an example minimal project that you're trying to run.

If you're looking for a quickstart guide, then you may find one [here](https://learn.microsoft.com/en-us/azure/azure-functions/durable/quickstart-powershell-vscode). For documentation on Durable Functions concepts, and PowerShell samples, you may review [this](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=powershell).
