### ISSUE TITLE
listener for function unable t start if web storage behind private end point 

### ISSUE THREAD

**Issue by KrisA-1** [Azure/azure-functions-powershell-worker#898]
I set up an **durable powershell function** to pause and resume our synapse dedicated pool as we have all our resources sitting behind private end points and the API we're accessible. 

**Everything works fine except if the Web storage is behind private end points. Added table, queue and blob private end points. All accessible over our private network.**

If I run the function now we see the function listeners unable to start. This is from local (when behind VPN) or from deployed function app with outbound VPN enabled.

> The listener for function 'Functions.AchangeDedicatedPoolState' was unable to start. DurableTask.AzureStorage: Forbidden. Microsoft.WindowsAzure.Storage: Forbidden.
> [2022-12-12T13:44:02.404Z] The listener for function 'Functions.OchangeDedicatedPoolState' was unable to start.
> [2022-12-12T13:44:02.407Z] The listener for function 'Functions.OchangeDedicatedPoolState' was unable to start. DurableTask.AzureStorage: Forbidden. Microsoft.WindowsAzure.Storage: Forbidden.

**Comment by davidmrdavid** [comment]
Thanks @KrisA-1, for the reaching out. The error message suggests to me that the your application is not able to connect to your storage accounts once they're behind the VNET. Just curious - how are you connecting to your storage accounts when behind a VNET? Is it via a connection string, or are you used managed identity, or something else?

**Comment by KrisA-1** [comment]
The webjobstorage is wired up to the storage account using the storage
account key. If the storage account has no private endpoints on it then
this approach works.

If I add an outbound vent on the function then it can write to the storage
account when it's behind private endpoint.

The error appeared when durable app tries to write to queue and table
storage. We added these services as private endpoints. We're seeing no
blocking from network.

The access method and account key have remained the same.

If I add a network rule to storage account to allow relevent vnet on public
inbound rules the this works but only because it's bypassing private
endpoint which defeats the object of having them.

Hope this give you enough information to help replicate.

Thanks,
Kris

**Comment by davidmrdavid** [comment]
Hi @KrisA-1,

Thanks for the response. In general, private endpoint integration isn't something that the PowerShell worker nor the Durable Functions SDK handles directly, so I suspect this is simply an issue with how these endpoints have been configured in relation to the Functions app.

As quick check: is this only affecting durable functions? For example, is a regular (non-durable) Azure Function unable to connect to storage as well? You could try creating a simple blob storage-triggered Function to see if this is the case. That would tell us a bit more about what needs to be tweaked.

In the meantime, we have extensive documention on configuring VNETs with Azure Functions. I would help if you review these in case you're missing something in your set up. See below:

1) https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-vnet
2) https://learn.microsoft.com/en-us/azure/azure-functions/configure-networking-how-to#restrict-your-storage-account-to-a-virtual-network

**Comment by KrisA-1** [comment]
Thanks David. Yes we have a dotnet function working ok. It looks like
issues with durable function writing to the queue and table endpoints.

I'll read around those docs and see if I can navigate the issues.

Thanks for your help.

Kris
