### ISSUE TITLE
MSI support for Azure PowerShell

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-powershell-worker#91]
Make `Connect-AzAccount -Identity` work the same way that it works in Azure Cloud Shell. 

For now, this is non-blocking on the prototype, but we should work to make it happen.

**Comment by tylerl0706** [comment]
Blocked on this for now. Marking as external while we wait.

**Comment by joeyaiello** [comment]
If anyone is actively investigating this one (either @daxian-dbw or @TylerLeonhardt), could you please assign yourself here?

Status is currently housed in Azure/azure-powershell#7876

**Comment by daxian-dbw** [comment]
I have done the investigation on Azure/azure-powershell#7876. Now the root cause is clear and it's up to the Azure PowerShell to resolve the issue.

**Comment by TylerLeonhardt** [comment]
as far as we are concerned - this will be fixed in #108. Once Azure PowerShell fixes `-MSI` we can modify our worker to use that new code path

**Comment by joeyaiello** [comment]
This works now!
