### ISSUE TITLE
Do Azure functions support an asynchronous polling pattern? (question)

### ISSUE THREAD

**Issue by johnravas** [Azure/azure-functions-powershell-worker#913]
I am calling a function from a Power Automate flow.  The function runs for approximately 6 minutes to complete it's task.  This exceeds the http request timeout of 2 minutes.  It appears that you can use asynchronous polling pattern to get around this timeout issue.  In this solution, the called process responds with a 202 Accepted response.  Then they establish either a polling process or the flow simply waits for the 200 OK response.

Is there a way for the function to be configured to support such a process?

**Comment by Francisco-Gamino** [comment]
Yes, we support this via PowerShell Durable Functions. Please see for more information: https://learn.microsoft.com/en-us/azure/azure-functions/durable/quickstart-powershell-vscode. For the scenario you are interested in, see https://learn.microsoft.com/en-us/azure/azure-functions/durable/quickstart-powershell-vscode#test-the-function-locally step 6.
