### ISSUE TITLE
Support reloading app settings or support dynamic configuration

### ISSUE THREAD

**Issue by TheMorganator** [Azure/azure-functions-powershell-worker#927]
There seems to be no way to force reloading app settings in PowerShell functions? When I make changes to app settings in the Azure portal and then restart the function the changes are not loaded, but rather the functions uses the old settings. This seems to be especially true for app settings that are Key Vault references.

Other languages has [dynamic configuration](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-azure-functions-csharp?tabs=in-process) support, but not PowerShell. Maybe this is possible to add to PowerShell too?

**Comment by Francisco-Gamino** [comment]
Hello @TheMorganator -- Thank you for reaching out. If you changed the value of the app settings in the Portal, and after this you restarted the app, the app settings should refresh, the dynamic configuration feature is not required for this. If this is not the case, we can look into the logs to help understand what happened. Could you please share the timestamp and the function app name (please follow this instructions to do this: https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)? 

Are you actually changing the app setting value? Or are you changing the secret value in key vault without changing the app setting?
