### ISSUE TITLE
Radom exceptions when trying to connect to azure context

### ISSUE THREAD

**Issue by v-bafa** [Azure/azure-functions-powershell-worker#957]
## Azure function structure and settings
We have 16 timer trigger functions within one function app running every 5/10/15 minutes.
FUNCTIONS_WORKER_PROCESS_COUNT = 10
FUNCTIONS_WORKER_RUNTIME = powershell
FUNCTIONS_EXTENSION_VERSION = ~4

## Command throws exceptions. 
Connect to azure with User assigned managed identity.
`Connect-AzAccount -Identity -AccountId $ENV:AZURE_CLIENT_ID`

I have this command in profile.ps1, but randomly get following exceptions when trying to read KeyVault in functions, so I put this command to each function too.

> ERROR: Run Connect-AzAccount to login.
> 
> Exception             : 
>     Type        : System.Management.Automation.PSInvalidOperationException
>     ErrorRecord : 
>         Exception             : 
>             Type    : System.Management.Automation.ParentContainsErrorRecordException
>             Message : Run Connect-AzAccount to login.
>             HResult : -2146233087
>         CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
>         FullyQualifiedErrorId : InvalidOperation
>     TargetSite  : 
>         Name          : get_DefaultContext
>         DeclaringType : Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet
>         MemberType    : Method
>         Module        : Microsoft.Azure.PowerShell.Clients.ResourceManager.dll
>     Message     : Run Connect-AzAccount to login.
>     Source      : Microsoft.Azure.PowerShell.Clients.ResourceManager
>     HResult     : -2146233079
>     StackTrace  : 
>    at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.get_DefaultContext()
>    at Microsoft.Azure.Commands.KeyVault.Models.KeyVaultCmdletBase.get_DataServiceClient()
>    at Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret.ExecuteCmdlet()
>    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
>    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
>    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
>    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
> CategoryInfo          : CloseError: (:) [Get-AzKeyVaultSecret], PSInvalidOperationException
> FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret
> InvocationInfo        : 
>     MyCommand        : Get-AzKeyVaultSecret

## Exceptions:
* Exception 1

> ERROR: The given key 'WriteWarning-System.EventHandler`1[[Microsoft.Azure.Commands.Common.Authentication.Abstractions.StreamEventArgs, Microsoft.Azure.PowerShell.Authentication.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]' was not present in the dictionary.
> 
> Exception             : 
>     Type       : System.Collections.Generic.KeyNotFoundException
>     TargetSite : 
>         Name          : ThrowKeyNotFoundException
>         DeclaringType : System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue]
>         MemberType    : Method
>         Module        : System.Collections.Concurrent.dll
>     Message    : The given key 'WriteWarning-System.EventHandler`1[[Microsoft.Azure.Commands.Common.Authentication.Abstractions.StreamEventArgs, Microsoft.Azure.PowerShell.Authentication.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]' was not present in the dictionary.
>     Source     : System.Collections.Concurrent
>     HResult    : -2146232969
>     StackTrace : 
>    at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
>    at Microsoft.Azure.Commands.Common.Authentication.AzureSession.<>c__DisplayClass86_0`1.<UnregisterComponent>b__0()
>    at Microsoft.Azure.Commands.Common.Authentication.AzureSession.UnregisterComponent[T](String componentName)
>    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.EndProcessing()
>    at System.Management.Automation.Cmdlet.DoEndProcessing()
>    at System.Management.Automation.CommandProcessorBase.Complete()
> CategoryInfo          : NotSpecified: (:) [Connect-AzAccount], KeyNotFoundException
> FullyQualifiedErrorId : System.Collections.Generic.KeyNotFoundException,Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
> InvocationInfo        : 
>     MyCommand        : Connect-AzAccount
>     ScriptLineNumber : 27
>     OffsetInLine     : 1
>     HistoryId        : 1
>     ScriptName       : C:\home\site\wwwroot\xxxx\run.ps1
>     Line             : Connect-AzAccount -Identity -AccountId $ENV:AZURE_CLIENT_ID
>                        
>     PositionMessage  : At C:\home\site\wwwroot\xxxx\run.ps1:27 char:1
>                        + Connect-AzAccount -Identity -AccountId $ENV:AZURE_CLIENT_ID
>                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     PSScriptRoot     : C:\home\site\wwwroot\xxxx
>     PSCommandPath    : C:\home\site\wwwroot\xxxx\run.ps1
>     InvocationName   : Connect-AzAccount
>     CommandOrigin    : Internal
> ScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\xxxx\run.ps1: line 27

* Exception2:

> ERROR: No such host is known. (management.azure.com:443)
> 
> Exception             : 
>     Type           : System.Net.Http.HttpRequestException
>     TargetSite     : 
>         Name          : MoveNext
>         DeclaringType : System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__98, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>         MemberType    : Method
>         Module        : System.Net.Http.dll
>     Message        : No such host is known. (management.azure.com:443)
>     InnerException : 
>         Type            : System.Net.Sockets.SocketException
>         Message         : No such host is known.
>         SocketErrorCode : HostNotFound
>         ErrorCode       : 11001
>         NativeErrorCode : 11001
>         TargetSite      : 
>             Name          : ThrowException
>             DeclaringType : System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs, System.Net.Sockets, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>             MemberType    : Method
>             Module        : System.Net.Sockets.dll
>         Source          : System.Net.Sockets
>         HResult         : -2147467259
>         StackTrace      : 
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>     Source         : System.Net.Http
>     HResult        : -2147467259
>     StackTrace     : 
>    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
>    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at Microsoft.Rest.RetryAfterDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Commands.Common.Authentication.ClaimsChallengeHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Commands.Common.Authentication.Factories.CancelRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Version2021_01_01.TenantsOperations.ListWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Version2021_01_01.TenantsOperationsExtensions.ListAsync(ITenantsOperations operations, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Version2021_01_01.TenantsOperationsExtensions.List(ITenantsOperations operations)
>    at Microsoft.Azure.Commands.ResourceManager.Common.Paging.GenericPageEnumerator`1..ctor(Func`1 list, Func`2 listNext, UInt64 first, UInt64 skip)
>    at Microsoft.Azure.Commands.ResourceManager.Common.Paging.GenericPageEnumerable`1.GetEnumerator()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at Microsoft.Azure.Commands.ResourceManager.Common.Utilities.Version2021_01_01.SubscriptionClientWrapper.ListAccountTenants(IAccessToken accessToken, IAzureEnvironment environment)
>    at Microsoft.Azure.Commands.Profile.Models.SubscriptionClientProxy.<>c__DisplayClass4_0.<ListAccountTenants>b__0(ISubscriptionClientWrapper client)
>    at Microsoft.Azure.Commands.Profile.Models.SubscriptionClientProxy.<>c.<.ctor>b__2_0(Action`1 subscriptionClientAction, LoggerWriter warning)
>    at Microsoft.Azure.Commands.Profile.Models.SubscriptionClientProxy.ListAccountTenants(IAccessToken accessToken, IAzureEnvironment environment)
>    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
>    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantIdOrName, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int32 maxContextPopulation, String authScope)
>    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass127_2.<ExecuteCmdlet>b__5()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location ---
>    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass127_0.<ExecuteCmdlet>b__1(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
>    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass136_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)
>    at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
>    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
>    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
>    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
>    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
>    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
>    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
> CategoryInfo          : CloseError: (:) [Connect-AzAccount], HttpRequestException
> FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
> InvocationInfo        : 
>     MyCommand        : Connect-AzAccount
>     ScriptLineNumber : 30
>     OffsetInLine     : 1
>     HistoryId        : 1
>     ScriptName       : C:\home\site\wwwroot\xxxx\run.ps1
>     Line             : Connect-AzAccount -Identity -AccountId $ENV:AZURE_CLIENT_ID
>

**Comment by Francisco-Gamino** [comment]
Hello @v-bafa -- Unless you have some specific reasons, we suggest that you removing this 
`FUNCTIONS_WORKER_PROCESS_COUNT` app setting and relying on the default value. Fore more information on concurrency settings, please see https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell?tabs=portal#concurrency. If you do have an specific reason, please let us know and we will help you further. Please let us know if you are still seeing this issue after removing this app settings.
