### ISSUE TITLE
Reference assemblies in the wrong place?

### ISSUE THREAD

**Issue by bittrance** [Azure/azure-functions-powershell-worker#958]
It would appear that it is currently not possible to use custom assemblies?

I am trying to use [powershell-yaml](https://github.com/cloudbase/powershell-yaml/) in my Powershell Azure Function. Rougly this:
```
using namespace System.Net
param($Request)
Import-Module powershell-yaml
Push-OutputBinding -Name Response -Value (@{
        StatusCode = [HttpStatusCode]::OK
        Body = ConvertTo-Yaml @{ "Success" = $true }
    })
```
If this function is run with `func host start`, invocation yields a wall or errors, but I believe the pertinent bit is this:
```
[2023-06-02T16:30:58.822Z] ERROR: Exception calling "GetFiles" with "3" argument(s): "Could not find a part of the path '/usr/lib/azure-functions-core-tools-4/workers/powershell/7.2/runtimes/unix/lib/net6.0/ref'."
```
Indeed, providing a symlink resolves the issue:
```
ln -s /usr/lib/azure-functions-core-tools-4/workers/powershell/7.2/ref /usr/lib/azure-functions-core-tools-4/workers/powershell/7.2/runtimes/unix/lib/net6.0/ref
```
However, the same issue occurs when the function is published to a Windows Azure Function where a symlink workaround is not feasible:
```
ERROR: Exception calling "GetFiles" with "3" argument(s): "Could not find a part of the path 'C:\Program Files (x86)\SiteExtensions\Functions\4.19.0\workers\powershell\7.2\runtimes\win\lib\net6.0\ref'."
```
I tried this out with the bundled Powershell 7.4, but the issue appears there too (and can be resolved with (`ln -s /usr/lib/azure-functions-core-tools-4/workers/powershell/7.4/ref /usr/lib/azure-functions-core-tools-4/workers/powershell/7.4/runtimes/unix/lib/net7.0/ref`)

Is this a regression on https://github.com/PowerShell/PowerShell/issues/9587 such that this issue should be reported on Powershell, or a runtime packaging issue?

Packages installed from official Microsoft Ubuntu repo:
```
ii  azure-functions-core-tools-4               4.0.5198-1                              amd64        Azure Function Core Tools v4
ii  dotnet-apphost-pack-6.0                    6.0.116-0ubuntu1~22.04.1                amd64        Internal - targeting pack for Microsoft.NETCore.App 6.0
ii  dotnet-apphost-pack-7.0                    7.0.105-0ubuntu1~22.04.1                amd64        Internal - targeting pack for Microsoft.NETCore.App 7.0
ii  dotnet-host-7.0                            7.0.105-0ubuntu1~22.04.1                amd64        dotNET host command line
ii  dotnet-hostfxr-6.0                         6.0.116-0ubuntu1~22.04.1                amd64        dotNET host resolver
ii  dotnet-hostfxr-7.0                         7.0.105-0ubuntu1~22.04.1                amd64        dotNET host resolver
ii  dotnet-runtime-6.0                         6.0.116-0ubuntu1~22.04.1                amd64        dotNET runtime
ii  dotnet-runtime-7.0                         7.0.105-0ubuntu1~22.04.1                amd64        dotNET runtime
ii  dotnet-sdk-6.0                             6.0.116-0ubuntu1~22.04.1                amd64        dotNET 6.0 Software Development Kit
ii  dotnet-sdk-7.0                             7.0.105-0ubuntu1~22.04.1                amd64        dotNET 7.0 Software Development Kit
ii  dotnet-targeting-pack-6.0                  6.0.116-0ubuntu1~22.04.1                amd64        Internal - targeting pack for Microsoft.NETCore.App 6.0
ii  dotnet-targeting-pack-7.0                  7.0.105-0ubuntu1~22.04.1                amd64        Internal - targeting pack for Microsoft.NETCore.App 7.0
ii  dotnet-templates-6.0                       6.0.116-0ubuntu1~22.04.1                amd64        dotNET 6.0 templates
ii  dotnet-templates-7.0                       7.0.105-0ubuntu1~22.04.1                amd64        dotNET 7.0 templates
```

Additional details can be found in https://github.com/cloudbase/powershell-yaml/issues/110 .

**Comment by Francisco-Gamino** [comment]
@bittrance -- For `pwsh`, the reference assemblies are located at `'$PSHOME\ref'`. However,  for applications that host PowerShell, the `ref` folder is deployed to the `publish` folder and not where `'System.Management.Automation.dll'` is located. In this case, the entry assembly's location is used to construct the path to the 'ref' folder. For more information, please see https://github.com/daxian-dbw/PowerShell/blob/afe99fcaea4c3df7c68cd00529890e29c88a2961/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L618-L633

Please note that this is by design and not a regression of https://github.com/PowerShell/PowerShell/issues/9587.

The `powershell-yaml` assumes that the `ref` folder is located at `$PSHOME/ref` as shown here: https://github.com/cloudbase/powershell-yaml/blob/9ade3620a105dde12941dbb971bbd30050780dea/powershell-yaml.psm1#L376.

Have you tried reaching out to the module owner to see if they can fix this for applications that host PowerShell?
