### ISSUE TITLE
PowerShell stream order needs to be maintained

### ISSUE THREAD

**Issue by RanjeetKumar27** [Azure/azure-functions-powershell-worker#96]
https://github.com/Azure/azure-functions-powershell-worker/blob/293f6086a763233977fcfd07e89c23930e204a2d/src/PowerShell/PowerShellManager.cs#L144-L147

The logging of output streams after the execution at L134 completes means that output streams will always be logged after other streams types, even if output stream is generated before other stream types in the actual script.

Beside, the wacky table output resulted from logging the pipeline object.

**Comment by TylerLeonhardt** [comment]
Seems reasonable to me :+1:
