### ISSUE TITLE
Az modules not loading for PowerShell 7.2 Function App

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/azure-functions-powershell-worker#977]
I keep getting ` Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException`  exceptions from `Az.Accounts` and `Az.Compute` not loading in Application insights.

```powershell
Result: ERROR: The 'Get-AzVmss' command was found in the module 'Az.Compute', but the module could not be loaded. For more information, run 'Import-Module Az.Compute'.

Exception :
Type : System.Management.Automation.CommandNotFoundException
ErrorRecord :
Exception :
Type : System.Management.Automation.ParentContainsErrorRecordException
Message : The 'Get-AzVmss' command was found in the module 'Az.Compute', but the module could not be loaded. For more information, run 'Import-Module Az.Compute'.
HResult : -2146233087
TargetObject : Get-AzVmss
CategoryInfo : ObjectNotFound: (Get-AzVmss:String) [], ParentContainsErrorRecordException
FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
```

```powershell
Result: ERROR: The 'Set-AzContext' command was found in the module 'Az.Accounts', but the module could not be loaded. For more information, run 'Import-Module Az.Accounts'.

Exception :
Type : System.Management.Automation.CommandNotFoundException
ErrorRecord :
Exception :
Type : System.Management.Automation.ParentContainsErrorRecordException
Message : The 'Set-AzContext' command was found in the module 'Az.Accounts', but the module could not be loaded. For more information, run 'Import-Module Az.Accounts'.
HResult : -2146233087
TargetObject : Set-AzContext
CategoryInfo : ObjectNotFound: (Set-AzContext:String) [], ParentContainsErrorRecordException
FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
```

I have `requirements.psd1` defined like this:

```powershell
# This file enables modules to be automatically managed by the Functions service.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'.
    # To use the Az module in your function app, please uncomment the line below.
    'Az.Accounts' = '2.12.3'
    'Az.Compute'  = '6.0.0'
    'Az.Monitor'  = '4.5.0'
    'Az.CosmosDB' = '1.11.0'
    'Az.Resources'= '6.7.0'
    'CosmosDB'    = '4.7.0'
}
```

What could be causing this? I keep getting exceptions intermittently.

I have managed dependencies enabled but since we pin specific versions we don't expect it to update frequently.

**Comment by andystaples** [comment]
I can see several potential issues here. 
Firstly, Az.CosmosDB, Az.Compute, Az.Monitor, and Az.Resources will all pull down their own version of Az.Accounts, which should always be the most current version of Az.Accounts (currently 2.12.5). This would conflict with the pinned version 2.12.3. 
Secondly, using both CosmosDB and Az.CosmosDB - from what I'm told, CosmosDB package is not recommended for use with Powershell ~7, and the Az.CosmosDB package is recommended, preferrably at version 2.0.5-preview
Can you try with the following requirements.psd1 file contents and see if it resolves the issue? 

``` 
# This file enables modules to be automatically managed by the Functions service.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'.
    # To use the Az module in your function app, please uncomment the line below.
    'Az.Compute'  = '6.0.0'
    'Az.Monitor'  = '4.5.0'
    'Az.CosmosDB' = '2.0.5-preview'
    'Az.Resources'= '6.7.0'
}
```

**Comment by ArmaanMcleod** [comment]
@andystaples Thank you for the response.

We use `CosmosDB` because the module has data plane operations which `Az.CosmosDB` does not have since it only has management plane operations. Unfortunately, it is hard for us to remove either of these modules which is why we include them both together.

If we remove `Az.Accounts` pinned version does it implicitly get the latest version that supports all modules in the requirements file?

**Comment by andystaples** [comment]
OK, good to know. It may still be worth trying to include both Cosmos modules, but without explicitly versioning Az.Accounts. Yes, essentially the worker just runs Save-Module sequentially on each item in requirements.psd1, saving them all to a common modules folder accessible by function code. This means that any requirements for each item are downloaded and installed into this folder as well. It is possible that, if you version two Az modules that have different version requirements for the same module, it will be installed twice and cause conflicts. Thankfully, it appears the versions of the various Az modules you have specified all require >= Az.Accounts 2.12.3, so they will always pull down the latest version.

**Comment by guri-s** [comment]
This appears to be working, the Az.Accounts module when removed from `requirements.psd1` still gets downloaded & have not seen module loading errors so far.

**Comment by ArmaanMcleod** [comment]
Thank you @andystaples for your support. Seems to have helped us resolve the modules issues.

**Comment by andystaples** [comment]
Glad to hear it! Closing this issue
