### ISSUE TITLE
Update language worker to support parsing command-line arguments prefix with `functions-<argumentname>`

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-powershell-worker#992]
The command-line arguments that the language worker receives from the Functions Host have generic names (such as 'host' and 'port'). This can cause conflicts with other environment variables in certain environments. To address this issue, the Functions Host will now send a new set of arguments prefixed with `functions-<argumentname>`. This will be in addition to the existing arguments.

With the current parsing implementation, the language worker throws and it is not able to start given that the new prefix options are unknown, see error below:

```
ERROR(S):
  Option 'functions-uri' is unknown.
  Option 'functions-workerid' is unknown.
  Option 'functions-requestid' is unknown.
  Option 'functions-grpcmaxmessagelength' is unknown.
```
To resolve the language worker parsing issue, we need to do the following:

1) Add support for the new prefix arguments.
2) Ignore unknown arguments (this will be useful in preparation for number 3).
3) After the Functions Host changes have propagated, and we have a Core Tools version with this new Functions Host, we can remove the parsing support for the old arguments.

This is the PR that contains the Functions Host changes: https://github.com/Azure/azure-functions-host/pull/9514.

/cc @fabiocav @kshyju

**Comment by fabiocav** [comment]
Could you set the parser setting to ignore unknown arguments? The command line parser supports that and it might be a better option than the current strict model. Unless you do that, you might not be able to remove the old option.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.
